"""Deterministic auto-commit helper for project-scope skill-tree changes.

When Ralph Workflow installs a fresh skill bundle via the pre-pipeline sync
(``_sync_shipped_skills_on_pipeline_run`` in ``ralph/cli/commands/run.py``),
the project-canonical and its sibling fan-out entries can drift away from
HEAD. Without an auto-commit, the development agent sees those changes in
its working tree on the next ``ralph`` run and the ``development_commit_cleanup``
phase logs a WARNING for every tracked ``.agents/skills/<name>`` symlink.

This module provides the deterministic single-commit resolution:

* ``SKILL_AUTO_COMMIT_SUBJECT`` -- the LITERAL conventional-commit subject
  line ``chore(skills): sync baseline bundle``. Pinned by
  ``ralph.testing.audit_skill_auto_commit`` so a future rename is a
  contract change that updates both the helper and the audit in the same
  commit.

* ``commit_skill_updates`` -- the helper that scans the FIVE
  ``_SKILL_ROOT_PREFIXES`` for dirty paths, filters out anything outside
  those prefixes (defensive filter against drift in the constant), stages
  the surviving paths via the injected ``stage_fn``, builds the
  deterministic commit body listing every changed skill name (sorted) under
  the ``Changed skills:`` header, and creates the commit via the injected
  ``create_commit_fn``.

The helper is BEST-EFFORT: every I/O path returns ``None`` (or the appropriate
default) when the repo is not a git repo, when the FIVE skill roots are all
clean, or when any ``OSError`` / ``GitCommandError`` fires. The caller
(``_sync_shipped_skills_on_pipeline_run``) wraps the helper in
``try/except Exception`` and logs a DEBUG line on failure so a broken git
state cannot block the pipeline.

Dependency injection contract (matches the convention used by
``ralph/git/commit_cleanup.py::untrack_engine_internal_files``):

* ``create_commit_fn(repo_root, message) -> str`` is REQUIRED -- the
  caller (``_sync_shipped_skills_on_pipeline_run``) passes the production
  ``create_commit`` from ``ralph.git.operations``. Tests inject a stub.
* ``stage_fn(repo_root, files) -> None`` is keyword-only OPTIONAL with a
  production default of ``stage_files`` from ``ralph.git.operations``.
  Tests inject a spy to pin AC-04 (selective staging).

The deterministic commit message always carries the Ralph Workflow coauthor
trailer via the production ``create_commit`` flow; that is the documented
contract for every Ralph-managed commit (see the existing ``e4b47d2fb``
``chore(skills): ...`` and ``c2465d497`` ``feat(skills-package): ...``
commits).
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, cast

from loguru import logger

from ralph.skills._agent_paths import _SKILL_ROOT_PREFIXES

if TYPE_CHECKING:
    from collections.abc import Callable

    from git import Repo

# The deterministic conventional-commit subject line. Pinned by
# ralph.testing.audit_skill_auto_commit.
SKILL_AUTO_COMMIT_SUBJECT: str = "chore(skills): sync baseline bundle"

# Default commit-body header -- explains to humans (and to ``git log``)
# that the commit is generated, not authored by a human.
_SKILL_AUTO_COMMIT_HEADER: str = "Auto-generated by Ralph skill sync"

# Section header under which the changed skill names are listed.
_SKILL_AUTO_COMMIT_CHANGED_SKILLS_HEADER: str = "Changed skills:"

# ``git status --porcelain`` lines start with a 2-char status code followed
# by a single space -- so a valid line has at least 4 characters of prefix
# before the path body begins. Lines shorter than this are noise (e.g. an
# empty trailing newline).
_GIT_PORCELAIN_PREFIX_LEN: int = 4


def _list_dirty_skill_paths(repo: Repo, prefix: str) -> list[str]:
    """Return sorted repo-relative paths under ``prefix`` that are dirty.

    Args:
        repo: An open ``git.Repo`` instance.
        prefix: A FIVE skill-root prefix (e.g. ``.opencode/skills/``).

    Returns:
        Sorted list of repo-relative path strings reported as dirty by
        ``git status --porcelain -- <prefix>``. Paths outside the prefix
        are filtered out defensively.

    Notes:
        ``git status --porcelain --untracked-files=all -- <prefix>`` returns
        lines of the form ``XY path`` where ``XY`` is a 2-char status code
        (or ``??`` for untracked). We strip the 2-char prefix and any
        leading space, then re-validate that the path actually starts with
        the requested prefix. ``--untracked-files=all`` is required so the
        helper sees nested untracked files like
        ``.opencode/skills/<name>/SKILL.md`` (default
        ``git status --porcelain`` collapses them to the parent directory).
    """
    raw = cast("str", repo.git.status("--porcelain", "--untracked-files=all", "--", prefix))
    dirty: list[str] = []
    for line in raw.splitlines():
        if len(line) < _GIT_PORCELAIN_PREFIX_LEN:
            continue
        path = line[_GIT_PORCELAIN_PREFIX_LEN - 1 :].strip()
        if path.startswith(prefix):
            dirty.append(path)
    return sorted(set(dirty))


def _extract_skill_names(dirty_paths: list[str]) -> list[str]:
    """Extract the sorted unique skill names from a list of dirty paths.

    A skill path is any path under one of the FIVE ``_SKILL_ROOT_PREFIXES``.
    The skill name is the first path segment after the prefix
    (e.g. ``.opencode/skills/brainstorming/SKILL.md`` -> ``brainstorming``).
    Paths that do not have at least one segment after the prefix are
    skipped defensively.
    """
    names: set[str] = set()
    for path in dirty_paths:
        for prefix in _SKILL_ROOT_PREFIXES:
            if not path.startswith(prefix):
                continue
            tail = path[len(prefix) :].strip("/")
            if not tail:
                continue
            skill_name = tail.split("/", 1)[0]
            if skill_name:
                names.add(skill_name)
            break
    return sorted(names)


def commit_skill_updates(
    repo_root: Path | str,
    create_commit_fn: Callable[[Path | str, str], str],
    *,
    stage_fn: Callable[[Path | str, list[str]], None] | None = None,
) -> str | None:
    """Create a deterministic auto-commit for project-scope skill-tree changes.

    The function:

      (1) lazy-imports ``git.Repo`` / ``InvalidGitRepositoryError`` /
          ``GitCommandError`` (lazy so the module import has no side
          effects on environments that do not have a working tree),
      (2) opens ``repo_root`` as a git repo and returns ``None`` on
          ``InvalidGitRepositoryError`` (no commit when the workspace is
          not a git repo),
      (3) iterates the FIVE ``_SKILL_ROOT_PREFIXES`` and collects dirty
          paths via ``git status --porcelain -- <prefix>``,
      (4) applies a DEFENSIVE FILTER -- any path NOT under one of the
          FIVE prefixes is excluded from the auto-commit, even if
          ``git status`` reported it. This pins AC-04: the auto-commit
          stages ONLY skill-root paths.
      (5) returns ``None`` when the filtered set is empty (no commit when
          the skill tree is clean),
      (6) calls ``stage_fn(repo_root, sorted_filtered_paths)`` with the
          default ``stage_files`` from ``ralph.git.operations`` (so
          modified, untracked, and deleted entries are all handled
          consistently for the selected scope),
      (7) builds the commit body as
          ``"Auto-generated by Ralph skill sync\\n\\nChanged skills:\\n"
          + "\\n".join(f"- {name}" for name in sorted_changed_names)``
          and calls ``create_commit_fn(repo_root, subject + "\\n\\n" + body)``,
      (8) returns the SHA returned by ``create_commit_fn`` on success.

    Args:
        repo_root: Path to the repository root (typically the workspace
            root of the current ``ralph`` run).
        create_commit_fn: REQUIRED callable that creates a commit and
            returns its SHA. The production call from
            ``_sync_shipped_skills_on_pipeline_run`` passes
            ``ralph.git.operations.create_commit``; tests pass a stub.
        stage_fn: Keyword-only OPTIONAL callable that stages the provided
            paths. Defaults to ``stage_files`` from
            ``ralph.git.operations``. Tests inject a spy.

    Returns:
        The commit SHA on success, ``None`` when no commit was created
        (non-git repo, clean skill tree, or any ``OSError`` /
        ``GitCommandError``).
    """
    try:
        from git import GitCommandError, InvalidGitRepositoryError, Repo  # noqa: PLC0415

        if stage_fn is None:
            from ralph.git.operations import stage_files  # noqa: PLC0415

            stage_fn = stage_files

        repo_root_path = Path(repo_root)
        try:
            repo = Repo(repo_root_path)
        except (InvalidGitRepositoryError, Exception):
            logger.debug(
                "commit_skill_updates: {} is not a git repo; skipping auto-commit",
                repo_root_path,
            )
            return None

        try:
            all_dirty: list[str] = []
            for prefix in sorted(_SKILL_ROOT_PREFIXES):
                all_dirty.extend(_list_dirty_skill_paths(repo, prefix))
            # Defensive filter: drop any path NOT under one of the FIVE
            # prefixes, even if ``git status --porcelain -- <prefix>``
            # somehow returned it. This pins AC-04.
            all_dirty = sorted(
                {
                    path
                    for path in all_dirty
                    if any(path.startswith(prefix) for prefix in _SKILL_ROOT_PREFIXES)
                }
            )
            if not all_dirty:
                return None
            stage_fn(repo_root_path, all_dirty)
            skill_names = _extract_skill_names(all_dirty)
            body_lines = [_SKILL_AUTO_COMMIT_HEADER, "", _SKILL_AUTO_COMMIT_CHANGED_SKILLS_HEADER]
            body_lines.extend(f"- {name}" for name in skill_names)
            body = "\n".join(body_lines)
            message = f"{SKILL_AUTO_COMMIT_SUBJECT}\n\n{body}"
            return create_commit_fn(repo_root_path, message)
        except (OSError, GitCommandError) as exc:
            logger.debug("commit_skill_updates: auto-commit failed (non-fatal): {}", exc)
            return None
        finally:
            repo.close()
    except (OSError, GitCommandError) as exc:
        logger.debug("commit_skill_updates: outer guard caught (non-fatal): {}", exc)
        return None


__all__ = [
    "SKILL_AUTO_COMMIT_SUBJECT",
    "commit_skill_updates",
]
