//! File length checking with workspace-aware detection.
//!
//! Uses std::env::current_dir() to determine workspace root - this is
//! appropriate for runtime/ module per boundaries.md.

use rustc_lint::{EarlyContext, EarlyLintPass, LintContext};
use rustc_session::{declare_lint, impl_lint_pass};
use rustc_span::{FileName, SourceFile, Span};
use std::collections::HashSet;
use std::path::{Component, Path};
use std::sync::Arc;

declare_lint! {
    /// ### What it does
    ///
    /// Checks for files exceeding 1000 lines (must refactor).
    ///
    /// ### Why is this bad?
    ///
    /// Large files are harder to navigate and maintain. They often indicate
    /// a module with too many responsibilities.
    ///
    /// ### Example
    ///
    /// A file with 1500 lines should be split into multiple modules.
    pub FILE_TOO_LONG,
    Deny,
    "file exceeds 1000 lines and must be refactored"
}

pub const AUTOGENERATED_MARKER: &str = "reason=\"autogenerated\"";

pub const CONSIDER_REFACTOR_LINES: usize = 500;
pub const MUST_REFACTOR_LINES: usize = 1000;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FileLengthDisposition {
    Allowed,
    ConsiderRefactor,
    MustRefactor,
}

pub fn classify_file_length(total_lines: usize) -> FileLengthDisposition {
    if total_lines >= MUST_REFACTOR_LINES {
        FileLengthDisposition::MustRefactor
    } else if total_lines >= CONSIDER_REFACTOR_LINES {
        FileLengthDisposition::ConsiderRefactor
    } else {
        FileLengthDisposition::Allowed
    }
}

#[derive(Default)]
pub struct FileTooLong {
    warned_files: HashSet<String>,
}

impl_lint_pass!(FileTooLong => [FILE_TOO_LONG]);

pub fn register_lints(_sess: &rustc_session::Session, lint_store: &mut rustc_lint::LintStore) {
    lint_store.register_lints(&[FILE_TOO_LONG]);
    lint_store.register_early_pass(|| Box::new(FileTooLong::default()));
}

fn path_contains_component(path: &Path, target: &str) -> bool {
    path.components()
        .any(|component| matches!(component, Component::Normal(name) if name == target))
}

pub fn current_workspace_root() -> Option<std::path::PathBuf> {
    std::env::current_dir()
        .ok()
        .and_then(|path| path.canonicalize().ok().or(Some(path)))
}

fn canonicalize_for_filter(path: &Path) -> std::path::PathBuf {
    path.canonicalize().unwrap_or_else(|_| path.to_path_buf())
}

pub fn is_local_project_file(name: &FileName) -> bool {
    let FileName::Real(real_name) = name else {
        return false;
    };

    let Some(path) = real_name.local_path() else {
        return false;
    };

    let canonical_path = canonicalize_for_filter(path);

    if path_contains_component(&canonical_path, ".cargo")
        || path_contains_component(&canonical_path, ".rustup")
        || path_contains_component(&canonical_path, "target")
    {
        return false;
    }

    current_workspace_root()
        .map(|root| canonical_path.starts_with(root))
        .unwrap_or(false)
}

pub fn get_file_display_path(name: &FileName) -> Option<String> {
    match name {
        FileName::Real(real_name) => real_name.local_path().map(|p| p.display().to_string()),
        _ => None,
    }
}

pub fn file_marked_as_autogenerated(source: &str) -> bool {
    source.lines().take(20).any(|line| {
        let compact: String = line.chars().filter(|ch| !ch.is_whitespace()).collect();
        compact.contains(AUTOGENERATED_MARKER)
    })
}

fn file_length_help() -> &'static str {
    "split this file by responsibility into smaller modules with explicit seams and focused helpers - files this large usually hide multiple responsibilities, make review and navigation harder, and weaken module boundaries. See `docs/code-style/module-organization.md`."
}

impl FileTooLong {
    pub fn check_source_file(&mut self, cx: &EarlyContext<'_>, source_file: &Arc<SourceFile>) {
        if !is_local_project_file(&source_file.name) {
            return;
        }

        let Some(file_path) = get_file_display_path(&source_file.name) else {
            return;
        };

        if source_file
            .src
            .as_ref()
            .is_some_and(|source| file_marked_as_autogenerated(source.as_ref()))
        {
            return;
        }

        if self.warned_files.contains(&file_path) {
            return;
        }

        let total_lines = source_file.count_lines();

        if classify_file_length(total_lines) == FileLengthDisposition::MustRefactor {
            self.warned_files.insert(file_path.clone());

            let warning_span = Span::with_root_ctxt(source_file.start_pos, source_file.start_pos);

            cx.span_lint(FILE_TOO_LONG, warning_span, |diag| {
                diag.primary_message(format!(
                    "file has {total_lines} lines (>= {MUST_REFACTOR_LINES}) - MUST refactor"
                ));
                diag.help(file_length_help());
                diag.note(
                    "style guides: `docs/code-style/module-organization.md` and \
                     `docs/code-style/architecture.md`.",
                );
            });
        }
    }
}

impl EarlyLintPass for FileTooLong {
    fn check_crate(&mut self, cx: &EarlyContext<'_>, _krate: &rustc_ast::Crate) {
        let source_map = cx.sess().source_map();

        source_map.files().iter().for_each(|source_file| {
            self.check_source_file(cx, source_file);
        });
    }
}

#[cfg(test)]
mod tests {
    use super::FileLengthDisposition;
    use super::{
        classify_file_length, file_length_help, file_marked_as_autogenerated,
        path_contains_component,
    };
    use std::path::Path;

    #[test]
    fn detects_cargo_component() {
        assert!(path_contains_component(
            Path::new("/home/.cargo/registry/src/lib.rs"),
            ".cargo"
        ));
    }

    #[test]
    fn detects_rustup_component() {
        assert!(path_contains_component(
            Path::new("/home/.rustup/toolchains/nightly/lib.rs"),
            ".rustup"
        ));
    }

    #[test]
    fn detects_autogenerated_marker() {
        let source = "// reason = \"autogenerated\"\nfn generated() {}\n";
        assert!(file_marked_as_autogenerated(source));
    }

    #[test]
    fn files_below_500_are_allowed() {
        assert_eq!(classify_file_length(499), FileLengthDisposition::Allowed);
    }

    #[test]
    fn files_at_500_are_consider_refactor() {
        assert_eq!(
            classify_file_length(500),
            FileLengthDisposition::ConsiderRefactor
        );
    }

    #[test]
    fn files_at_1000_are_must_refactor() {
        assert_eq!(
            classify_file_length(1000),
            FileLengthDisposition::MustRefactor
        );
    }

    #[test]
    fn help_explains_why_large_files_must_be_split() {
        let help = file_length_help();

        assert!(help.contains("multiple responsibilities"));
        assert!(help.contains("harder to review"));
    }
}
