"""Agent output parsers: one per agent transport, plus a generic fallback.

This package converts raw stdout lines from an agent subprocess into structured
``AgentOutputLine`` objects for the invocation engine in ``ralph.agents.invoke``.

Main entry points:

- ``get_parser(parser_type)`` — factory function; maps a parser type name string
  (``'claude'``, ``'claude_interactive'``, ``'codex'``, ``'gemini'``, ``'opencode'``,
  ``'nanocoder'``, ``'pi'``, ``'generic'``) to the corresponding parser instance. Raises
  ``ValueError`` for unknown names.
- ``AgentParser`` — the protocol that all parsers implement; defines ``parse``.
- ``AgentOutputLine`` — structured parse result (``type``, ``content``, ``raw``,
  ``metadata``).
- ``ClaudeParser`` — parses Claude stream-JSON NDJSON output.
- ``ClaudeInteractiveParser`` — parses interactive Claude transcript output.
- ``CodexParser`` — parses Codex per-event JSON output.
- ``GeminiParser`` — parses Gemini output.
- ``NanocoderParser`` — parses Nanocoder interactive PTY output.
- ``OpenCodeParser`` — parses OpenCode NDJSON stream output.
- ``PiParser`` — parses pi.dev AgentSessionEvent NDJSON stream output.
- ``GenericParser`` — fallback parser for unknown or plain-text agent output.

Parser selection is driven by ``AgentConfig.json_parser`` (a ``JsonParserType`` enum
value in ``ralph.config.enums``) or, for agents registered via
``register_agent_support()``, by the agent's command name when
``json_parser == JsonParserType.GENERIC``. The runtime calls ``get_parser()`` with the
resolved key and consumes normalized lines through ``parser.parse()``.

To add a parser for a new agent transport, create a module in this package, implement
``AgentParser``, and register the class in both the default-catalog seed
(``ralph.agents.catalog._DEFAULT_BUILTIN_PARSER_TYPES``) and ``__all__``.
"""

from __future__ import annotations

import importlib
import sys
import types
from typing import TYPE_CHECKING, Protocol, cast, runtime_checkable

from ralph.config.enums import AgentTransport, JsonParserType

from ._ndjson_base import NdjsonParserBase
from .agent_output_line import AgentOutputLine
from .agy import AgyParser
from .base import AgentParser
from .claude import ClaudeParser
from .claude_interactive import ClaudeInteractiveParser
from .codex import CodexParser
from .cursor import CursorParser
from .gemini import GeminiParser
from .generic import GenericParser
from .nanocoder import NanocoderParser
from .opencode import OpenCodeParser
from .pi import PiParser

if TYPE_CHECKING:
    from collections.abc import Mapping

    from ralph.agents.catalog import AgentCatalog
    from ralph.agents.idle_watchdog import SubagentPidRegistry

__all__ = [
    "_CUSTOM_COMMAND_REGISTRY",
    "_PARSER_REGISTRY",
    "AgentOutputLine",
    "AgentParser",
    "AgyParser",
    "ClaudeInteractiveParser",
    "ClaudeParser",
    "CodexParser",
    "CursorParser",
    "GeminiParser",
    "GenericParser",
    "NanocoderParser",
    "NdjsonParserBase",
    "OpenCodeParser",
    "PiParser",
    "resolve_parser_key",
]


class _ParserFactory(Protocol):
    def __call__(
        self,
        *,
        subagent_pid_registry: object | None = None,
        subagent_source_label: str | None = None,
    ) -> AgentParser: ...


@runtime_checkable
class _RegisteredParserFactory(_ParserFactory, Protocol):
    transport: AgentTransport


class _CatalogModule(Protocol):
    def default_catalog(self) -> AgentCatalog: ...


def _catalog_module() -> _CatalogModule:
    """Load the catalog lazily to preserve the parser/catalog import boundary."""
    return cast("_CatalogModule", importlib.import_module("ralph.agents.catalog"))


# Public read-only views over the AgentCatalog's mutable state dicts.
#
# These are :class:`types.MappingProxyType` instances that wrap the
# default catalog's ``state.parsers`` and ``state.commands`` dicts.
# They are created lazily (on first attribute access) to break the
# catalog <-> parsers import cycle: catalog.py imports the parser
# classes from this package's submodules at module load time, so the
# ``__getattr__`` below defers the catalog import until first access.
#
# The variables are NOT defined at module level so that Python's
# module-attribute lookup falls through to ``__getattr__`` on first
# access.  Once created, the view is cached in ``globals()`` so
# subsequent accesses return the same object.


def __getattr__(name: str) -> object:
    if name == "_PARSER_REGISTRY":
        state_parsers: Mapping[str, _ParserFactory] = cast(
            "Mapping[str, _ParserFactory]",
            _catalog_module().default_catalog()._state.parsers,
        )
        parser_view: Mapping[str, _ParserFactory] = types.MappingProxyType(state_parsers)
        globals()["_PARSER_REGISTRY"] = parser_view  # type: ignore[misc]  # reason: autogenerated code has no type support, see docs/agents/type-ignore-policy.md#autogenerated-code
        return parser_view
    if name == "_CUSTOM_COMMAND_REGISTRY":
        state_commands: Mapping[str, _ParserFactory] = cast(
            "Mapping[str, _ParserFactory]",
            _catalog_module().default_catalog()._state.commands,
        )
        command_view: Mapping[str, _ParserFactory] = types.MappingProxyType(state_commands)
        globals()["_CUSTOM_COMMAND_REGISTRY"] = command_view  # type: ignore[misc]  # reason: autogenerated code has no type support, see docs/agents/type-ignore-policy.md#autogenerated-code
        return command_view
    msg = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(msg)


def _view(name: str) -> Mapping[str, _ParserFactory]:
    """Module-attribute lookup that triggers ``__getattr__`` for lazy views.

    Used by internal functions (``get_parser``, ``resolve_parser_key``)
    that need to read the legacy module-level views at call time without
    forcing eager module-level definitions that would create a circular
    import with ``ralph.agents.catalog``.
    """
    return cast("Mapping[str, _ParserFactory]", getattr(sys.modules[__name__], name))


def resolve_parser_key(
    command: str,
    json_parser: JsonParserType,
    transport: AgentTransport,
) -> str:
    """Resolve the parser-type key for an agent configuration.

    The resolution order matches the runtime lookup path:

    1. The bundled interactive Claude command uses the
       ``claude_interactive`` parser.  This check precedes registered-command
       lookup because ``claude`` is also the bundled headless parser key.
    2. Agents registered via ``register_agent_support()`` are keyed by their
       command name.  When the command name is present in ``_PARSER_REGISTRY``
       as a bundled entry and the registered transport matches ``transport``,
       that command name is the key.  This lets custom interactive agents
       override the built-in ``claude_interactive`` parser.
    3. Built-in interactive Claude still falls back to the
       ``claude_interactive`` parser when no registered entry matched.
    4. When ``json_parser`` is ``JsonParserType.GENERIC`` and a built-in
       parser is registered under the agent's command name, that command name
       is the key.
    5. When the command-name lookup fails (e.g. ``RALPH_AGY_BINARY`` rewrites
       the cmd to a wrapper path), fall back to the transport-based parser
       registered in the default catalog.  This ensures AgentTransport.AGY
       routes through :class:`AgyParser` even when the command is the mock
       wrapper path rather than the literal ``agy`` binary.
    6. Otherwise fall back to ``str(json_parser)``.

    Args:
        command: The agent's configured command string (e.g. ``"claude"``).
        json_parser: The parser type token from the agent configuration.
        transport: Optional transport enum; ``CLAUDE_INTERACTIVE`` is special-cased.

    Returns:
        A parser-type key suitable for :func:`get_parser`.
    """
    command_lower = command.lower() if command else ""
    if command_lower == "claude" and transport == AgentTransport.CLAUDE_INTERACTIVE:
        return "claude_interactive"
    custom_entry = _view("_CUSTOM_COMMAND_REGISTRY").get(command_lower)
    if isinstance(custom_entry, _RegisteredParserFactory) and custom_entry.transport == transport:
        return command_lower
    if transport == AgentTransport.CLAUDE_INTERACTIVE:
        return "claude_interactive"
    command_name = command.split(maxsplit=1)[0].lower() if command else ""
    parser_registry = _view("_PARSER_REGISTRY")
    if command_name and command_name in parser_registry and json_parser == JsonParserType.GENERIC:
        return command_name
    if transport is not None and json_parser == JsonParserType.GENERIC:
        transport_key = str(transport)
        if transport_key in parser_registry:
            return transport_key
    return str(json_parser)


def get_parser(
    parser_type: str,
    *,
    subagent_pid_registry: SubagentPidRegistry | None = None,
    subagent_source_label: str | None = None,
) -> AgentParser:
    """Get parser instance by type name or by a registered custom command.

    Args:
        parser_type: Parser type name (claude, codex, gemini, opencode, generic)
            or the full executable command of a custom-registered agent.
        subagent_pid_registry: Optional R5 (Trustworthy Idle Watchdog)
            per-invocation shared :class:`SubagentPidRegistry`. When
            provided AND ``subagent_source_label`` is also provided, the
            parser will register any PID discovered in structured
            child-lifecycle events into the shared registry. Both
            kwargs default to ``None`` for full backward-compat with
            the legacy zero-arg ``parser_factory()`` call.
        subagent_source_label: Per-transport source label (e.g.
            ``"claude"``, ``"codex"``) used by the parser when
            registering PIDs into the shared registry. ``None`` keeps
            the registration hook no-op.

    Returns:
        Parser instance implementing AgentParser protocol.

    Raises:
        ValueError: If parser type is unknown.
    """
    parser_cls = _view("_PARSER_REGISTRY").get(parser_type.lower())
    if parser_cls is not None:
        return parser_cls(
            subagent_pid_registry=subagent_pid_registry,
            subagent_source_label=subagent_source_label,
        )
    custom_entry = _view("_CUSTOM_COMMAND_REGISTRY").get(parser_type.lower())
    if isinstance(custom_entry, _RegisteredParserFactory):
        # Custom-command parser factories are stored as class refs (the
        # ``BuiltinAgentSpec.parser_factory`` typed as ``Callable[[], AgentParser]``).
        # The registered classes accept the registry kwargs by
        # contract; passing them is safe (legacy zero-arg classes that
        # ignore the kwargs continue to work because the kwargs are
        # keyword-only with defaults). The entry's ``__call__`` method
        # carries the typed kwargs signature; calling ``parser_factory``
        # directly would reject the kwargs at type-check time.
        return custom_entry(
            subagent_pid_registry=subagent_pid_registry,
            subagent_source_label=subagent_source_label,
        )
    msg = f"Unknown parser type: {parser_type}"
    raise ValueError(msg)
