"""Agent output parsers: one per agent transport, plus a generic fallback.

This package converts raw stdout lines from an agent subprocess into structured
``AgentOutputLine`` objects for the invocation engine in ``ralph.agents.invoke``.

Main entry points:

- ``get_parser(parser_type)`` — factory function; maps a parser type name string
  (``'claude'``, ``'claude_interactive'``, ``'codex'``, ``'gemini'``, ``'opencode'``,
  ``'generic'``) to the corresponding parser instance. Raises ``ValueError`` for
  unknown names.
- ``AgentParser`` — the protocol that all parsers implement; defines ``parse``.
- ``AgentOutputLine`` — structured parse result (``type``, ``content``, ``raw``,
  ``metadata``).
- ``ClaudeParser`` — parses Claude stream-JSON NDJSON output.
- ``ClaudeInteractiveParser`` — parses interactive Claude transcript output.
- ``CodexParser`` — parses Codex per-event JSON output.
- ``GeminiParser`` — parses Gemini output.
- ``OpenCodeParser`` — parses OpenCode NDJSON stream output.
- ``GenericParser`` — fallback parser for unknown or plain-text agent output.

Parser selection is driven by ``AgentConfig.json_parser`` (a ``JsonParserType`` enum
value in ``ralph.config.enums``) or, for agents registered via
``register_agent_support()``, by the agent's command name when
``json_parser == JsonParserType.GENERIC``. The runtime calls ``get_parser()`` with the
resolved key and consumes normalized lines through ``parser.parse()``.

To add a parser for a new agent transport, create a module in this package, implement
``AgentParser``, and register the class in both the default-catalog seed
(``ralph.agents.catalog._DEFAULT_BUILTIN_PARSER_TYPES``) and ``__all__``.
"""

from __future__ import annotations

import sys
import types
from typing import TYPE_CHECKING, cast

from ralph.config.enums import AgentTransport, JsonParserType

from ._ndjson_base import NdjsonParserBase
from .agent_output_line import AgentOutputLine
from .base import AgentParser
from .claude import ClaudeParser
from .claude_interactive import ClaudeInteractiveParser
from .codex import CodexParser
from .gemini import GeminiParser
from .generic import GenericParser
from .opencode import OpenCodeParser

if TYPE_CHECKING:
    from collections.abc import Mapping

    from ralph.agents.catalog import _ParserRegistryEntry

__all__ = [
    "_CUSTOM_COMMAND_REGISTRY",
    "_PARSER_REGISTRY",
    "AgentOutputLine",
    "AgentParser",
    "ClaudeInteractiveParser",
    "ClaudeParser",
    "CodexParser",
    "GeminiParser",
    "GenericParser",
    "NdjsonParserBase",
    "OpenCodeParser",
    "resolve_parser_key",
]


# Public read-only views over the AgentCatalog's mutable state dicts.
#
# These are :class:`types.MappingProxyType` instances that wrap the
# default catalog's ``state.parsers`` and ``state.commands`` dicts.
# They are created lazily (on first attribute access) to break the
# catalog <-> parsers import cycle: catalog.py imports the parser
# classes from this package's submodules at module load time, so the
# ``__getattr__`` below defers the catalog import until first access.
#
# The variables are NOT defined at module level so that Python's
# module-attribute lookup falls through to ``__getattr__`` on first
# access.  Once created, the view is cached in ``globals()`` so
# subsequent accesses return the same object.


def __getattr__(name: str) -> object:
    if name == "_PARSER_REGISTRY":
        from ralph.agents.catalog import (  # noqa: PLC0415  # reason: lazy import breaks catalog<->parsers cycle
            default_catalog,
        )

        state_parsers: Mapping[str, _ParserRegistryEntry] = cast(
            "Mapping[str, _ParserRegistryEntry]",
            default_catalog()._state.parsers,
        )
        parser_view: Mapping[str, _ParserRegistryEntry] = types.MappingProxyType(state_parsers)
        globals()["_PARSER_REGISTRY"] = parser_view  # type: ignore[misc]  # reason: autogenerated code has no type support, see docs/agents/type-ignore-policy.md#autogenerated-code
        return parser_view
    if name == "_CUSTOM_COMMAND_REGISTRY":
        from ralph.agents.catalog import (  # noqa: PLC0415  # reason: lazy import breaks catalog<->parsers cycle
            default_catalog,
        )

        state_commands: Mapping[str, _ParserRegistryEntry] = cast(
            "Mapping[str, _ParserRegistryEntry]",
            default_catalog()._state.commands,
        )
        command_view: Mapping[str, _ParserRegistryEntry] = types.MappingProxyType(state_commands)
        globals()["_CUSTOM_COMMAND_REGISTRY"] = command_view  # type: ignore[misc]  # reason: autogenerated code has no type support, see docs/agents/type-ignore-policy.md#autogenerated-code
        return command_view
    msg = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(msg)


def _view(name: str) -> Mapping[str, _ParserRegistryEntry]:
    """Module-attribute lookup that triggers ``__getattr__`` for lazy views.

    Used by internal functions (``get_parser``, ``resolve_parser_key``)
    that need to read the legacy module-level views at call time without
    forcing eager module-level definitions that would create a circular
    import with ``ralph.agents.catalog``.
    """
    value: Mapping[str, _ParserRegistryEntry] = getattr(sys.modules[__name__], name)
    return value


def resolve_parser_key(
    command: str,
    json_parser: JsonParserType,
    transport: AgentTransport,
) -> str:
    """Resolve the parser-type key for an agent configuration.

    The resolution order matches the runtime lookup path:

    1. Agents registered via ``register_agent_support()`` are keyed by their
       command name.  When the command name is present in ``_PARSER_REGISTRY``
       as a bundled entry and the registered transport matches ``transport``,
       that command name is the key.  This lets custom interactive agents
       override the built-in ``claude_interactive`` parser.
    2. Built-in interactive Claude still falls back to the
       ``claude_interactive`` parser when no registered entry matched.
    3. When ``json_parser`` is ``JsonParserType.GENERIC`` and a built-in
       parser is registered under the agent's command name, that command name
       is the key.
    4. Otherwise fall back to ``str(json_parser)``.

    Args:
        command: The agent's configured command string (e.g. ``"claude"``).
        json_parser: The parser type token from the agent configuration.
        transport: Optional transport enum; ``CLAUDE_INTERACTIVE`` is special-cased.

    Returns:
        A parser-type key suitable for :func:`get_parser`.
    """
    command_lower = command.lower() if command else ""
    custom_entry = _view("_CUSTOM_COMMAND_REGISTRY").get(command_lower)
    from ralph.agents.catalog import (  # noqa: PLC0415  # reason: lazy import breaks catalog<->parsers cycle
        _ParserRegistryEntry,
    )
    if isinstance(custom_entry, _ParserRegistryEntry) and custom_entry.transport == transport:
        return command_lower
    if transport == AgentTransport.CLAUDE_INTERACTIVE:
        return "claude_interactive"
    command_name = command.split(maxsplit=1)[0].lower() if command else ""
    parser_registry = _view("_PARSER_REGISTRY")
    if command_name and command_name in parser_registry and json_parser == JsonParserType.GENERIC:
        return command_name
    return str(json_parser)


def get_parser(parser_type: str) -> AgentParser:
    """Get parser instance by type name or by a registered custom command.

    Args:
        parser_type: Parser type name (claude, codex, gemini, opencode, generic)
            or the full executable command of a custom-registered agent.

    Returns:
        Parser instance implementing AgentParser protocol.

    Raises:
        ValueError: If parser type is unknown.
    """
    parser_cls = _view("_PARSER_REGISTRY").get(parser_type.lower())
    if parser_cls is not None:
        return parser_cls()
    custom_entry = _view("_CUSTOM_COMMAND_REGISTRY").get(parser_type.lower())
    from ralph.agents.catalog import (  # noqa: PLC0415  # reason: lazy import breaks catalog<->parsers cycle
        _ParserRegistryEntry,
    )
    if isinstance(custom_entry, _ParserRegistryEntry):
        return custom_entry.parser_factory()
    msg = f"Unknown parser type: {parser_type}"
    raise ValueError(msg)
