#![deny(unsafe_code)]
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use ralph_gui::commands::{
    config, run_management, session, session_launch, session_prompt, worktree,
};
use ralph_gui::state::new_shared_state;
use tauri_specta::collect_commands;

fn main() {
    // Build tauri-specta command registry for type-safe TypeScript bindings
    let builder = tauri_specta::Builder::<tauri::Wry>::new().commands(collect_commands![
        // Session commands
        session::get_sessions,
        session::create_session,
        session::get_session_detail,
        // Worktree commands
        worktree::list_worktrees,
        worktree::create_worktree,
        worktree::switch_context,
        // Config commands
        config::get_global_config,
        config::get_project_config,
        config::get_effective_config,
        config::save_global_config,
        config::save_project_config,
        config::get_raw_global_config_toml,
        config::get_raw_project_config_toml,
        config::list_agent_profiles,
        config::get_ai_api_key,
        config::save_ai_api_key,
        config::validate_config_toml,
        // Run management commands
        run_management::get_run_status,
        run_management::get_run_detail,
        run_management::get_run_logs,
        run_management::notify_run_status_change,
        // Session prompt commands
        session_prompt::read_prompt_file,
        session_prompt::save_prompt_file,
        session_prompt::review_prompt_with_ai,
        // Session launch commands
        session_launch::launch_ralph_session,
        session_launch::resume_ralph_session,
    ]);

    // Export additional types needed by the frontend
    let builder = builder
        .typ::<ralph_gui::commands::config::ConfigView>()
        .typ::<ralph_gui::commands::config::AgentProfile>()
        .typ::<ralph_gui::commands::run_management::RunStatus>()
        .typ::<ralph_gui::commands::run_management::RunDetail>()
        .typ::<ralph_gui::commands::session::SessionSummary>()
        .typ::<ralph_gui::commands::session::CreateSessionRequest>()
        .typ::<ralph_gui::commands::session_launch::LaunchSessionArgs>()
        .typ::<ralph_gui::commands::session_prompt::PromptReviewResult>()
        .typ::<ralph_gui::commands::worktree::WorktreeInfo>()
        .typ::<ralph_gui::commands::worktree::CreateWorktreeResult>();

    // Export TypeScript bindings in debug builds for frontend type safety
    #[cfg(debug_assertions)]
    {
        let output_path = std::path::PathBuf::from("ui/src/app/types/generated.ts");

        builder
            .export(
                specta_typescript::Typescript::default()
                    .header("// Auto-Generated - DO NOT EDIT\n// Generated by tauri-specta from Rust commands in ralph-gui/src/commands/\n\n"),
                &output_path,
            )
            .expect("Failed to export TypeScript bindings");
    }

    tauri::Builder::default()
        .plugin(tauri_plugin_notification::init())
        .manage(new_shared_state())
        .invoke_handler(builder.invoke_handler())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
