"""Instance-owned injectable registry for agent support registrations.

The :class:`AgentCatalog` is instance-owned. Tests should construct a fresh
``AgentCatalog`` per test rather than mutating module-level state.

AgentCatalog is the single source of truth for all agent registration
state (parsers, custom-command registry, strategy dispatch). The
public legacy module-level dicts (``_PARSER_REGISTRY``,
``_CUSTOM_COMMAND_REGISTRY``, ``_STRATEGY_DISPATCH``) are
``MappingProxyType`` snapshots of the default catalog's state for
backward compatibility; new code should use the catalog directly.
"""

# ``from __future__ import annotations`` is intentionally NOT used here:
# the dataclass field annotations reference ``_ParserRegistryEntry`` (a
# class defined later in this module) and mypy's forward-reference
# resolver is sensitive to the ``from __future__ import annotations``
# scope.  Keeping the annotations as runtime expressions lets mypy
# evaluate them at class-definition time and gives a precise dict type
# to ``default_catalog()._state.parsers`` / ``.commands``.

from collections.abc import Callable, Iterator, Mapping
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypeVar

from ralph.agents._contracts import StrategyFactory
from ralph.agents.execution_state._factory import _make_agy_strategy
from ralph.agents.execution_state.claude_execution_strategy import ClaudeExecutionStrategy
from ralph.agents.execution_state.claude_interactive_execution_strategy import (
    ClaudeInteractiveExecutionStrategy,
)
from ralph.agents.execution_state.generic_execution_strategy import GenericExecutionStrategy
from ralph.agents.execution_state.opencode_execution_strategy import OpenCodeExecutionStrategy
from ralph.agents.parsers.agy import AgyParser
from ralph.agents.parsers.claude import ClaudeParser
from ralph.agents.parsers.claude_interactive import ClaudeInteractiveParser
from ralph.agents.parsers.codex import CodexParser
from ralph.agents.parsers.gemini import GeminiParser
from ralph.agents.parsers.generic import GenericParser
from ralph.agents.parsers.opencode import OpenCodeParser
from ralph.agents.parsers.pi import PiParser
from ralph.agents.support import AgentSupport
from ralph.config.agent_config import AgentConfig
from ralph.config.enums import AgentTransport

if TYPE_CHECKING:
    from ralph.agents.execution_state._base import BaseExecutionStrategy
    from ralph.agents.parsers.base import AgentParser

__all__ = [
    "AgentCatalog",
    "_CatalogBackedMapping",
    "_ParserRegistryEntry",
    "_reset_default_catalog",
    "default_catalog",
]


K = TypeVar("K")
V = TypeVar("V")


@dataclass
class _ParserRegistryEntry:
    """Parser factory bundled with the strategy factory registered alongside it.

    Instances are callable so they can be stored directly in the parser
    registry without changing that dict's public shape.  The bundled
    ``strategy_factory`` lets runtime resolution select the correct
    strategy for a specific agent command, not just its transport.
    """

    parser_factory: Callable[[], "AgentParser"]
    strategy_factory: "StrategyFactory"
    transport: "AgentTransport"

    def __call__(self) -> "AgentParser":
        return self.parser_factory()


class _CatalogBackedMapping(Mapping[K, V]):
    """Read-only mapping that delegates to a live catalog field on each access.

    Allows module-level views to stay in lockstep with the catalog state
    without making the view a snapshot of a fixed dict.  Mutations to the
    backing field are visible immediately through the view, and writes
    (setitem / delitem) are rejected with ``TypeError``.
    """

    __slots__ = ("_getter",)

    def __init__(self, getter: Callable[[], Mapping[K, V]]) -> None:
        self._getter = getter

    def __getitem__(self, key: K) -> V:
        return self._getter()[key]

    def __len__(self) -> int:
        return len(self._getter())

    def __iter__(self) -> Iterator[K]:
        return iter(self._getter())

    def __contains__(self, key: object) -> bool:
        return key in self._getter()

    def __repr__(self) -> str:
        return f"_CatalogBackedMapping({self._getter()!r})"

    def get(self, key: K, default: V | None = None) -> V | None:  # type: ignore[override]  # reason: autogenerated code has no type support, see docs/agents/type-ignore-policy.md#autogenerated-code
        result: V | None = self._getter().get(key, default)
        return result

    def __setitem__(self, key: K, value: V) -> None:
        msg = f"catalog-backed mapping does not support item assignment ({key!r})"
        raise TypeError(msg)

    def __delitem__(self, key: K) -> None:
        msg = f"catalog-backed mapping does not support item deletion ({key!r})"
        raise TypeError(msg)


# ---------------------------------------------------------------------------
# Default seed tables
#
# The default AgentCatalog is seeded with these built-in parser types and
# strategy factories.  New ``AgentCatalog()`` instances are NOT seeded;
# only ``default_catalog()`` (the singleton used by ``AgentRegistry()``)
# is seeded on first access.  This keeps the construction cost of fresh
# test catalogs at zero and avoids surprising callers with global state
# in a constructor that is documented as a clean instance.
# ---------------------------------------------------------------------------

_DEFAULT_BUILTIN_PARSER_TYPES: dict[
    str, tuple[type["AgentParser"], "AgentTransport", "StrategyFactory"]
] = {
    "agy": (AgyParser, AgentTransport.AGY, _make_agy_strategy),
    "claude": (ClaudeParser, AgentTransport.CLAUDE, ClaudeExecutionStrategy),
    "claude_interactive": (
        ClaudeInteractiveParser,
        AgentTransport.CLAUDE_INTERACTIVE,
        ClaudeInteractiveExecutionStrategy,
    ),
    "codex": (CodexParser, AgentTransport.CODEX, GenericExecutionStrategy),
    "gemini": (GeminiParser, AgentTransport.GENERIC, GenericExecutionStrategy),
    "opencode": (OpenCodeParser, AgentTransport.OPENCODE, GenericExecutionStrategy),
    "pi": (PiParser, AgentTransport.PI, GenericExecutionStrategy),
    "generic": (GenericParser, AgentTransport.GENERIC, GenericExecutionStrategy),
}


@dataclass
class _AgentCatalogState:
    """Internal mutable state owned by :class:`AgentCatalog`.

    AgentCatalog is the single source of truth for this state.  The
    legacy module-level views read from ``default_catalog()._state``
    so they are always in lockstep with the catalog.
    """

    parsers: dict[str, "type[AgentParser] | _ParserRegistryEntry"] = field(default_factory=dict)
    commands: dict[str, "Callable[[], AgentParser] | _ParserRegistryEntry"] = field(
        default_factory=dict
    )
    strategies: dict[AgentTransport, StrategyFactory] = field(default_factory=dict)


def _default_strategy_factories() -> dict[AgentTransport, StrategyFactory]:
    """Return the transport-derived default strategy factories.

    Mirrors the historical ``_DEFAULT_STRATEGY_BY_TRANSPORT`` table
    (in :mod:`ralph.agents.registration`) which is the canonical
    greppable source of truth.  Used by
    :meth:`AgentCatalog._default_strategy_for_transport` and by the
    default-catalog seeding logic.
    """
    return {
        AgentTransport.OPENCODE: OpenCodeExecutionStrategy,
        AgentTransport.CLAUDE: ClaudeExecutionStrategy,
        AgentTransport.CLAUDE_INTERACTIVE: ClaudeInteractiveExecutionStrategy,
        AgentTransport.AGY: _make_agy_strategy,
        AgentTransport.CODEX: GenericExecutionStrategy,
        AgentTransport.NANOCODER: GenericExecutionStrategy,
        AgentTransport.PI: GenericExecutionStrategy,
        AgentTransport.GENERIC: GenericExecutionStrategy,
    }


@dataclass
class AgentCatalog:
    """Single injectable agent registry.

    Manages registrations through :class:`AgentSupport` objects.  The
    legacy module-level ``_PARSER_REGISTRY``, ``_CUSTOM_COMMAND_REGISTRY``,
    and ``_STRATEGY_DISPATCH`` views are :class:`types.MappingProxyType`
    snapshots of ``default_catalog()._state`` for backward compatibility.
    """

    _entries: dict[str, "AgentSupport"] = field(default_factory=dict)
    _by_command: dict[str, "AgentSupport"] = field(default_factory=dict)
    _state: _AgentCatalogState = field(default_factory=_AgentCatalogState)

    def _default_strategy_for_transport(
        self, transport: AgentTransport
    ) -> "StrategyFactory":
        """Return the transport-derived default strategy factory for ``transport``.

        Looks up the agent's canonical default strategy table.  Raises
        ``ValueError`` if no default is registered.
        """
        factory = self._DEFAULT_STRATEGIES.get(transport)
        if factory is None:
            msg = f"No default strategy registered for transport {transport!r}"
            raise ValueError(msg)
        return factory

    @property
    def _DEFAULT_STRATEGIES(self) -> dict[AgentTransport, "StrategyFactory"]:  # noqa: N802  # reason: historical public API name preserved for backward compat
        """Return the transport-derived default strategy factories.

        Mirrors the historical ``_DEFAULT_STRATEGY_BY_TRANSPORT`` table.
        """
        return _default_strategy_factories()

    def add(self, support: "AgentSupport") -> None:
        """Register an agent support entry.

        Raises ValueError if the name or command is already registered,
        or if the name matches a reserved built-in parser key.
        """
        name_lower = support._name_lower
        if name_lower in self._entries:
            msg = f"Agent {support.name!r} is already registered"
            raise ValueError(msg)

        if self._is_built_in_parser_key(name_lower) and not support.is_builtin:
            msg = f"Cannot register agent with reserved built-in parser name: {support.name}"
            raise ValueError(msg)

        cmd_lower = support.cmd.lower()
        if cmd_lower in self._by_command:
            existing = self._by_command[cmd_lower]
            msg = f"Command {support.cmd!r} is already registered for agent {existing.name!r}"
            raise ValueError(msg)

        self._entries[name_lower] = support
        self._by_command[cmd_lower] = support
        self._write_through(support, name_lower, cmd_lower)

    @staticmethod
    def _is_built_in_parser_key(key: str) -> bool:
        """Return True when ``key`` maps to a built-in parser class.

        Checks both the built-in agent name set (from
        :func:`ralph.agents.builtin.builtin_supports`) and the legacy
        class-keyed parser registry entries that the runtime resolves by
        parser key (e.g. ``stream_parsed_agent_activity``).
        """
        from ralph.agents.builtin import (  # noqa: PLC0415  # reason: lazy import breaks catalog<->builtin cycle
            builtin_supports,
        )

        builtin_names = {s.name.lower() for s in builtin_supports()}
        if key in builtin_names:
            return True

        existing = default_catalog()._state.parsers.get(key)
        return existing is not None and not isinstance(existing, _ParserRegistryEntry)

    def _write_through(self, support: "AgentSupport", name_lower: str, cmd_lower: str) -> None:
        """Populate the catalog state for backward compat.

        Only overwrites ``self._state.parsers`` and ``self._state.commands``
        when the existing slot is not a built-in parser class, so that seeding the
        default catalog with the six built-in agents does not silently replace the
        ``ClaudeParser`` / ``ClaudeInteractiveParser`` / ``CodexParser`` / etc.
        classes that downstream callers (e.g. ``stream_parsed_agent_activity``)
        resolve by parser key. Custom agents still write through normally.

        Only overwrites ``self._state.strategies`` when the transport does not yet
        have an entry, preserving built-in dispatch entries so custom-agent
        registrations do not corrupt global transport-level strategy lookups.
        """
        entry = _ParserRegistryEntry(
            support.parser_factory,
            support.strategy_factory,
            support.spec.transport,
        )
        existing_parser = self._state.parsers.get(name_lower)
        if existing_parser is None or isinstance(existing_parser, _ParserRegistryEntry):
            self._state.parsers[name_lower] = entry
        existing_custom = self._state.commands.get(cmd_lower)
        if existing_custom is None or isinstance(existing_custom, _ParserRegistryEntry):
            self._state.commands[cmd_lower] = entry
        if support.spec.transport not in self._state.strategies:
            self._state.strategies[support.spec.transport] = support.strategy_factory

    def remove(self, name: str) -> None:
        """Remove an agent registration by name.

        Reverses the compatibility writes made by ``add()``: removes the parser
        entry from ``self._state.parsers``, removes the command entry from
        ``self._state.commands``, and removes the transport strategy entry
        from ``self._state.strategies`` only when the stored factory matches this
        registration's strategy factory (preserving built-in transport fallbacks
        for entries that existed before the removed registration).
        """
        name_lower = name.lower()
        support = self._entries.pop(name_lower, None)
        if support is not None:
            cmd_lower = support.cmd.lower()
            self._by_command.pop(cmd_lower, None)
            self._state.parsers.pop(name_lower, None)
            self._state.commands.pop(cmd_lower, None)
            if self._state.strategies.get(support.spec.transport) is support.strategy_factory:
                self._state.strategies.pop(support.spec.transport, None)

    def replace_builtin(self, name: str, support: AgentSupport) -> None:
        """Replace an existing built-in entry with a new built-in entry.

        Used by :meth:`AgentRegistry.register` to install a configured
        ``[agents.<name>]`` override on top of a built-in so the public
        catalog surface stays in lockstep with ``registry.get(<name>)``.

        The replacement support must carry ``is_builtin=True`` so a
        subsequent override can replace it as well.  The transport's
        parser factory and strategy factory are intentionally
        preserved (the override cannot change them — those are
        structural to the transport, not user preference), so the
        override only changes the per-instance fields (cmd, flags,
        session flag).

        Both ``_entries`` (name-keyed) and ``_by_command`` (cmd-keyed)
        are updated.  ``_state.parsers`` and ``_state.commands`` are
        also rewritten through :meth:`_write_through` so downstream
        callers that resolve parsers / strategies by name or by cmd
        continue to see the correct entry.

        Raises:
            ValueError: If ``support.is_builtin`` is False, if no entry
                exists under ``name``, or if the existing entry is not
                a built-in (i.e. user cannot replace a non-built-in
                registration through this path).
        """
        if not support.is_builtin:
            msg = (
                f"Replacement support must have is_builtin=True: {name!r}"
            )
            raise ValueError(msg)

        name_lower = name.lower()
        existing = self._entries.get(name_lower)
        if existing is None:
            msg = f"Cannot replace non-existent catalog entry: {name!r}"
            raise ValueError(msg)
        if not existing.is_builtin:
            msg = (
                f"Cannot replace non-built-in catalog entry through "
                f"replace_builtin: {name!r}"
            )
            raise ValueError(msg)

        old_cmd_lower = existing.cmd.lower()
        new_cmd_lower = support.cmd.lower()

        # Tear down the existing built-in's index entries so the new
        # support fully replaces them.  Strategy factories and the
        # seeded parser CLASS under ``_state.parsers[name_lower]`` are
        # intentionally left in place (the override cannot change the
        # transport's structural parser / strategy factories; see
        # ``AgentRegistry.register`` for the override synthesis path).
        self._entries.pop(name_lower, None)
        if old_cmd_lower != new_cmd_lower:
            self._by_command.pop(old_cmd_lower, None)
        self._state.commands.pop(old_cmd_lower, None)

        # Install the new built-in override.
        self._entries[name_lower] = support
        self._by_command[new_cmd_lower] = support
        self._write_through(support, name_lower, new_cmd_lower)

    def get(self, name_or_command: str) -> "AgentSupport | None":
        """Look up by agent name first, then by command, then via dynamic alias resolver.

        Dynamic aliases (``pi/<model>``, ``opencode/<model>``, ``nanocoder/<provider>/<model>``,
        ``agy/<model>``, ``claude-headless/<model>``, ``claude/<model>``, ``ccs/<alias>``) are
        resolved by ``ralph.agents.registry._resolve_dynamic_agent`` so the public catalog
        surface stays in lockstep with :meth:`AgentRegistry.get`.  The synthesized support
        inherits the base built-in's parser factory, strategy factory, and spec, and overrides
        the ``AgentConfig`` with the resolver's per-alias model-flag / cmd / session-flag
        overrides.
        """
        key = name_or_command.lower()
        support = self._entries.get(key)
        if support is not None:
            return support
        support = self._by_command.get(key)
        if support is not None:
            return support
        return _resolve_dynamic_support(self, name_or_command)

    def get_parser(self, name_or_command: str) -> "AgentParser":
        """Return a fresh parser instance for the given name or command."""
        support = self.get(name_or_command)
        if support is None:
            msg = f"Unknown agent: {name_or_command}"
            raise ValueError(msg)
        return support.parser_factory()

    def get_strategy(
        self,
        transport: AgentTransport,
        command: str | None = None,
    ) -> "BaseExecutionStrategy":
        """Return a strategy instance by transport, optionally preferring a command match.

        Args:
            transport: The transport to look up.
            command: Optional command string. When provided and a matching
                registration exists, that registration's strategy factory is used.
                Otherwise falls back to the first entry with matching transport.

        Returns:
            A BaseExecutionStrategy instance.

        Raises:
            ValueError: If no matching strategy is found.
        """
        if command is not None:
            cmd_lower = command.lower()
            match = self._by_command.get(cmd_lower)
            if match is not None:
                return match.strategy_factory(label_scope=None, registry=None)

        for support in self._entries.values():
            if support.spec.transport == transport:
                return support.strategy_factory(label_scope=None, registry=None)

        msg = f"No strategy found for transport {transport!r}"
        raise ValueError(msg)

    def list_agents(self) -> tuple[str, ...]:
        """Return sorted tuple of registered agent names."""
        return tuple(sorted(self._entries.keys()))

    def by_transport(self, transport: AgentTransport) -> tuple["AgentSupport", ...]:
        """Return all supports matching the given transport."""
        return tuple(s for s in self._entries.values() if s.spec.transport == transport)


def _seed_default_catalog(catalog: AgentCatalog) -> None:
    """Populate the default catalog with the 7 built-in supports and 8 default strategies.

    Idempotent: calling on a catalog that is already seeded is a no-op.

    Seeding populates BOTH the parser-type-keyed ``_state.parsers`` dict
    (for runtime ``get_parser(parser_type)`` lookups by parser type key,
    e.g. ``claude`` / ``claude_interactive`` / ``codex`` / ``gemini`` /
    ``opencode`` / ``pi`` / ``generic``) AND the agent-name-keyed
    ``_entries`` / ``_by_command`` dicts (for catalog API lookups by
    agent name, e.g. ``claude`` / ``claude-headless`` / ``codex`` /
    ``opencode`` / ``nanocoder`` / ``agy`` / ``pi``).  This makes
    :meth:`AgentCatalog.get` / :meth:`AgentCatalog.get_parser` /
    :meth:`AgentCatalog.get_strategy` resolve built-in names through
    the same public API that custom registrations use.

    Parser factories are stored as bare callables (NOT
    ``_ParserRegistryEntry`` instances) so
    :meth:`AgentCatalog._is_built_in_parser_key` can distinguish
    built-ins from custom registrations and so
    :meth:`AgentCatalog._write_through` preserves them when a custom
    agent tries to register a name that collides with a built-in parser
    key.  The bare factories are also callable so
    ``_PARSER_REGISTRY[name]()`` (the runtime parser lookup) works
    directly on the seeded value.
    """
    if catalog._state.parsers:
        return
    from ralph.agents.builtin import (  # noqa: PLC0415  # reason: lazy import breaks catalog<->builtin cycle
        builtin_supports,
    )
    for name, (factory, _transport, _strategy) in _DEFAULT_BUILTIN_PARSER_TYPES.items():
        catalog._state.parsers[name] = factory
    for support in builtin_supports():
        name_lower = support.name.lower()
        cmd_lower = support.cmd.lower()
        catalog._entries[name_lower] = support
        catalog._by_command[cmd_lower] = support
        catalog._state.commands[cmd_lower] = support.parser_factory
    catalog._state.strategies.update(catalog._DEFAULT_STRATEGIES)


_catalog_holder: list[AgentCatalog] = []


def default_catalog() -> AgentCatalog:
    """Return the singleton default catalog, seeding it on first access."""
    if not _catalog_holder:
        catalog = AgentCatalog()
        _seed_default_catalog(catalog)
        _catalog_holder.append(catalog)
    return _catalog_holder[0]


def _reset_default_catalog(catalog: AgentCatalog) -> None:
    _catalog_holder.clear()
    _catalog_holder.append(catalog)


def _resolve_dynamic_support(
    catalog: AgentCatalog, name_or_command: str
) -> "AgentSupport | None":
    """Resolve a documented dynamic alias to a synthesized :class:`AgentSupport`.

    Delegates to ``ralph.agents.registry._resolve_dynamic_agent`` (lazy import to
    break the ``catalog -> builtin -> registry -> catalog`` import cycle) and, on
    success, clones the underlying built-in :class:`AgentSupport` with the resolver's
    ``AgentConfig`` overrides applied.  The synthesized support inherits the base
    built-in's parser factory, strategy factory, and spec so ``catalog.get_parser``,
    ``catalog.get_strategy``, and ``build_command`` continue to work end-to-end.

    The base config is looked up via the catalog itself
    (``catalog._entries.get(<name>).config``) so a configured
    ``[agents.<name>]`` override installed through
    :meth:`AgentCatalog.replace_builtin` propagates to dynamic alias
    resolution end-to-end.  Falls back to the built-in when the alias
    base name has no catalog entry (e.g. for ``ccs/<alias>``).

    The base built-in is identified by ``config.transport`` (a unique
    property of each built-in) rather than by ``config.cmd`` lookup in
    ``catalog._by_command``.  The cmd-based lookup is unreliable for
    dynamic aliases whose synthesized ``AgentConfig.cmd`` is a multi-word
    string (e.g. ``"ccs mm"`` for ``ccs/mm``) that is NOT registered as
    a built-in command key (built-ins only register their canonical
    single-token command).  Each built-in has a unique transport, so
    iterating ``catalog._entries.values()`` and matching on transport
    finds the right base support regardless of whether the synthesized
    cmd is a single token, a multi-word shell command, or an absolute
    path.  Falls back to the ``_by_command`` lookup only when no
    transport-matched entry exists (defensive — should not happen for
    a documented alias backed by a built-in transport).

    Returns ``None`` when the alias does not match any documented pattern or when
    the resolved ``AgentConfig`` is not backed by a registered built-in (which
    would indicate a resolver bug rather than a caller error).
    """
    from ralph.agents.registry import (  # noqa: PLC0415  # reason: lazy import breaks catalog<->registry cycle
        _resolve_dynamic_agent,
    )
    from ralph.config.ccs_config import (  # noqa: PLC0415  # reason: same lazy-import rationale
        CcsConfig,
    )

    def _catalog_base_lookup(agent_name: str) -> AgentConfig | None:
        entry = catalog._entries.get(agent_name.lower())
        if entry is not None:
            return entry.config
        return None

    config = _resolve_dynamic_agent(
        name_or_command,
        CcsConfig(),
        base_lookup=_catalog_base_lookup,
    )
    if config is None:
        return None

    base: AgentSupport | None = None
    for entry in catalog._entries.values():
        if entry.spec.transport == config.transport:
            base = entry
            break
    if base is None:
        base = catalog._by_command.get(config.cmd.lower())
    if base is None:
        return None

    return AgentSupport(
        name=name_or_command.lower(),
        spec=base.spec,
        parser_factory=base.parser_factory,
        strategy_factory=base.strategy_factory,
        config=config,
        is_builtin=base.is_builtin,
        no_default_session_flag=base.no_default_session_flag,
    )
