// Auto-Generated - DO NOT EDIT
// Generated by tauri-specta from Rust commands in ralph-gui/src/commands/
// This file is regenerated during debug builds. Run `cargo build -p ralph-gui` to regenerate.

// Placeholder types - will be overwritten by tauri-specta during build
// These are here to prevent TypeScript errors before the first build

export type RunStatusString =
  | 'pending'
  | 'running'
  | 'paused'
  | 'interrupted'
  | 'completed'
  | 'failed';

export interface SessionSummary {
  run_id: string;
  status: RunStatusString;
  repo_path: string;
  worktree_path: string | null;
  created_at: string;
  description: string;
  developer_agent: string;
  reviewer_agent: string;
  phase: string;
  is_degraded?: boolean;
}

export interface CreateSessionRequest {
  repo_path: string;
  worktree_path: string | null;
  prompt_path: string;
  developer_iterations: number;
  reviewer_passes: number;
  developer_agent?: string;
  reviewer_agent?: string;
}

export interface WorktreeInfo {
  path: string;
  branch: string;
  name: string;
  has_active_run: boolean;
  is_main: boolean;
}

export interface CreateWorktreeResult {
  worktree: WorktreeInfo;
}

export interface ConfigView {
  verbosity: number;
  developer_iters: number;
  reviewer_reviews: number;
  checkpoint_enabled: boolean;
  isolation_mode: boolean;
  interactive: boolean;
  review_depth: string;
  max_dev_continuations: number;
  // Retry and Fallback settings
  max_retries?: number;
  max_same_agent_retries?: number;
  retry_delay_ms?: number;
  backoff_multiplier?: number;
  max_backoff_ms?: number;
  max_fallback_cycles?: number;
  // Git identity settings
  git_user_name?: string;
  git_user_email?: string;
}

export type RunStatus =
  | 'Running'
  | 'Paused'
  | 'Completed'
  | 'Failed'
  | 'NotStarted';

export interface RunStatusSummary {
  status: RunStatus;
  run_id: string | null;
  current_phase: string | null;
  last_checkpoint: string | null;
}

export interface RunDetail {
  run_id: string;
  status: RunStatus;
  current_phase: string;
  last_checkpoint: string | null;
  agent_profile: string;
  repo_path: string;
  worktree_path: string | null;
  created_at: string;
  description: string;
  iteration_count?: number;
  last_error?: string | null;
  is_degraded?: boolean;
}

export interface AgentProfile {
  name: string;
  developer_agent: string;
  reviewer_agent: string;
}

export interface PromptReviewResult {
  suggestions: string[];
  improved_prompt: string | null;
}

export interface LaunchSessionArgs {
  repo_path: string;
  worktree_path: string | null;
  prompt_path: string;
  developer_iterations: number;
  reviewer_passes: number;
  developer_agent: string | null;
  reviewer_agent: string | null;
}

// Workspace types
export interface WorkspaceEntry {
  id: string;
  repo_path: string;
  display_name: string;
  last_nav: string;
  active_run_count: number;
}

// GUI Preferences – booleans are split into sub-types to satisfy the Rust
// pedantic `struct_excessive_bools` lint (max 3 bools per struct).

/** Which run events trigger a desktop notification. */
export interface GuiNotificationTriggers {
  notifyCompletion: boolean;
  notifyFailure: boolean;
  notifyDegraded: boolean;
}

/** Notification-related preferences. */
export interface GuiNotificationSettings {
  showPhaseNotifications: boolean;
  desktopNotifications: boolean;
  notifyPhaseChange: boolean;
  triggers: GuiNotificationTriggers;
}

/** Session and log behaviour preferences. */
export interface GuiSessionSettings {
  logAutoscroll: boolean;
  confirmCancel: boolean;
  restoreWorkspaces: boolean;
}

export interface GuiPreferences {
  theme: string;
  accentColor: string;
  sidebarWidth: number;
  fontSize: number;
  monospaceFont: string;
  runPollIntervalMs: number;
  logBufferSize: number;
  defaultView: string;
  checkUpdates: boolean;
  session: GuiSessionSettings;
  notifications: GuiNotificationSettings;
}

// Run log streaming
export interface RunLogLine {
  run_id: string;
  line: string;
  sequence: number;
}

// Run diff / changes
export interface FileDiff {
  path: string;
  additions: number;
  deletions: number;
  diff_text: string;
}

export interface RunChanges {
  files: FileDiff[];
  total_additions: number;
  total_deletions: number;
  iteration: number | null;
}

// Agent tools
export interface AgentToolInfo {
  name: string;
  binary: string;
  installed: boolean;
  version: string | null;
  auth_status: string;
  health: string;
}

// Prompt templates
export interface TemplateInfo {
  name: string;
  description: string;
  content: string;
  tags: string[];
}
