// Auto-Generated - DO NOT EDIT
// Generated by tauri-specta from Rust commands in ralph-gui/src/commands/
// This file is regenerated during debug builds. Run `cargo build -p ralph-gui` to regenerate.

// Placeholder types - will be overwritten by tauri-specta during build
// These are here to prevent TypeScript errors before the first build

export type RunStatusString =
  | 'pending'
  | 'running'
  | 'paused'
  | 'interrupted'
  | 'completed'
  | 'failed';

export interface SessionSummary {
  run_id: string;
  status: RunStatusString;
  repo_path: string;
  worktree_path: string | null;
  created_at: string;
  description: string;
  developer_agent: string;
  reviewer_agent: string;
  phase: string;
  is_degraded?: boolean;
}

export interface CreateSessionRequest {
  repo_path: string;
  worktree_path: string | null;
  prompt_path: string;
  developer_iterations: number;
  reviewer_passes: number;
  developer_agent?: string;
  reviewer_agent?: string;
}

export interface WorktreeInfo {
  path: string;
  branch: string;
  name: string;
  has_active_run: boolean;
  is_main: boolean;
}

export interface CreateWorktreeResult {
  worktree: WorktreeInfo;
}

export interface ConfigView {
  verbosity: number;
  developer_iters: number;
  reviewer_reviews: number;
  checkpoint_enabled: boolean;
  isolation_mode: boolean;
  interactive: boolean;
  review_depth: string;
  max_dev_continuations: number;
}

export type RunStatus =
  | 'Running'
  | 'Paused'
  | 'Completed'
  | 'Failed'
  | 'NotStarted';

export interface RunStatusSummary {
  status: RunStatus;
  run_id: string | null;
  current_phase: string | null;
  last_checkpoint: string | null;
}

export interface RunDetail {
  run_id: string;
  status: RunStatus;
  current_phase: string;
  last_checkpoint: string | null;
  agent_profile: string;
  repo_path: string;
  worktree_path: string | null;
  created_at: string;
  description: string;
  iteration_count?: number;
  last_error?: string | null;
  is_degraded?: boolean;
}

export interface AgentProfile {
  name: string;
  developer_agent: string;
  reviewer_agent: string;
}

export interface PromptReviewResult {
  suggestions: string[];
  improved_prompt: string | null;
}

export interface LaunchSessionArgs {
  repo_path: string;
  worktree_path: string | null;
  prompt_path: string;
  developer_iterations: number;
  reviewer_passes: number;
  developer_agent: string | null;
  reviewer_agent: string | null;
}
