// TypeScript interfaces re-exported from Specta-generated types.
// The generated.ts file is auto-generated by tauri-specta during debug builds.
// Source: ralph-gui/src/commands/* Rust command definitions.

// Re-export all generated types
export * from './generated';

// Additional frontend-only types not generated by Specta

/**
 * Context for the currently active worktree/repo
 */
export interface ActiveContext {
  repo_path: string | null;
  worktree_path: string | null;
}
