"""Repo-structure audit: file size, class-per-module, private imports, bypass comments.

Single source of truth for the repository structure policy. It runs as a
``make verify`` step -- so a violation fails the gate on EVERY run, no matter who
introduced it -- and ``tests/integration/test_policy_file_rules.py`` asserts on the
same :func:`collect_violations` result.

This check previously lived ONLY in a ``subprocess_e2e``-marked test, which
``make test`` excludes, so the policy rotted silently while the gate stayed green.
Keeping it in ``_VERIFY_STEPS`` is the regression guard; do not unwire it.

The four rules (allowlists live in ``_repo_structure_allowlists``):

- files may not exceed 1000 lines
- a module may define at most one public top-level class
- tests may not import private (``_``-prefixed) names from ``ralph``
- no lint- or typecheck-suppression comments outside the allowlist (the two
  markers are assembled at runtime in ``_NOQA_MARKER`` / ``_TYPE_IGNORE_MARKER``
  rather than spelled out here, so this module does not trip its own scan)
"""

from __future__ import annotations

import io
import sys
import tokenize
from dataclasses import dataclass
from pathlib import Path

from ralph.testing._repo_structure_allowlists import (
    _LEGACY_BYPASS_COMMENT_ALLOWLIST,
    _LEGACY_LARGE_FILE_ALLOWLIST,
    _LEGACY_MULTIPLE_CLASS_ALLOWLIST,
    _LEGACY_PRIVATE_IMPORT_ALLOWLIST,
    _MAX_FILE_LINES,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
RALPH_DIR = REPO_ROOT / "ralph"
TESTS_DIR = REPO_ROOT / "tests"
_REPO_ROOT_STANDALONE_FILES: tuple[Path, ...] = (REPO_ROOT / "conftest.py",)
_SKIP_DIRS = frozenset({"__pycache__", ".venv", "tmp"})
_TYPE_IGNORE_MARKER = "# type:" + " ignore"
_NOQA_MARKER = "# no" + "qa"
_EXTERNAL_LIBRARY_SUFFIX = (
    "# reason: external library has no type support, see "
    "docs/agents/type-ignore-policy.md#external-library"
)
_AUTOGENERATED_SUFFIX = (
    "# reason: autogenerated code has no type support, see "
    "docs/agents/type-ignore-policy.md#autogenerated-code"
)


@dataclass(frozen=True)
class _Analysis:
    """Everything the four rules need from one source file, scanned once."""

    line_count: int
    top_level_classes: tuple[str, ...]
    nested_classes: tuple[tuple[int, str, str], ...]
    bypass_comments: tuple[tuple[int, str], ...]
    private_ralph_imports: tuple[tuple[str, list[str]], ...]


# Explicit memos rather than functools.cache: the decorator erases the
# signature to Any, which mypy rejects under disallow_any_expr on ralph/.
_PY_FILE_CACHE: dict[Path, tuple[Path, ...]] = {}
_SOURCE_CACHE: dict[Path, str] = {}
_ANALYSIS_CACHE: dict[Path, _Analysis] = {}


def _all_py_files(base: Path) -> tuple[Path, ...]:
    cached = _PY_FILE_CACHE.get(base)
    if cached is None:
        cached = tuple(
            sorted(
                path
                for path in base.rglob("*.py")
                if not any(part in _SKIP_DIRS for part in path.parts)
            )
        )
        _PY_FILE_CACHE[base] = cached
    return cached


def _read_path(path: Path) -> str:
    cached = _SOURCE_CACHE.get(path)
    if cached is None:
        cached = path.read_text(encoding="utf-8")
        _SOURCE_CACHE[path] = cached
    return cached


def _scan_private_imports(lines: tuple[str, ...]) -> tuple[tuple[str, list[str]], ...]:
    results: list[tuple[str, list[str]]] = []
    for raw_line in lines:
        stripped = raw_line.strip()
        if not stripped.startswith("from ralph") or " import " not in stripped:
            continue
        module_part, imported_part = stripped.split(" import ", 1)
        module = module_part[len("from ") :].strip()
        if not module.startswith("ralph"):
            continue
        private_names = []
        for item in imported_part.split(","):
            name = item.split("#", 1)[0].strip()
            if not name:
                continue
            if " as " in name:
                name = name.split(" as ", 1)[0].strip()
            if name.startswith("_"):
                private_names.append(name)
        if private_names:
            results.append((module, private_names))
    return tuple(results)


def _record_bypass_comment(
    *,
    tok_string: str,
    start_row: int,
    lines: tuple[str, ...],
    bypass_comments: list[tuple[int, str]],
) -> None:
    if _TYPE_IGNORE_MARKER not in tok_string and _NOQA_MARKER not in tok_string:
        return
    line = lines[start_row - 1].rstrip() if start_row - 1 < len(lines) else ""
    if line.endswith(_EXTERNAL_LIBRARY_SUFFIX) or line.endswith(_AUTOGENERATED_SUFFIX):
        return
    bypass_comments.append((start_row, line))


def _scan_structure(
    src: str, lines: tuple[str, ...]
) -> tuple[tuple[str, ...], tuple[tuple[int, str, str], ...], tuple[tuple[int, str], ...]]:
    top_level_classes: list[str] = []
    nested_classes: list[tuple[int, str, str]] = []
    bypass_comments: list[tuple[int, str]] = []
    indent_level = 0
    class_stack: list[tuple[str, int]] = []
    pending_class_name: str | None = None
    pending_top_level = False
    pending_nested_outer: str | None = None

    try:
        tokens = tokenize.generate_tokens(io.StringIO(src).readline)
        for tok_type, tok_string, (start_row, _), *_rest in tokens:
            if tok_type == tokenize.INDENT:
                indent_level += 1
                if pending_class_name is not None:
                    class_stack.append((pending_class_name, indent_level))
                    pending_class_name = None
                continue
            if tok_type == tokenize.DEDENT:
                indent_level = max(0, indent_level - 1)
                while class_stack and class_stack[-1][1] > indent_level:
                    class_stack.pop()
                continue
            if tok_type == tokenize.COMMENT:
                _record_bypass_comment(
                    tok_string=tok_string,
                    start_row=start_row,
                    lines=lines,
                    bypass_comments=bypass_comments,
                )
                continue
            if tok_type == tokenize.NAME and tok_string == "class":
                pending_class_name = None
                pending_top_level = indent_level == 0
                pending_nested_outer = class_stack[-1][0] if class_stack else None
                continue
            if (
                pending_top_level or pending_nested_outer is not None
            ) and tok_type == tokenize.NAME:
                if pending_top_level and not tok_string.startswith("_"):
                    top_level_classes.append(tok_string)
                if pending_nested_outer is not None and indent_level > 0:
                    nested_classes.append((start_row, pending_nested_outer, tok_string))
                pending_class_name = tok_string
                pending_top_level = False
                pending_nested_outer = None
                continue
            if (pending_top_level or pending_nested_outer is not None) and tok_type not in {
                tokenize.NL,
                tokenize.NEWLINE,
                tokenize.COMMENT,
            }:
                pending_top_level = False
                pending_nested_outer = None
    except tokenize.TokenError:
        return (), (), ()

    return tuple(top_level_classes), tuple(nested_classes), tuple(bypass_comments)


def _analysis(path: Path) -> _Analysis:
    cached = _ANALYSIS_CACHE.get(path)
    if cached is None:
        src = _read_path(path)
        lines = tuple(src.splitlines())
        top_level_classes, nested_classes, bypass_comments = _scan_structure(src, lines)
        cached = _Analysis(
            line_count=len(lines),
            top_level_classes=top_level_classes,
            nested_classes=nested_classes,
            bypass_comments=bypass_comments,
            private_ralph_imports=_scan_private_imports(lines),
        )
        _ANALYSIS_CACHE[path] = cached
    return cached


def _collect_source_violations() -> list[str]:
    violations: list[str] = []
    for base in (RALPH_DIR, TESTS_DIR):
        for path in _all_py_files(base):
            rel = str(path.relative_to(REPO_ROOT))
            data = _analysis(path)
            line_count = data.line_count
            if rel not in _LEGACY_LARGE_FILE_ALLOWLIST and line_count > _MAX_FILE_LINES:
                violations.append(f"file too large: {line_count} lines: {rel}")
            classes = list(data.top_level_classes)
            if len(classes) > 1 and rel not in _LEGACY_MULTIPLE_CLASS_ALLOWLIST:
                violations.append(f"multiple top-level classes: {rel}: {classes[:5]}")
            for module, names in data.private_ralph_imports:
                if not path.is_relative_to(TESTS_DIR):
                    continue
                key = (rel, module, tuple(names))
                if key in _LEGACY_PRIVATE_IMPORT_ALLOWLIST:
                    continue
                violations.append(f"private ralph import: {rel}: from {module} import {names}")
            for lineno, line in data.bypass_comments:
                if (rel, lineno) in _LEGACY_BYPASS_COMMENT_ALLOWLIST:
                    continue
                violations.append(f"bypass comment: {rel}:{lineno}: {line}")
            if path.is_relative_to(RALPH_DIR):
                for lineno, outer, inner in data.nested_classes:
                    violations.append(f"nested class: {rel}:{lineno}: {outer}.{inner}")
    return violations


def _collect_repo_root_violations() -> list[str]:
    violations: list[str] = []
    for path in _REPO_ROOT_STANDALONE_FILES:
        if not path.exists():
            violations.append(f"expected file not found: {path.relative_to(REPO_ROOT)}")
            continue
        rel = str(path.relative_to(REPO_ROOT))
        data = _analysis(path)
        line_count = data.line_count
        if line_count > _MAX_FILE_LINES:
            violations.append(f"repo-root file too large: {line_count} lines: {rel}")
        classes = list(data.top_level_classes)
        if len(classes) > 1:
            violations.append(f"repo-root multiple classes: {rel}: {classes}")
        for lineno, outer, inner in data.nested_classes:
            violations.append(f"repo-root nested class: {rel}:{lineno}: {outer}.{inner}")
        for lineno, line in data.bypass_comments:
            violations.append(f"repo-root bypass comment: {rel}:{lineno}: {line}")
    return violations


def collect_violations() -> list[str]:
    """Return every repo-structure policy violation (empty when the repo is clean)."""
    return _collect_source_violations() + _collect_repo_root_violations()


def main(argv: list[str] | None = None) -> int:
    """Print violations and exit non-zero when the structure policy is broken."""
    _ = argv
    violations = collect_violations()
    if violations:
        print("Repo-structure policy violations:")
        for violation in sorted(violations):
            print(f"  {violation}")
        print(f"\n{len(violations)} violation(s). See AGENTS.md 'Non-negotiables'.")
        return 1
    print(
        "Repo-structure audit: OK "
        "(file size, class-per-module, private imports, bypass comments)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
