"""Typecheck bypass audit — detects forbidden type:ignore and mypy config weakening.

Scans the codebase for:
- Blanket ``# type: ignore`` without a specific mypy error code
- ``# type: ignore[CODE]`` without a policy-compliant reason marker
- ``# type: ignore`` in test files (must be fully typed)
- Mypy config that weakens type checking: ``ignore_missing_imports``,
  ``follow_imports = silent``, ``exclude`` patterns, ``ignore_errors``

Usage:
    python -m ralph.testing.audit_typecheck_bypass [codebase_root]

Returns exit code 0 if no typecheck bypass violations found, 1 otherwise.
"""

from __future__ import annotations

import re
import sys
from configparser import ConfigParser
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Iterable

# ---------------------------------------------------------------------------
# Allowlist: known-legitimate type:ignore annotations
#
# Each entry: (file_stem, error_code)
# ---------------------------------------------------------------------------
_TYPE_IGNORE_ALLOWLIST: set[tuple[str, str]] = {
    ("commit_cleanup", "misc"),
}

# Policy-compliant reason markers (must appear on the same logical line
# as the # type: ignore annotation).
_VALID_REASON_MARKERS: tuple[str, ...] = (
    "# reason: external library has no type support, see "
    "docs/agents/type-ignore-policy.md#external-library",
    "# reason: autogenerated code has no type support, see "
    "docs/agents/type-ignore-policy.md#autogenerated-code",
)

# Files / directories to skip.
_SKIP_DIRS: frozenset[str] = frozenset({"__pycache__", ".venv", ".mypy_cache", "tmp", ".ruff_cache", ".pytest_cache", "htmlcov", "build", "dist"})

# Regex: blanket # type: ignore (no error code in brackets).
_BLANKET_TYPE_IGNORE_RE = re.compile(r"#\s*type\s*:\s*ignore\s*(?:$|[^\[#])")

# Regex: # type: ignore[CODE] with error code.
_CODE_TYPE_IGNORE_RE = re.compile(r"#\s*type\s*:\s*ignore\s*\[([^\]]+)\]")

# Mypy config keys that weaken type checking.
_WEAKENING_MYPY_KEYS: dict[str, str] = {
    "ignore_missing_imports": "ignore_missing_imports = true",
    "follow_imports": "follow_imports = silent",
    "ignore_errors": "ignore_errors = true",
}


class TypecheckBypassViolation:
    """A single typecheck bypass violation found during scanning."""

    def __init__(
        self,
        file_path: str,
        line: int,
        category: str,
        detail: str,
    ) -> None:
        self.file_path = file_path
        self.line = line
        self.category = category
        self.detail = detail

    def __str__(self) -> str:
        return f"{self.file_path}:{self.line}: [TYPECHECK-BYPASS] {self.category}: {self.detail}"


def _is_inside_triple_quoted(lines: list[str], line_index: int) -> bool:
    """Return True if *line_index* is inside a triple-quoted string literal."""
    in_triple: bool = False
    for i in range(line_index):
        stripped = lines[i].strip()
        count = stripped.count('"""') + stripped.count("'''")
        if count % 2 == 1:
            in_triple = not in_triple
    return in_triple


def _is_test_file(rel_path: str) -> bool:
    """Return True if the file is under a tests/ directory."""
    parts = Path(rel_path).parts
    return len(parts) > 0 and parts[0] == "tests"


def _check_line_for_type_ignore(
    line: str,
    rel_path: str,
    lines: list[str],
    lineno: int,
) -> list[TypecheckBypassViolation]:
    """Check a single source line for type:ignore violations."""
    violations: list[TypecheckBypassViolation] = []
    file_stem = Path(rel_path).stem

    # Skip lines inside triple-quoted strings.
    if _is_inside_triple_quoted(lines, lineno - 1):
        return violations

    if _is_test_file(rel_path):
        # Check for blanket type: ignore in test files.
        if _BLANKET_TYPE_IGNORE_RE.search(line):
            violations.append(
                TypecheckBypassViolation(
                    file_path=rel_path,
                    line=lineno,
                    category="test-blanket-type-ignore",
                    detail="blanket '# type: ignore' in test file — tests must be fully typed",
                )
            )
        # Check for coded type: ignore in test files.
        code_match = _CODE_TYPE_IGNORE_RE.search(line)
        if code_match:
            code = code_match.group(1).strip()
            violations.append(
                TypecheckBypassViolation(
                    file_path=rel_path,
                    line=lineno,
                    category="test-type-ignore",
                    detail=f"'# type: ignore[{code}]' in test file — "
                    f"tests must be fully typed",
                )
            )
    else:
        # Check for blanket type: ignore.
        if _BLANKET_TYPE_IGNORE_RE.search(line):
            violations.append(
                TypecheckBypassViolation(
                    file_path=rel_path,
                    line=lineno,
                    category="blanket-type-ignore",
                    detail="blanket '# type: ignore' without specific mypy error code",
                )
            )
            return violations

        # Check for coded type: ignore.
        code_match = _CODE_TYPE_IGNORE_RE.search(line)
        if code_match:
            code = code_match.group(1).strip()

            # Check allowlist.
            if (file_stem, code) in _TYPE_IGNORE_ALLOWLIST:
                # Verify reason marker is present.
                if not any(marker in line for marker in _VALID_REASON_MARKERS):
                    violations.append(
                        TypecheckBypassViolation(
                            file_path=rel_path,
                            line=lineno,
                            category="missing-reason",
                            detail=f"'# type: ignore[{code}]' — "
                            f"allowlisted but missing policy-compliant reason marker",
                        )
                    )
                return violations

            # Check for any code that is NOT in allowlist.
            # is_allowlisted check.
            if not any(marker in line for marker in _VALID_REASON_MARKERS):
                violations.append(
                    TypecheckBypassViolation(
                        file_path=rel_path,
                        line=lineno,
                        category="missing-reason",
                        detail=f"'# type: ignore[{code}]' — "
                        f"missing policy-compliant reason marker. "
                        f"Must use one of the approved reason suffixes.",
                    )
                )
            else:
                violations.append(
                    TypecheckBypassViolation(
                        file_path=rel_path,
                        line=lineno,
                        category="unknown-type-ignore",
                        detail=f"'# type: ignore[{code}]' — "
                        f"code {code} is not in the allowlist",
                    )
                )

    return violations


def _find_type_ignore_violations(
    lines: list[str],
    rel_path: str,
) -> list[TypecheckBypassViolation]:
    """Scan source lines for forbidden type: ignore annotations."""
    violations: list[TypecheckBypassViolation] = []
    for idx, raw_line in enumerate(lines):
        lineno = idx + 1
        if "# type:" not in raw_line and "# type :" not in raw_line:
            continue
        violations.extend(
            _check_line_for_type_ignore(raw_line, rel_path, lines, lineno)
        )
    return violations


def _check_mypy_ini(config_path: Path) -> list[TypecheckBypassViolation]:
    """Check a mypy.ini file for weakening settings using ConfigParser."""
    violations: list[TypecheckBypassViolation] = []

    if not config_path.is_file():
        return violations

    try:
        content = config_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return violations

    config = ConfigParser()
    try:
        config.read_string(content)
    except Exception:
        return violations

    rel_path = str(config_path)

    for section_name in config.sections():
        if not section_name.startswith("mypy"):
            continue

        for key, pattern in _WEAKENING_MYPY_KEYS.items():
            if config.has_option(section_name, key):
                try:
                    value = config.get(section_name, key).strip().lower()
                except Exception:
                    continue
                if key == "ignore_missing_imports" and value == "true":
                    violations.append(
                        TypecheckBypassViolation(
                            file_path=rel_path,
                            line=0,
                            category="mypy-config",
                            detail=f"[{section_name}] {pattern} — "
                            f"weakens type checking",
                        )
                    )
                elif key == "follow_imports" and value == "silent":
                    violations.append(
                        TypecheckBypassViolation(
                            file_path=rel_path,
                            line=0,
                            category="mypy-config",
                            detail=f"[{section_name}] {pattern} — "
                            f"weakens type checking",
                        )
                    )
                elif key == "ignore_errors" and value == "true":
                    violations.append(
                        TypecheckBypassViolation(
                            file_path=rel_path,
                            line=0,
                            category="mypy-config",
                            detail=f"[{section_name}] {pattern} — "
                            f"weakens type checking",
                        )
                    )

        # Check for disable_error_code — globally suppresses mypy error codes.
        if config.has_option(section_name, "disable_error_code"):
            try:
                disable_value = config.get(section_name, "disable_error_code").strip()
            except Exception:
                disable_value = "<parse error>"
            if disable_value:
                violations.append(
                    TypecheckBypassViolation(
                        file_path=rel_path,
                        line=0,
                        category="mypy-config",
                        detail=f"[{section_name}] disable_error_code = "
                        f"{disable_value} — globally suppresses mypy "
                        f"error codes, weakening enforcement",
                    )
                )

        # Check for exclude patterns.
        if config.has_option(section_name, "exclude"):
            try:
                exclude_value = config.get(section_name, "exclude").strip()
            except Exception:
                continue
            violations.append(
                TypecheckBypassViolation(
                    file_path=rel_path,
                    line=0,
                    category="mypy-config",
                    detail=f"[{section_name}] exclude = {exclude_value} — "
                    f"excludes files from type checking, weakening enforcement",
                )
            )

    return violations


def _check_pyproject_mypy(pyproject_path: Path) -> list[TypecheckBypassViolation]:
    """Check pyproject.toml for [tool.mypy] weakening settings using tomllib."""
    violations: list[TypecheckBypassViolation] = []

    if not pyproject_path.is_file():
        return violations

    try:
        import tomllib as _tomllib
        data = _tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    except (OSError, ImportError, Exception):
        return violations

    tool_mypy = data.get("tool", {}).get("mypy", {})
    if not tool_mypy:
        return violations

    rel_path = str(pyproject_path)

    for key, pattern in _WEAKENING_MYPY_KEYS.items():
        if key in tool_mypy:
            value = str(tool_mypy[key]).strip().lower()
            if key == "ignore_missing_imports" and value == "true":
                violations.append(
                    TypecheckBypassViolation(
                        file_path=rel_path,
                        line=0,
                        category="mypy-config",
                        detail=f"[tool.mypy] {pattern} — "
                        f"weakens type checking",
                    )
                )
            elif key == "follow_imports" and value == "silent":
                violations.append(
                    TypecheckBypassViolation(
                        file_path=rel_path,
                        line=0,
                        category="mypy-config",
                        detail=f"[tool.mypy] {pattern} — "
                        f"weakens type checking",
                    )
                )
            elif key == "ignore_errors" and value == "true":
                violations.append(
                    TypecheckBypassViolation(
                        file_path=rel_path,
                        line=0,
                        category="mypy-config",
                        detail=f"[tool.mypy] {pattern} — "
                        f"weakens type checking",
                    )
                )

    if "exclude" in tool_mypy:
        violations.append(
            TypecheckBypassViolation(
                file_path=rel_path,
                line=0,
                category="mypy-config",
                detail=f"[tool.mypy] exclude = {tool_mypy['exclude']} - "
                f"excludes files from type checking, weakening enforcement",
            )
        )

    # disable_error_code globally suppresses mypy error codes.
    disable_error_code = tool_mypy.get("disable_error_code")
    if disable_error_code:
        violations.append(
            TypecheckBypassViolation(
                file_path=rel_path,
                line=0,
                category="mypy-config",
                detail=f"[tool.mypy] disable_error_code = {disable_error_code} - "
                f"globally suppresses mypy error codes, weakening enforcement",
            )
        )

    # warn_unused_ignores = false weakens type checking by silencing
    # the "unused ignore" error, allowing stale type: ignore to accumulate.
    if tool_mypy.get("warn_unused_ignores") is False:
        violations.append(
            TypecheckBypassViolation(
                file_path=rel_path,
                line=0,
                category="mypy-config",
                detail="[tool.mypy] warn_unused_ignores = false - "
                "weakens type checking by silencing unused ignore warnings",
            )
        )

    # disallow_untyped_defs = false weakens type checking by allowing
    # functions without type annotations to pass silently.
    if tool_mypy.get("disallow_untyped_defs") is False:
        violations.append(
            TypecheckBypassViolation(
                file_path=rel_path,
                line=0,
                category="mypy-config",
                detail="[tool.mypy] disallow_untyped_defs = false - "
                "weakens type checking by allowing untyped function definitions",
            )
        )

    return violations


def _collect_py_files(root: Path) -> Iterable[Path]:
    """Yield all Python files under *root*, skipping excluded directories."""
    for path in root.rglob("*.py"):
        if any(part in _SKIP_DIRS for part in path.parts):
            continue
        yield path


def _find_mypy_config_files(codebase_root: Path) -> tuple[list[Path], Path | None]:
    """Find mypy config files.

    Returns (ini_configs, pyproject_path).
    """
    ini_configs: list[Path] = []
    for name in ("mypy.ini", ".mypy.ini"):
        p = codebase_root / name
        if p.is_file():
            ini_configs.append(p)
    pyproject = codebase_root / "pyproject.toml"
    return ini_configs, pyproject if pyproject.is_file() else None


def audit_codebase(codebase_root: Path) -> tuple[list[TypecheckBypassViolation], int]:
    """Audit the entire codebase for typecheck bypass violations.

    Returns (violations, files_checked).
    """
    all_violations: list[TypecheckBypassViolation] = []
    files_checked = 0

    for py_file in sorted(_collect_py_files(codebase_root)):
        files_checked += 1
        try:
            content = py_file.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue

        lines = content.splitlines()
        rel_path = str(py_file.relative_to(codebase_root))
        violations = _find_type_ignore_violations(lines, rel_path)
        all_violations.extend(violations)

    # Check mypy config files.
    ini_configs, pyproject_path = _find_mypy_config_files(codebase_root)
    for ini_path in ini_configs:
        config_violations = _check_mypy_ini(ini_path)
        all_violations.extend(config_violations)
    if pyproject_path is not None:
        pyproject_violations = _check_pyproject_mypy(pyproject_path)
        all_violations.extend(pyproject_violations)

    return all_violations, files_checked


def main(argv: list[str] | None = None) -> int:
    """Run the typecheck bypass audit and return exit code.

    Exit code 0: no violations found.
    Exit code 1: violations found.
    Exit code 2: error.
    """
    args = argv if argv is not None else sys.argv[1:]

    if args:
        codebase_root = Path(args[0])
    else:
        # Default: scan the ralph-workflow package root.
        codebase_root = Path(__file__).parent.parent.parent

    if not codebase_root.is_dir():
        print(f"Error: directory not found: {codebase_root}", file=sys.stderr)
        return 2

    print(f"Auditing typecheck bypass in: {codebase_root}")
    print()

    violations, files_checked = audit_codebase(codebase_root)

    if violations:
        print(
            f"TYPECHECK BYPASS VIOLATIONS FOUND: {len(violations)} violation(s) "
            f"in {files_checked} file(s)"
        )
        print("=" * 72)
        for v in violations:
            print(f"  {v}")
        print()
        print("These violations weaken typecheck enforcement. Fix the violation, not the audit.")
        print("Guidance: docs/agents/type-ignore-policy.md")
        return 1

    print(f"No typecheck bypass violations found in {files_checked} file(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
