"""Deterministic auto-commit for project-policy readiness changes.

Mirror of the wt-025 skill auto-commit: when the readiness preflight leaves
the project READY, the policy surfaces it wrote are committed in one
deterministic chore commit. Without it, the next run's development agent
sees the drift in its working tree and the commit-cleanup phase warns about
files it does not own.

Shares the git mechanics (scoped dirty discovery, staged-state preservation,
best-effort semantics) with the skill auto-commit through
:mod:`ralph.git.scoped_auto_commit`.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from loguru import logger

from ralph.git.commit_result import CommitCreationResult
from ralph.git.operations import stage_files
from ralph.git.scoped_auto_commit import (
    ScopedCommitResult,
    ScopedCommitStatus,
    commit_deterministic_writes,
    commit_scoped_updates,
)
from ralph.project_policy import markers

if TYPE_CHECKING:
    from collections.abc import Callable, Mapping
    from typing import Protocol

    from ralph.git.commit_result import CommitCreationResult

    class _CreateCommitFn(Protocol):
        def __call__(
            self, repo_root: Path | str, message: str, *, expected_head: str
        ) -> CommitCreationResult: ...


# The deterministic conventional-commit subject line.
POLICY_AUTO_COMMIT_SUBJECT: str = "chore(policy): sync project-policy readiness"

_POLICY_AUTO_COMMIT_HEADER: str = "Auto-generated by Ralph project-policy remediation"

_POLICY_AUTO_COMMIT_CHANGED_FILES_HEADER: str = "Changed files:"

#: Repo-relative surfaces the readiness validator and remediation agent own.
#: A trailing ``/`` means directory scope; otherwise an exact file. The
#: migration candidates are content-conditional (see ``_migrated_only``).
_POLICY_COMMIT_SCOPES: tuple[str, ...] = (
    markers.CANONICAL_DIR,
    markers.AGENTS_MD,
    markers.CLAUDE_MD,
    *markers.MIGRATION_CANDIDATE_PATHS,
)

#: The stable prefix of the migrated marker (target-independent).
_MIGRATED_MARKER_PREFIX: str = markers.MIGRATED_MARKER_TEMPLATE.split("{target}")[0]

#: Migration candidates whose commit is content-conditional. AGENTS.md and
#: CLAUDE.md are always Ralph-owned surfaces (committed unconditionally);
#: every other candidate is only committed once it carries the migrated
#: marker, so unrelated user edits are never swept into the chore commit.
_CONDITIONAL_MIGRATION_SCOPES: frozenset[str] = frozenset(markers.MIGRATION_CANDIDATE_PATHS) - {
    markers.AGENTS_MD,
    markers.CLAUDE_MD,
}


def _migrated_only(repo_root: Path) -> Callable[[str], bool]:
    """Filter: commit a migration candidate only when it carries the marker.

    Remediation adds the ``ralph-workflow-policy:migrated ->`` marker when it
    consolidates a candidate's policy content. A candidate that is dirty for
    any other reason is the user's own edit and must never be swept into the
    chore commit.
    """

    def check(path: str) -> bool:
        if path not in _CONDITIONAL_MIGRATION_SCOPES:
            return True
        try:
            content = (repo_root / path).read_text(encoding="utf-8")
        except OSError:
            return False
        return _MIGRATED_MARKER_PREFIX in content

    return check


def _build_body(dirty_paths: list[str]) -> str:
    lines = [_POLICY_AUTO_COMMIT_HEADER, "", _POLICY_AUTO_COMMIT_CHANGED_FILES_HEADER]
    lines.extend(f"- {path}" for path in dirty_paths)
    return "\n".join(lines)


def commit_policy_updates(
    repo_root: Path | str,
    create_commit_fn: _CreateCommitFn,
    *,
    stage_fn: Callable[[Path | str, list[str]], None] | None = None,
    pre_run_dirty: frozenset[str] | None = None,
) -> str | None:
    """Create the deterministic policy-readiness auto-commit.

    wt-012 contract:

    * Commits only the policy surfaces themselves (``_POLICY_COMMIT_SCOPES``)
      and the conditional migration candidates whose content carries
      the migration marker.
    * Remediation-agent authored paths (gate scripts outside the
      policy directories) are NO LONGER swept in here -- the
      remediation-author scope expansion was removed in wt-012. The
      deterministic chore commit must never ride an agent's authoring.
    * ``pre_run_dirty`` -- the paths already dirty BEFORE the policy
      pipeline ran -- is subtracted from the in-scope set so a user
      mid-edit on ``AGENTS.md`` or a policy file is not swept into
      the chore commit.

    New callers should prefer :func:`commit_policy_writes` (the
    producer-level isolation primitive) when the deterministic
    writer knows the byte-exact set of paths it just wrote. This
    legacy scope-dirty helper is retained for callers that only have
    dirty-tree visibility (and as a final safety net for any policy
    path the preflight surfaced that the producer-level pass missed).

    Returns the commit SHA on ``CREATED``, else ``None``. The explicit
    result type used internally is :class:`ScopedCommitResult`; this
    legacy signature keeps the ``str | None`` return for the existing
    call sites and tests.
    """
    if stage_fn is None:
        stage_fn = stage_files
    path_filter = _migrated_only(Path(repo_root))
    result = commit_scoped_updates(
        repo_root,
        scopes=_POLICY_COMMIT_SCOPES,
        subject=POLICY_AUTO_COMMIT_SUBJECT,
        body_builder=_build_body,
        create_commit_fn=create_commit_fn,
        stage_fn=stage_fn,
        path_filter=path_filter,
        exclude=pre_run_dirty or frozenset(),
    )
    if result.status is ScopedCommitStatus.CREATED:
        return result.sha
    if result.status is ScopedCommitStatus.FAILED:
        logger.warning("commit_policy_updates: failed ({}); returning None", result.error)
    return None


def commit_policy_writes(
    repo_root: Path | str,
    *,
    written_paths: list[str] | tuple[str, ...],
    pre_contents: Mapping[str, str | None],
    create_commit_fn: _CreateCommitFn,
    stage_fn: Callable[[Path | str, list[str]], None] | None = None,
) -> ScopedCommitResult:
    """Producer-level deterministic auto-commit for the policy preflight.

    Routes the byte-exact set of paths the preflight wrote
    (``agents_md.bootstrap`` + ``_seed_missing_starters`` outputs) plus
    the policy surfaces touched by the post-pipeline finalize pass
    (e.g. ``agents_md.condense_placeholder_block``) through the shared
    :func:`ralph.git.scoped_auto_commit.commit_deterministic_writes`
    isolation primitive. A path that was already dirty at HEAD before
    the preflight (HEAD != pre-write hash) is SKIPPED with a warning so
    the agent or user flow owns it. The fixed-message policy commit can
    never sweep in unrelated work.

    Returns a :class:`ScopedCommitResult`; ``result.sha`` is the commit
    SHA on ``CREATED``, else ``None``.
    """
    if stage_fn is None:
        stage_fn = stage_files
    return commit_deterministic_writes(
        repo_root,
        paths=tuple(written_paths),
        pre_contents=pre_contents,
        subject=POLICY_AUTO_COMMIT_SUBJECT,
        create_commit_fn=create_commit_fn,
        stage_fn=stage_fn,
    )


__all__ = [
    "POLICY_AUTO_COMMIT_SUBJECT",
    "ScopedCommitResult",
    "ScopedCommitStatus",
    "commit_policy_updates",
    "commit_policy_writes",
]
