"""Deterministic auto-commit for project-policy readiness changes.

Mirror of the wt-025 skill auto-commit: when the readiness preflight (or
the out-of-graph remediation loop) leaves the project READY, the policy
surfaces it wrote — the canonical policy directory, ``AGENTS.md``, and
``CLAUDE.md`` — are committed in one deterministic chore commit. Without
it, the next run's development agent sees the drift in its working tree
and the commit-cleanup phase warns about files it does not own.

Shares the git mechanics (scoped dirty discovery, staged-state
preservation, best-effort semantics) with the skill auto-commit through
:mod:`ralph.git.scoped_auto_commit`.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from ralph.git.scoped_auto_commit import commit_scoped_updates
from ralph.project_policy import markers

if TYPE_CHECKING:
    from collections.abc import Callable

# The deterministic conventional-commit subject line.
POLICY_AUTO_COMMIT_SUBJECT: str = "chore(policy): sync project-policy readiness"

_POLICY_AUTO_COMMIT_HEADER: str = "Auto-generated by Ralph project-policy remediation"

_POLICY_AUTO_COMMIT_CHANGED_FILES_HEADER: str = "Changed files:"

#: Repo-relative surfaces the readiness validator and remediation agent own.
#: A trailing ``/`` means directory scope; otherwise an exact file. The
#: migration candidates are content-conditional (see ``_migrated_only``).
_POLICY_COMMIT_SCOPES: tuple[str, ...] = (
    markers.CANONICAL_DIR,
    markers.AGENTS_MD,
    markers.CLAUDE_MD,
    *markers.MIGRATION_CANDIDATE_PATHS,
)

#: The stable prefix of the migrated marker (target-independent).
_MIGRATED_MARKER_PREFIX: str = markers.MIGRATED_MARKER_TEMPLATE.split("{target}")[0]


def _migrated_only(repo_root: Path) -> Callable[[str], bool]:
    """Filter: commit a migration candidate only when it carries the marker.

    Remediation adds the ``ralph-workflow-policy:migrated ->`` marker when it
    consolidates a candidate's policy content. A candidate that is dirty for
    any other reason is the user's own edit and must never be swept into the
    chore commit.
    """

    def check(path: str) -> bool:
        if path not in markers.MIGRATION_CANDIDATE_PATHS:
            return True
        try:
            content = (repo_root / path).read_text(encoding="utf-8")
        except OSError:
            return False
        return _MIGRATED_MARKER_PREFIX in content

    return check


def _build_body(dirty_paths: list[str]) -> str:
    lines = [_POLICY_AUTO_COMMIT_HEADER, "", _POLICY_AUTO_COMMIT_CHANGED_FILES_HEADER]
    lines.extend(f"- {path}" for path in dirty_paths)
    return "\n".join(lines)


def commit_policy_updates(
    repo_root: Path | str,
    create_commit_fn: Callable[[Path | str, str], str],
    *,
    stage_fn: Callable[[Path | str, list[str]], None] | None = None,
) -> str | None:
    """Create the deterministic policy-readiness auto-commit.

    Returns the commit SHA, or ``None`` when nothing inside the policy
    scopes is dirty, the workspace is not a git repo, or git errored
    (best-effort, never blocks the run).
    """
    if stage_fn is None:
        from ralph.git.operations import stage_files  # noqa: PLC0415

        stage_fn = stage_files
    return commit_scoped_updates(
        repo_root,
        scopes=_POLICY_COMMIT_SCOPES,
        subject=POLICY_AUTO_COMMIT_SUBJECT,
        body_builder=_build_body,
        create_commit_fn=create_commit_fn,
        stage_fn=stage_fn,
        path_filter=_migrated_only(Path(repo_root)),
    )


__all__ = [
    "POLICY_AUTO_COMMIT_SUBJECT",
    "commit_policy_updates",
]
