"""Transport-keyed strategy factory.

To add a new transport, append one entry to the default catalog's
``_DEFAULT_STRATEGIES`` table (in ``ralph.agents.catalog``); the factory
itself never needs editing.
"""

from __future__ import annotations

import sys
import types
from typing import TYPE_CHECKING, cast

from ._completion_mixin import CompletionEnforcingStrategy
from .generic_execution_strategy import GenericExecutionStrategy
from .opencode_execution_strategy import OpenCodeExecutionStrategy

if TYPE_CHECKING:
    from collections.abc import Mapping

    from ralph.agents._contracts import StrategyFactory
    from ralph.agents.catalog import _ParserRegistryEntry
    from ralph.config.enums import AgentTransport
    from ralph.process.child_liveness import ChildLivenessRegistry
    from ralph.process.monitor import SubagentPidSource

    from ._base import BaseExecutionStrategy


def _make_opencode_strategy(
    *,
    label_scope: str | None = None,
    registry: ChildLivenessRegistry | None = None,
    subagent_pid_source: SubagentPidSource | None = None,
    **_kwargs: object,
) -> BaseExecutionStrategy:
    """Forward transport kwargs to the OpenCode strategy constructor."""
    del _kwargs
    return OpenCodeExecutionStrategy(
        label_scope=label_scope,
        registry=registry,
        subagent_pid_source=subagent_pid_source,
    )


def _make_agy_strategy(
    *,
    label_scope: str | None = None,
    registry: ChildLivenessRegistry | None = None,
    subagent_pid_source: SubagentPidSource | None = None,
    **_kwargs: object,
) -> BaseExecutionStrategy:
    """Factory for AGY strategy: CompletionEnforcingStrategy wrapping GenericExecutionStrategy.

    Uses inheritance (not composition) because CompletionEnforcingStrategy is a mixin
    that requires being inherited to properly initialize via MRO. Pure composition
    via CompletionEnforcingStrategy(GenericExecutionStrategy(...)) fails because
    the mixin has no __init__ that accepts an argument.
    """

    class AgyExecutionStrategy(CompletionEnforcingStrategy, GenericExecutionStrategy):
        pass

    return AgyExecutionStrategy(
        label_scope=label_scope,
        registry=registry,
        subagent_pid_source=subagent_pid_source,
    )


# Public read-only view over the default catalog's ``state.strategies`` dict.
#
# The catalog is the single source of truth for the transport-to-strategy
# dispatch table.  This view is created lazily (on first attribute access)
# to break the catalog <-> _factory import cycle: catalog.py imports the
# strategy classes from this module at module load time, so the
# ``__getattr__`` below defers the catalog import until first access.
#
# The variable is NOT defined at module level so that Python's
# module-attribute lookup falls through to ``__getattr__`` on first
# access.  Once created, the view is cached in ``globals()`` so
# subsequent accesses return the same object.


def __getattr__(name: str) -> object:
    if name == "_STRATEGY_DISPATCH":
        from ralph.agents.catalog import (  # noqa: PLC0415  # reason: lazy import breaks catalog<->_factory cycle
            default_catalog,
        )

        state_strategies: Mapping[AgentTransport, StrategyFactory] = cast(
            "Mapping[AgentTransport, StrategyFactory]",
            default_catalog()._state.strategies,
        )
        value: Mapping[AgentTransport, StrategyFactory] = types.MappingProxyType(state_strategies)
        globals()["_STRATEGY_DISPATCH"] = value  # type: ignore[misc]  # reason: autogenerated code has no type support, see docs/agents/type-ignore-policy.md#autogenerated-code
        return value
    msg = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(msg)


def _view(name: str) -> Mapping[AgentTransport, StrategyFactory]:
    """Module-attribute lookup that triggers ``__getattr__`` for the lazy view.

    Used by internal functions (``strategy_for_transport``,
    ``strategy_for_command``) that need to read the legacy module-level
    view at call time.
    """
    value: Mapping[AgentTransport, StrategyFactory] = getattr(sys.modules[__name__], name)
    return value


def strategy_for_transport(
    transport: object,
    *,
    label_scope: str | None = None,
    registry: ChildLivenessRegistry | None = None,
    subagent_pid_source: SubagentPidSource | None = None,
) -> BaseExecutionStrategy:
    """Return the appropriate ExecutionStrategy for an agent transport."""
    factory = _view("_STRATEGY_DISPATCH").get(
        cast("AgentTransport", transport), GenericExecutionStrategy
    )
    return factory(
        label_scope=label_scope,
        registry=registry,
        subagent_pid_source=subagent_pid_source,
    )


def strategy_for_command(
    cmd: str,
    transport: AgentTransport,
    *,
    label_scope: str | None = None,
    registry: ChildLivenessRegistry | None = None,
    subagent_pid_source: SubagentPidSource | None = None,
) -> BaseExecutionStrategy:
    """Return the execution strategy registered for ``cmd`` when one exists.

    Custom agents registered via ``register_agent_support()`` are keyed by
    their full executable command string.  When a matching entry exists and
    its registered transport matches ``transport``, its strategy factory is
    used; otherwise the transport-keyed fallback from
    :func:`strategy_for_transport` is used.
    """
    from ralph.agents.catalog import (  # noqa: PLC0415  # reason: lazy import breaks catalog<->_factory cycle
        _ParserRegistryEntry,
    )
    from ralph.agents.parsers import (  # noqa: PLC0415  # reason: lazy import breaks catalog<->_factory cycle
        _CUSTOM_COMMAND_REGISTRY,
    )

    command_lower = cmd.lower() if cmd else ""
    custom_entry = cast(
        "_ParserRegistryEntry | None",
        _CUSTOM_COMMAND_REGISTRY.get(command_lower),  # type: ignore[attr-defined]  # reason: autogenerated code has no type support, see docs/agents/type-ignore-policy.md#autogenerated-code
    )
    if isinstance(custom_entry, _ParserRegistryEntry) and custom_entry.transport == transport:
        return custom_entry.strategy_factory(
            label_scope=label_scope,
            registry=registry,
            subagent_pid_source=subagent_pid_source,
        )
    return strategy_for_transport(
        transport,
        label_scope=label_scope,
        registry=registry,
        subagent_pid_source=subagent_pid_source,
    )
