"""Codex-specific MCP transport helpers."""

from __future__ import annotations

import atexit
import collections
import shutil
import tempfile
import tomllib
from pathlib import Path
from typing import Final, cast

import tomli_w
from loguru import logger

from ralph.mcp.artifacts.file_backend import DEFAULT_FILE_BACKEND
from ralph.mcp.artifacts.idempotent_write import write_text_if_changed
from ralph.mcp.tools.names import (
    CODEX_NATIVE_FEATURE_OVERRIDES,
    RALPH_MCP_SERVER_NAME,
)
from ralph.mcp.upstream.config import UpstreamMcpServer, normalize_upstream_mcp_servers
from ralph.workspace.agent_dir_retention import (
    register_temporary_path_owner,
    unregister_temporary_path_owner,
)

#: Sane upper bound for the in-process Codex-home registry. The deque
#: provides FIFO eviction so a long-lived process that spawns many
#: codex invocations cannot grow the in-memory registry unboundedly.
#: On-disk bound is provided by:
#:  - ``release_codex_home``: the production release path invoked from
#:    the per-invocation ``cleanup`` hook on
#:    ``ResolvedInvocationRuntime`` (see
#:    ``ralph.agents.invoke._runtime_resolvers.CodexRuntimeResolver``)
#:    in ``invoke_agent``'s ``finally`` block.
#:  - ``cleanup_codex_homes``: the atexit-registered net that rmtree's
#:    any orphan homes a crashed interpreter left behind.
#: An earlier version of this module used ``_allocate_codex_home_dir``
#: to rmtree the FIFO-evicted oldest entry on every append past the
#: cap, but that could delete a home that was still active in a live
#: Codex subprocess (analysis feedback wt-024 round 2). The active-home
#: invariant is now: eviction only REMOVES from the registry; the
#: on-disk directory survives until ``release_codex_home`` is called
#: by the owner or ``atexit`` reaps it.
_DEFAULT_CODEX_HOME_CAP: int = 64
# After every allocation the lifetime registry stays bounded, even when every
# outstanding home is active (1024 paths are roughly 100 KiB of bookkeeping).
_ALL_CODEX_HOMES_CAP: Final[int] = 1024

# bounded-accumulator-ok: deque(maxlen=_DEFAULT_CODEX_HOME_CAP) provides
# real FIFO eviction of the in-memory registry. The on-disk bound is
# provided by ``release_codex_home`` (production release path via the
# ResolvedInvocationRuntime.cleanup hook) and ``cleanup_codex_homes``
# (atexit net); see _allocate_codex_home_dir for the active-home
# invariant that prevents evicting a home whose subprocess is still
# running.
_allocated_codex_homes: collections.deque[str] = collections.deque(
    maxlen=_DEFAULT_CODEX_HOME_CAP
)  # bounded-accumulator-ok  # type: ignore[var-annotated]  # reason: autogenerated code has no type support, see docs/agents/type-ignore-policy.md#autogenerated-code
#: Outstanding Codex homes tracked for atexit cleanup, capped at
#: ``_ALL_CODEX_HOMES_CAP``. An evicted path loses only its atexit
#: registration: it is never removed on disk because it may be active.
_all_allocated_codex_homes: set[str] = (
    set()
)  # bounded-accumulator-ok: hard-capped at _ALL_CODEX_HOMES_CAP (1024) with no-rmtree eviction; release_codex_home drains on the healthy path and cleanup_codex_homes (atexit) drains the rest.


def cleanup_codex_homes() -> None:
    """Remove every Codex home dir still registered for atexit cleanup.

    The capped ``_all_allocated_codex_homes`` set retains outstanding homes
    up to ``_ALL_CODEX_HOMES_CAP``. A path evicted beyond that cap loses only
    its atexit registration, never its directory: normal owners use
    ``release_codex_home``; orphaned system-temp homes rely on OS cleanup;
    workspace-scoped homes under ``.agent/tmp`` rely on run-start aged
    reclamation by ``sweep_agent_dir``.

    Standalone importable function so tests can invoke cleanup
    directly without depending on ``atexit`` timing. ``ignore_errors``
    makes the function robust to partial interpreter shutdown and
    already-removed dirs.
    """
    for home in list(_all_allocated_codex_homes):
        # filesystem-write-ok: atexit cleanup of run-scoped temporary Codex homes
        shutil.rmtree(home, ignore_errors=True)
    _all_allocated_codex_homes.clear()
    _allocated_codex_homes.clear()


def release_codex_home(codex_home: str) -> bool:
    """Release a single Codex home during the normal runtime lifecycle.

    Removes the path from both ``_all_allocated_codex_homes`` (so the
    atexit net will not re-rrmtree it) AND ``_allocated_codex_homes``
    (the bounded deque). Rmtree's the on-disk directory with
    ``ignore_errors=True`` so the operation is idempotent.

    Returns ``True`` if the home was in the bounded deque (active
    bookkeeping member); ``False`` if the home was not in the deque
    (already released, never registered, or FIFO-evicted before this
    call). The returned boolean preserves the documented contract
    used by callers that want to know whether they were the first
    releaser; an evicted-but-unreleased home returns ``False``
    even though the on-disk rmtree still happens.

    This is the production release path: callers that allocate a
    Codex home, use it for a bounded operation (e.g. the MCP probe
    synthesizes a config + runs a handshake, then has no further
    use for the home), and want to release it BEFORE interpreter
    shutdown MUST call this function. ``atexit``-only cleanup leaves
    every allocated home on disk for the entire interpreter lifetime
    and grows the registry unboundedly across a long run.
    """
    home_path = Path(codex_home)
    workspace_root = _workspace_root_for_codex_home(home_path)
    if workspace_root is not None:
        unregister_temporary_path_owner(workspace_root, home_path)
    _all_allocated_codex_homes.discard(codex_home)
    try:
        _allocated_codex_homes.remove(codex_home)
    except ValueError:
        # filesystem-write-ok: idempotent release of run-scoped temporary Codex home
        shutil.rmtree(codex_home, ignore_errors=True)
        return False
    # filesystem-write-ok: normal lifecycle release of run-scoped temporary Codex home
    shutil.rmtree(codex_home, ignore_errors=True)
    return True


atexit.register(cleanup_codex_homes)


def _workspace_root_for_codex_home(path: Path) -> Path | None:
    """Return the workspace root when *path* is directly under ``.agent/tmp``."""
    try:
        if path.parent.name == "tmp" and path.parent.parent.name == ".agent":
            return path.parent.parent.parent
    except OSError:
        return None
    return None


def prepare_codex_home(
    endpoint: str | None,
    *,
    workspace_path: Path | None,
    existing_home: str | None,
    master_prompt_file: str | None,
    unsafe_mode: bool = False,
    run_id: str | None = None,
) -> str:
    """Prepare an isolated Codex home directory and return its path."""
    codex_home, _upstreams = prepare_codex_home_with_upstreams(
        endpoint,
        workspace_path=workspace_path,
        existing_home=existing_home,
        master_prompt_file=master_prompt_file,
        unsafe_mode=unsafe_mode,
        run_id=run_id,
    )
    return codex_home


def _mapping_at(config: dict[str, object], key: str) -> dict[str, object]:
    """Return the mapping stored at *key*, or an empty one when it is absent."""
    value = config.get(key)
    if isinstance(value, dict):
        return cast("dict[str, object]", value)
    return {}


def _ralph_feature_overrides() -> dict[str, object]:
    """Return Ralph's ``[features]`` settings as real TOML booleans."""
    return {key.split(".", 1)[1]: value == "true" for key, value in CODEX_NATIVE_FEATURE_OVERRIDES}


def _merge_codex_config(
    base: dict[str, object],
    *,
    endpoint: str | None,
    master_prompt_file: str | None,
    unsafe_mode: bool,
) -> dict[str, object]:
    """Layer Ralph's required settings over the operator's parsed config.

    Merging mappings -- rather than splicing text into the operator's file --
    is what makes this algorithm safe by construction: a mapping cannot hold
    the same key twice, so no combination of operator settings can produce the
    duplicate key that makes Codex abort with "Error loading config.toml". A
    key Ralph owns is overwritten; every other operator key is carried through
    untouched.
    """
    merged = dict(base)
    if endpoint:
        merged["features"] = {**_mapping_at(base, "features"), **_ralph_feature_overrides()}
        # Restricted mode hides every operator upstream: Ralph loads them
        # itself and re-exposes them as proxied tools. Unsafe mode keeps them,
        # minus any stale Ralph entry the live endpoint replaces.
        operator_servers = _mapping_at(base, "mcp_servers") if unsafe_mode else {}
        merged["mcp_servers"] = {
            **{
                name: value
                for name, value in operator_servers.items()
                if name != RALPH_MCP_SERVER_NAME
            },
            RALPH_MCP_SERVER_NAME: {"url": endpoint, "enabled": True},
        }
    if master_prompt_file:
        merged["model_instructions_file"] = master_prompt_file
    return merged


def _parse_source_config(base_config: str, source_config: Path) -> dict[str, object]:
    """Parse the operator's config, degrading to Ralph-only settings if it is invalid."""
    if not base_config.strip():
        return {}
    try:
        parsed: object = tomllib.loads(base_config)
    except ValueError as exc:
        logger.error(
            "Source Codex config {} is not loadable TOML ({}); Codex could not load it "
            "either. Continuing with Ralph-only settings -- operator settings such as "
            "model_provider will NOT apply until that file is fixed.",
            source_config,
            exc,
        )
        return {}
    if not isinstance(parsed, dict):
        return {}
    return cast("dict[str, object]", parsed)


def _render_codex_config(merged: dict[str, object], config_path: Path) -> str:
    """Serialize *merged* to TOML, verifying it reads back as what was intended.

    The round-trip check is the standing guarantee that this function cannot
    hand Codex a config that means something other than the merge decided --
    it runs on every invocation, not only under test.
    """
    config_text = tomli_w.dumps(merged)
    try:
        reparsed: object = tomllib.loads(config_text)
    except ValueError as exc:  # pragma: no cover - unreachable via TOML types
        logger.error(
            "Synthesized Codex config {} did not round-trip ({}); Codex will refuse to start.",
            config_path,
            exc,
        )
        return config_text
    if reparsed != merged:  # pragma: no cover - unreachable via TOML types
        logger.error(
            "Synthesized Codex config {} does not read back as the merged settings; "
            "Codex may behave differently from what Ralph configured.",
            config_path,
        )
    return config_text


def prepare_codex_home_with_upstreams(
    endpoint: str | None,
    *,
    workspace_path: Path | None,
    existing_home: str | None,
    master_prompt_file: str | None,
    unsafe_mode: bool = False,
    run_id: str | None = None,
) -> tuple[str, tuple[UpstreamMcpServer, ...]]:
    """Prepare an isolated Codex home directory and return its path with upstream servers."""
    codex_root = _allocate_codex_home_dir(workspace_path)
    if workspace_path is not None and run_id is not None:
        register_temporary_path_owner(workspace_path, codex_root, run_id)
    # filesystem-write-ok: create this run-scoped isolated Codex home before materializing configuration
    codex_root.mkdir(parents=True, exist_ok=True)

    source_home = Path(existing_home).expanduser() if existing_home else Path.home() / ".codex"
    if source_home.exists():
        _mirror_codex_home(source_home, codex_root)
    source_config = source_home / "config.toml"
    base_config = source_config.read_text(encoding="utf-8") if source_config.exists() else ""
    base = _parse_source_config(base_config, source_config)
    upstreams = _extract_codex_upstream_servers(base)
    if endpoint:
        logger.warning(
            "Codex MCP tool restriction is best-effort: apply_patch and core "
            "editing primitives cannot be disabled. See "
            "ralph-workflow/docs/sphinx/mcp-tool-restriction.md."
        )
    merged = _merge_codex_config(
        base,
        endpoint=endpoint,
        master_prompt_file=master_prompt_file,
        unsafe_mode=unsafe_mode,
    )
    config_path = codex_root / "config.toml"
    config_text = _render_codex_config(merged, config_path)
    write_text_if_changed(DEFAULT_FILE_BACKEND, config_path, config_text, encoding="utf-8")
    return str(codex_root), upstreams


def _mirror_codex_home(source_home: Path, codex_root: Path) -> None:
    for entry in source_home.iterdir():
        if entry.name == "config.toml":
            continue
        destination = codex_root / entry.name
        try:
            destination.symlink_to(entry, target_is_directory=entry.is_dir())
        except OSError:
            if entry.is_dir():
                # filesystem-write-ok: fallback materialization of isolated temporary Codex-home input
                shutil.copytree(entry, destination, dirs_exist_ok=True)
            else:
                # filesystem-write-ok: fallback materialization of isolated temporary Codex-home input
                shutil.copy2(entry, destination)


def _allocate_codex_home_dir(workspace_path: Path | None) -> Path:
    if workspace_path is None:
        codex_root = Path(tempfile.mkdtemp(prefix="ralph-codex-home-"))
    else:
        tmp_root = workspace_path / ".agent" / "tmp"
        tmp_root.mkdir(parents=True, exist_ok=True)
        codex_root = Path(tempfile.mkdtemp(prefix="codex-home-", dir=str(tmp_root)))
    # The deque is bounded; when appending past the cap, FIFO eviction
    # drops the oldest entry from the in-memory registry so the
    # registry itself cannot grow unboundedly. We deliberately do
    # NOT rmtree the evicted entry on-disk: the evicted home may
    # still be ACTIVE (its owning Codex subprocess is still running).
    # Earlier code performed the rmtree here, but analysis feedback
    # wt-024 round 2 found that this could delete the
    # CODEX_HOME directory out from under a running Codex agent when
    # more than ``_DEFAULT_CODEX_HOME_CAP`` concurrent invocations
    # occurred. The on-disk bound is now provided by:
    #   1. ``release_codex_home`` invoked from the
    #      ``ResolvedInvocationRuntime.cleanup`` hook (the production
    #      release path) when the owning subprocess finishes; AND
    #   2. ``cleanup_codex_homes`` (the atexit net, iterating
    #      ``_all_allocated_codex_homes`` so FIFO-evicted homes are
    #      still reaped) for orphans.
    # Use ``_allocated_codex_homes.maxlen`` (not the module-level
    # ``_DEFAULT_CODEX_HOME_CAP``) so a test that swaps the deque with
    # a smaller-maxlen one (see
    # ``tests/integration/test_codex_home_release_path.py``) still
    # bounds the registry at the test's cap. Tests MUST NOT be able
    # to opt out of the registry bound by shrinking the cap.
    maxlen = _allocated_codex_homes.maxlen
    if maxlen is not None and len(_allocated_codex_homes) >= maxlen:
        # FIFO eviction from the REGISTRY ONLY. The on-disk directory
        # is intentionally left in place; it is rmtree'd only when
        # ``release_codex_home`` (production release path) or
        # ``cleanup_codex_homes`` (atexit net) runs. The evicted path
        # remains in ``_all_allocated_codex_homes`` so the atexit net
        # can still find and rmtree it if no owner releases it first.
        _allocated_codex_homes.popleft()
    home_str = str(codex_root)
    _allocated_codex_homes.append(home_str)
    _all_allocated_codex_homes.add(home_str)
    if len(_all_allocated_codex_homes) > _ALL_CODEX_HOMES_CAP:
        # Never rmtree here: every outstanding home may still be active.
        # Eviction only drops atexit tracking; normal release removes the
        # directory, while orphaned homes are handled by system-temp cleanup
        # or run-start aged .agent/tmp reclamation by sweep_agent_dir.
        evicted = next(iter(_all_allocated_codex_homes - {home_str}))
        _all_allocated_codex_homes.discard(evicted)
        logger.warning(
            "codex home lifetime registry over _ALL_CODEX_HOMES_CAP={}; "
            "dropped atexit registration for {} (directory left in place)",
            _ALL_CODEX_HOMES_CAP,
            evicted,
        )
    return codex_root


def _extract_codex_upstream_servers(base: dict[str, object]) -> tuple[UpstreamMcpServer, ...]:
    """Return the operator's own MCP servers so Ralph can re-expose them as proxied tools.

    Ralph's own entry is dropped first. ``ralph`` is a reserved upstream name
    and ``normalize_upstream_mcp_servers`` raises on it, so an operator config
    that already names it -- one copied back from a synthesized Codex home, or
    written by hand -- used to abort every Codex invocation instead of being
    replaced by the live endpoint. Every other agent drops it the same way
    before normalizing (see ``mcp_config_as_upstreams``).
    """
    mcp_servers = {
        name: value
        for name, value in _mapping_at(base, "mcp_servers").items()
        if name != RALPH_MCP_SERVER_NAME
    }
    if not mcp_servers:
        return ()
    return normalize_upstream_mcp_servers(mcp_servers)


__all__ = [
    "cleanup_codex_homes",
    "prepare_codex_home",
    "prepare_codex_home_with_upstreams",
    "release_codex_home",
]
