"""Shared Ralph MCP environment variable names."""

from __future__ import annotations

from enum import StrEnum


class McpEnvVar(StrEnum):
    ENDPOINT = "RALPH_MCP_ENDPOINT"
    RUN_ID = "RALPH_MCP_RUN_ID"
    AGENT_LABEL_SCOPE = "RALPH_AGENT_LABEL_SCOPE"
    SESSION = "RALPH_MCP_SESSION_JSON"
    SESSION_FILE = "RALPH_MCP_SESSION_FILE"
    PREFLIGHT_TIMEOUT_MS = "RALPH_MCP_PREFLIGHT_TIMEOUT_MS"
    HEARTBEAT_INTERVAL_MS = "RALPH_MCP_HEARTBEAT_INTERVAL_MS"
    HEARTBEAT_MISSES = "RALPH_MCP_HEARTBEAT_MISSES"
    HEARTBEAT_RECONNECT_MS = "RALPH_MCP_HEARTBEAT_RECONNECT_MS"


MCP_ENDPOINT_ENV = McpEnvVar.ENDPOINT
MCP_RUN_ID_ENV = McpEnvVar.RUN_ID
AGENT_LABEL_SCOPE_ENV = McpEnvVar.AGENT_LABEL_SCOPE
MCP_SESSION_ENV = McpEnvVar.SESSION
MCP_SESSION_FILE_ENV = McpEnvVar.SESSION_FILE
MCP_PREFLIGHT_TIMEOUT_MS_ENV = McpEnvVar.PREFLIGHT_TIMEOUT_MS
MCP_HEARTBEAT_INTERVAL_MS_ENV = McpEnvVar.HEARTBEAT_INTERVAL_MS
MCP_HEARTBEAT_MISSES_ENV = McpEnvVar.HEARTBEAT_MISSES
MCP_HEARTBEAT_RECONNECT_MS_ENV = McpEnvVar.HEARTBEAT_RECONNECT_MS
