"""Shared Ralph MCP environment variable names."""

from __future__ import annotations

from enum import StrEnum


class McpEnvVar(StrEnum):
    """Environment variable names used to configure the Ralph MCP connection."""

    ENDPOINT = "RALPH_MCP_ENDPOINT"
    RUN_ID = "RALPH_MCP_RUN_ID"
    AGENT_LABEL_SCOPE = "RALPH_AGENT_LABEL_SCOPE"
    SESSION = "RALPH_MCP_SESSION_JSON"
    SESSION_FILE = "RALPH_MCP_SESSION_FILE"
    PREFLIGHT_TIMEOUT_MS = "RALPH_MCP_PREFLIGHT_TIMEOUT_MS"
    SUPERVISION_INTERVAL_MS = "RALPH_MCP_SUPERVISION_INTERVAL_MS"
    PROBE_TIMEOUT_MS = "RALPH_MCP_PROBE_TIMEOUT_MS"
    WORKER_ARTIFACT_DIR = "RALPH_WORKER_ARTIFACT_DIR"
    WORKER_ID = "RALPH_WORKER_ID"
    WORKER_NAMESPACE = "RALPH_WORKER_NAMESPACE"
    PARALLEL_WORKER_MANIFEST = "RALPH_PARALLEL_WORKER_MANIFEST"


MCP_ENDPOINT_ENV = McpEnvVar.ENDPOINT
MCP_RUN_ID_ENV = McpEnvVar.RUN_ID
AGENT_LABEL_SCOPE_ENV = McpEnvVar.AGENT_LABEL_SCOPE
MCP_SESSION_ENV = McpEnvVar.SESSION
MCP_SESSION_FILE_ENV = McpEnvVar.SESSION_FILE
MCP_PREFLIGHT_TIMEOUT_MS_ENV = McpEnvVar.PREFLIGHT_TIMEOUT_MS
MCP_SUPERVISION_INTERVAL_MS_ENV = McpEnvVar.SUPERVISION_INTERVAL_MS
MCP_PROBE_TIMEOUT_MS_ENV = McpEnvVar.PROBE_TIMEOUT_MS
WORKER_ARTIFACT_DIR_ENV = McpEnvVar.WORKER_ARTIFACT_DIR
WORKER_ID_ENV = McpEnvVar.WORKER_ID
WORKER_NAMESPACE_ENV = McpEnvVar.WORKER_NAMESPACE
RALPH_PARALLEL_WORKER_MANIFEST_ENV = McpEnvVar.PARALLEL_WORKER_MANIFEST
