from __future__ import annotations

from shlex import quote
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

    from ralph._existing_install import ExistingInstall
    from ralph._install_copy_tree import SnapshotIdentity

DEV_LAUNCHER_NAME = "rdev"
_SHORT_COMMIT_LENGTH = 8


def render_dev_launcher(package_dir: Path, uv_executable: str) -> str:
    return (
        "#!/usr/bin/env bash\n"
        "# Dev build of Ralph Workflow (generated by `make install`).\n"
        "# Runs the copied dev snapshot via uv; counterpart of the stable\n"
        "# `ralph` installed with `uv tool install`.\n"
        f"exec {quote(uv_executable)} run --locked --project {quote(str(package_dir))} ralph \"$@\"\n"
    )


def render_dev_launcher_notice(existing: ExistingInstall) -> str:
    return (
        f"Existing {existing.kind} Ralph Workflow install at {existing.executable} "
        "is left untouched.\n"
        f"This build installs the '{DEV_LAUNCHER_NAME}' launcher instead, replacing any "
        f"'{DEV_LAUNCHER_NAME}' from an earlier dev build.\n"
        f"Run '{DEV_LAUNCHER_NAME}' to use this checkout; 'ralph' keeps running the "
        "existing install."
    )


def short_commit(commit: str) -> str:
    return commit[:_SHORT_COMMIT_LENGTH] or "(unknown)"


def render_install_summary(
    *,
    source: Path,
    commit: str,
    version: str,
    snapshot: Path,
    launcher: Path,
    replaced: SnapshotIdentity | None,
) -> str:
    lines = [
        "Ralph Workflow dev build installed as 'rdev'.",
        f"  source:   {source}",
        f"  commit:   {short_commit(commit)}",
        f"  version:  {version}",
        f"  snapshot: {snapshot}",
        f"  launcher: {launcher}",
    ]
    if replaced is not None:
        took_over = replaced.source_path != "" and replaced.source_path != str(source)
        marker = "  <- taken over from a different checkout" if took_over else ""
        previous_source = replaced.source_path or "(unknown source)"
        lines.append(
            f"  replaced: {replaced.version or '(unknown version)'} from {previous_source} "
            f"@ {short_commit(replaced.source_commit)}{marker}"
        )
    return "\n".join(lines)
