"""Installation helpers for Ralph Workflow dev and stable builds.

Two builds are kept deliberately separate so they never shadow each other:

* **Dev build** — a self-contained snapshot of the current checkout
  (``install_dev_checkout``), launched globally as ``rdev``. It retains its
  own environment and package data, so it cannot collide with stable ``ralph``.
* **Stable build** — a pinned release installed as an isolated global ``ralph``
  command via ``uv tool`` (``install_stable_release``).

See ``CONTRIBUTING.md`` (§"Dev build vs stable build") for the workflow.
"""

from __future__ import annotations

import argparse
import os
import shutil
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Protocol

from ralph._install_conflicts import (
    ConflictResolution,
    detect_existing_ralph,
    prompt_for_conflict,
    real_environment,
    resolve_package_file,
)
from ralph._install_copy_tree import copy_install_tree
from ralph.executor.process import ProcessExecutionError, ProcessRunOptions, run_process
from ralph.mcp.artifacts.file_backend import DEFAULT_FILE_BACKEND
from ralph.mcp.artifacts.idempotent_write import write_text_if_changed
from ralph.process._spawn_env import sanitize_process_environment

if TYPE_CHECKING:
    from collections.abc import Callable, Sequence

    from ralph._existing_install import ExistingInstall

STABLE_PACKAGE_NAME = "ralph-workflow"
DEV_LAUNCHER_NAME = "rdev"


class RunCommand(Protocol):
    """Protocol for the subprocess runner passed to the install helpers."""

    def __call__(self, command: Sequence[str], *, cwd: Path) -> None: ...


class LauncherWriter(Protocol):
    """Protocol for writing the dev launcher script to disk."""

    def __call__(self, path: Path, content: str) -> None: ...


class BuildMetaWriter(Protocol):
    """Protocol for stamping runtime-only snapshot metadata."""

    def __call__(
        self,
        package_dir: Path,
        flavor: str,
        *,
        source_commit: str = "",
        installed_at: str = "",
    ) -> None: ...


def _run_command(command: Sequence[str], *, cwd: Path) -> None:
    cmd = tuple(command)
    result = run_process(cmd[0], cmd[1:], options=ProcessRunOptions(cwd=cwd))
    if not result.succeeded:
        raise ProcessExecutionError(
            cmd,
            f"Command failed with exit code {result.returncode}: {' '.join(cmd)}",
        )


def render_dev_launcher(package_dir: Path) -> str:
    """Return the contents of the ``rdev`` launcher for ``package_dir``.

    The launcher runs the copied dev snapshot via ``uv run`` while staying in
    the caller's working directory (the workspace ``ralph`` operates on); only
    the project environment is sourced from ``package_dir``.
    """
    return (
        "#!/usr/bin/env bash\n"
        "# Dev build of Ralph Workflow (generated by `make install`).\n"
        "# Runs the copied dev snapshot via uv; counterpart of the stable\n"
        "# `ralph` installed with `uv tool install`.\n"
        f'exec uv run --project "{package_dir}" ralph "$@"\n'
    )


def render_dev_launcher_notice(existing: ExistingInstall) -> str:
    """Return the notice shown when a global ``ralph`` coexists with the dev build.

    The dev build owns only ``rdev``, so an existing ``ralph`` is not a conflict
    to resolve: it is left exactly as it is, and the notice tells the reader
    which command now runs this checkout.
    """
    return (
        f"Existing {existing.kind} Ralph Workflow install at {existing.executable} "
        "is left untouched.\n"
        f"This build installs the '{DEV_LAUNCHER_NAME}' launcher instead, replacing any "
        f"'{DEV_LAUNCHER_NAME}' from an earlier dev build.\n"
        f"Run '{DEV_LAUNCHER_NAME}' to use this checkout; 'ralph' keeps running the "
        "existing install."
    )


def write_dev_launcher(path: Path, content: str) -> None:
    """Write ``content`` to ``path`` and mark it executable."""
    path.parent.mkdir(parents=True, exist_ok=True)
    write_text_if_changed(DEFAULT_FILE_BACKEND, path, content, encoding="utf-8")
    # filesystem-write-ok: caller-visible dev launcher must be executable after retained content publication
    path.chmod(0o755)


def _utc_now_iso8601() -> str:
    """Return the current UTC time for runtime-only snapshot provenance."""
    return datetime.now(UTC).isoformat()


def _resolve_source_commit(source_dir: Path) -> str:
    """Return the source checkout commit, or an empty stamp when unavailable."""
    try:
        result = run_process(
            "git",
            ("rev-parse", "HEAD"),
            options=ProcessRunOptions(cwd=source_dir, timeout=5.0),
        )
    except (OSError, ProcessExecutionError):
        return ""
    return result.stdout.strip() if result.succeeded else ""


def _write_build_flavor(
    package_dir: Path,
    flavor: str,
    *,
    source_commit: str = "",
    installed_at: str = "",
) -> None:
    build_meta = package_dir / "ralph" / "_build_meta.py"
    content = build_meta.read_text(encoding="utf-8")
    updated_content = content.replace('BUILD_FLAVOR: str = ""', f'BUILD_FLAVOR: str = "{flavor}"')
    updated_content = updated_content.replace(
        'BUILD_SOURCE_COMMIT: str = ""', f'BUILD_SOURCE_COMMIT: str = "{source_commit}"'
    )
    updated_content = updated_content.replace(
        'BUILD_INSTALLED_AT: str = ""', f'BUILD_INSTALLED_AT: str = "{installed_at}"'
    )
    write_text_if_changed(DEFAULT_FILE_BACKEND, build_meta, updated_content, encoding="utf-8")


def install_dev_checkout(
    *,
    run: RunCommand = _run_command,
    uv_executable: str | None,
    cwd: Path,
    launcher_dir: Path,
    install_root: Path | None = None,
    copy_tree: Callable[[Path, Path], Path] = copy_install_tree,
    write_flavor: BuildMetaWriter = _write_build_flavor,
    resolve_commit: Callable[[Path], str] = _resolve_source_commit,
    installed_at: Callable[[], str] = _utc_now_iso8601,
    write_launcher: LauncherWriter = write_dev_launcher,
    flavor: str = "-dev",
) -> None:
    """Set up the current checkout as a dev build via ``uv sync``.

    Copies the checkout to a stable location, syncs that snapshot's uv
    environment, and writes an ``rdev`` launcher aimed at the copy.  The copy
    retains package data such as templates and policy defaults after the source
    checkout is deleted.
    """
    if uv_executable is None:
        raise RuntimeError(
            "uv is required to set up the dev build. Install uv first: "
            "https://docs.astral.sh/uv/getting-started/installation/"
        )
    destination = (
        install_root or Path.home() / ".local" / "share" / "ralph-workflow-dev"
    ) / "current"
    copied_dir = copy_tree(cwd, destination)
    write_flavor(
        copied_dir,
        flavor,
        source_commit=resolve_commit(cwd),
        installed_at=installed_at(),
    )
    run((uv_executable, "sync", "--extra", "dev"), cwd=copied_dir)
    write_launcher(launcher_dir / DEV_LAUNCHER_NAME, render_dev_launcher(copied_dir))


def install_stable_release(
    *,
    run: RunCommand = _run_command,
    uv_executable: str | None,
    cwd: Path,
    version: str | None = None,
    from_path: Path | None = None,
    which_fn: Callable[[str], str | None] = shutil.which,
    resolve_installed_package_file: Callable[[str], Path | None] = resolve_package_file,
    write_flavor: BuildMetaWriter = _write_build_flavor,
    resolve_commit: Callable[[Path], str] = _resolve_source_commit,
    installed_at: Callable[[], str] = _utc_now_iso8601,
) -> None:
    """Install a stable release as the isolated global ``ralph`` command.

    Uses ``uv tool install`` so the stable build lives in its own environment and
    stays independent of the working tree.

    Without ``version`` the latest published release is installed, and an
    already-installed older ``ralph`` is upgraded: ``--force`` re-runs the install
    even when the tool is already present (a plain ``uv tool install`` is a no-op
    in that case), and ``--upgrade`` (which implies ``--refresh``) re-resolves
    against PyPI so a newer release is picked up. Pass ``version`` to pin a
    specific release instead.
    """
    if uv_executable is None:
        raise RuntimeError(
            "uv is required to install the stable build. Install uv first: "
            "https://docs.astral.sh/uv/getting-started/installation/"
        )
    command = [uv_executable, "tool", "install", "--force"]
    if from_path is not None:
        command.append(str(from_path))
    elif version is None:
        command.extend(("--upgrade", STABLE_PACKAGE_NAME))
    else:
        command.append(f"{STABLE_PACKAGE_NAME}=={version}")
    run(tuple(command), cwd=cwd)
    if from_path is not None:
        installed_package_file = resolve_installed_package_file(which_fn("ralph") or "")
        if installed_package_file is None:
            raise RuntimeError(
                "Installed ralph package could not be located to mark it as a manual build."
            )
        write_flavor(
            installed_package_file.parents[1],
            "-build",
            source_commit=resolve_commit(cwd),
            installed_at=installed_at(),
        )


class _InstallArgs(argparse.Namespace):
    """Typed arguments parsed by the installer entry point."""

    stable: bool
    build: bool
    version: str | None
    from_path: Path | None


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m ralph.install",
        description="Install Ralph Workflow as a dev build (default) or a pinned stable build.",
    )
    parser.add_argument(
        "--stable",
        action="store_true",
        help="Install a pinned stable release as the global `ralph` command via uv tool.",
    )
    parser.add_argument(
        "--build",
        action="store_true",
        help="Install a self-contained manual build snapshot with a -build version suffix.",
    )
    parser.add_argument(
        "--version",
        default=None,
        help="Pin the stable release to this version (implies --stable).",
    )
    parser.add_argument(
        "--from",
        dest="from_path",
        type=Path,
        default=None,
        help="Install a locally built wheel and mark it as a manual build.",
    )
    return parser


def _parse_args(argv: Sequence[str] | None) -> tuple[bool, bool, str | None, Path | None]:
    parsed = _InstallArgs()
    _build_parser().parse_args(argv, namespace=parsed)
    return parsed.stable, parsed.build, parsed.version, parsed.from_path


def main(argv: Sequence[str] | None = None) -> int:
    """Install the dev build by default, or the stable build with ``--stable``."""
    sanitize_process_environment()
    stable, build, version, from_path = _parse_args(argv)
    package_dir = Path(__file__).resolve().parents[1]

    if stable or version is not None or from_path is not None:
        _resolve_install_conflict(run=_run_command)
        install_stable_release(
            run=_run_command,
            uv_executable=shutil.which("uv"),
            cwd=package_dir,
            version=version,
            from_path=from_path,
        )
    else:
        _report_dev_launcher_conflict()
        install_dev_checkout(
            run=_run_command,
            uv_executable=shutil.which("uv"),
            cwd=package_dir,
            launcher_dir=Path.home() / ".local" / "bin",
            flavor="-build" if build else "-dev",
        )
    return 0


def _report_dev_launcher_conflict(*, emit: Callable[[str], None] = print) -> None:
    """Explain that a detected global ``ralph`` is kept and ``rdev`` is used instead."""
    existing = detect_existing_ralph(
        which_fn=shutil.which,
        environ=real_environment(),
        resolve_package_file=resolve_package_file,
    )
    if existing is None:
        return
    emit(render_dev_launcher_notice(existing))


def _resolve_install_conflict(*, run: RunCommand) -> None:
    existing = detect_existing_ralph(
        which_fn=shutil.which,
        environ=real_environment(),
        resolve_package_file=resolve_package_file,
    )
    if existing is None:
        return
    resolution = prompt_for_conflict(
        existing,
        input_fn=input,
        is_tty=os.isatty(0),
        cwd=Path(__file__).resolve().parents[1],
    )
    if resolution is ConflictResolution.ABORT:
        raise RuntimeError(f"Installation aborted because {existing.executable} already exists.")
    if resolution is ConflictResolution.REMOVE:
        command = existing.remove_command
        if command is None:
            raise RuntimeError(f"Cannot remove existing {existing.kind} install automatically.")
        run(command, cwd=Path.cwd())


if __name__ == "__main__":
    raise SystemExit(main())
