from collections.abc import Iterator, Mapping

class Node:
    @property
    def attributes(self) -> Mapping[str, str | None]: ...
    def decompose(self) -> None: ...
    def text(self, *, separator: str = ..., strip: bool = ...) -> str: ...

class HTMLParser:
    def __init__(self, html: str) -> None: ...
    @property
    def root(self) -> Node | None: ...
    def css(self, selector: str) -> Iterator[Node]: ...
