#[path = "verify_command.rs"]
mod command;
#[path = "verify_groups.rs"]
mod groups;
#[path = "verify_native.rs"]
mod native;
#[path = "verify_policy.rs"]
mod policy;
#[path = "verify_progress.rs"]
mod progress;
#[path = "verify_types.rs"]
pub mod types;

pub(crate) use command::is_cacheable_success_output;
#[cfg(test)]
pub use command::run_checks;
#[cfg(test)]
pub(crate) use command::{classify, run_checks_with_heartbeat, verify, HEARTBEAT_INTERVAL};
pub use command::{CommandOutput, CommandRunner, CommandSpec};

#[cfg(test)]
pub use progress::NoopProgressReporter;
pub use progress::{ProgressReporter, StderrProgressReporter};

#[cfg(test)]
pub use groups::verify_fast;
pub use groups::verify_fast_with_options;
pub use groups::CheckGroups;

#[cfg(test)]
pub(crate) use groups::all_required_checks;
pub(crate) use groups::FORBIDDEN_ALLOW_EXPECT_POLICY;
pub use native::NATIVE_REQUIRED_CHECKS;
#[cfg(test)]
pub(crate) use native::{
    collect_autogenerated_marked_files, detect_autogenerated_reason,
    format_autogenerated_marker_message,
};

pub use groups::{
    CORE_CARGO_CHECKS, DYLINT_CHECKS, FMT_CHECKS, FRONTEND_INSTALL_CHECKS,
    FRONTEND_POST_INSTALL_CHECKS, GUI_CARGO_CHECKS, RELEASE_BUILD_CHECKS, XTASK_CARGO_CHECKS,
};
#[cfg(test)]
pub use groups::{FRONTEND_CHECKS, RELEASE_CHECKS};
#[cfg(test)]
pub(crate) use policy::{
    CLIPPY_CORE_CHECK_NAME, CORE_LIB_TEST_CHECK_NAME, INTEGRATION_TEST_CHECK_NAME,
};

pub use types::{
    CheckFailure, CheckStatus, NativeCheck, NativeCheckResult, VerifyExitCode, VerifyReport,
};

#[cfg(test)]
#[path = "verify_tests.rs"]
mod tests;
