use std::path::Path;
use std::sync::{Arc, Mutex};
use std::time::Instant;

use anyhow::{Context as _, Result};

use super::command::{run_checks_cancellable, CommandRunner, CommandSpec};
use super::native::{collect_autogenerated_marked_files, format_autogenerated_marker_message};
use super::progress::ProgressReporter;
use super::types::{
    CancellationState, CheckFailure, CheckStatus, FailurePriority, NativeCheck, VerifyExitCode,
    VerifyReport,
};

pub(crate) const FORBIDDEN_ALLOW_EXPECT_POLICY: &str = r#"LINT POLICY: allow(...) attributes are PROHIBITED in this codebase.

There are NO permitted allow(...) exceptions. If the lint fires on external code
(test harness, proc-macro output, external trait impls, build-script artifacts),
use the expect(..., reason = "...") attribute instead.

The expect(...) attribute is permitted ONLY when ALL three conditions are met:
1. The lint fires on code you cannot modify (proc-macro output, external trait impls, build-script artifacts).
2. It includes reason = "..." naming the specific external source.
3. It is the narrowest possible scope (item attribute, not module or crate).

cfg_attr(..., expect(..., reason = "...")) is allowed as the conditional form of the above.
cfg_attr(test, allow(...)) is NOT a valid substitute for the expect() form.
If a lint fires on code you wrote, refactor the code instead of suppressing."#;

fn format_scan_violations(violations: &[crate::io::scanner::NativeScanViolation]) -> String {
    violations
        .iter()
        .map(|v| format!("{}:{}:{}", v.file.display(), v.line_number, v.line))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Check groups for parallel verification.
pub struct CheckGroups<'a> {
    pub fmt: &'a [CommandSpec],
    pub core_cargo: &'a [CommandSpec],
    pub xtask_cargo: &'a [CommandSpec],
    pub release: &'a [CommandSpec],
}

#[cfg(test)]
pub(crate) fn all_required_checks() -> Vec<&'static CommandSpec> {
    FMT_CHECKS
        .iter()
        .chain(CORE_CARGO_CHECKS.iter())
        .chain(XTASK_CARGO_CHECKS.iter())
        .chain(RELEASE_CHECKS.iter())
        .collect()
}

fn all_group_checks(groups: &CheckGroups<'_>) -> Vec<CommandSpec> {
    groups
        .fmt
        .iter()
        .chain(groups.core_cargo.iter())
        .chain(groups.xtask_cargo.iter())
        .chain(groups.release.iter())
        .cloned()
        .collect()
}

#[cfg(test)]
pub fn verify_fast(
    runner: Arc<dyn CommandRunner>,
    repo_root: &Path,
    native_checks: &[NativeCheck],
    groups: &CheckGroups<'_>,
    reporter: &dyn ProgressReporter,
) -> Result<VerifyReport> {
    verify_fast_with_options(runner, repo_root, native_checks, groups, reporter, true)
}

pub fn verify_fast_with_options(
    runner: Arc<dyn CommandRunner>,
    repo_root: &Path,
    native_checks: &[NativeCheck],
    groups: &CheckGroups<'_>,
    reporter: &dyn ProgressReporter,
    run_native_scan: bool,
) -> Result<VerifyReport> {
    let all_checks = all_group_checks(groups);
    let _ = runner.prepare_for_verify(
        repo_root,
        native_checks,
        &all_checks,
        crate::io::scanner::NATIVE_SCAN_CHECKS,
    );
    report_autogenerated_markers(repo_root, reporter);
    if let Some(report) = run_native_checks(&runner, repo_root, native_checks, reporter)? {
        return Ok(report);
    }
    let cancel = Arc::new(CancellationState::new());
    let lane_results = LaneResults::new();
    let cargo_report = run_parallel_lanes(
        Arc::clone(&runner),
        repo_root,
        reporter,
        groups,
        &cancel,
        &lane_results,
        run_native_scan,
    )?;
    select_first_failure(cargo_report, &lane_results)
}

fn select_first_failure(
    cargo_report: VerifyReport,
    lane_results: &LaneResults,
) -> Result<VerifyReport> {
    if let Some(report) = drain_lane_order(&[lane_results.scan(), lane_results.fmt()])? {
        return Ok(report);
    }
    check_remaining_lanes(cargo_report, lane_results)
}

fn check_remaining_lanes(
    cargo_report: VerifyReport,
    lane_results: &LaneResults,
) -> Result<VerifyReport> {
    if cargo_report.exit == VerifyExitCode::Failure {
        return Ok(cargo_report);
    }
    drain_secondary_lanes(lane_results)
}

fn drain_secondary_lanes(lane_results: &LaneResults) -> Result<VerifyReport> {
    if let Some(report) = drain_lane_order(&[lane_results.xtask(), lane_results.release()])? {
        return Ok(report);
    }
    Ok(VerifyReport {
        exit: VerifyExitCode::Success,
        failure: None,
    })
}

fn report_autogenerated_markers(repo_root: &Path, reporter: &dyn ProgressReporter) {
    if let Ok(marked_files) = collect_autogenerated_marked_files(repo_root) {
        for path in marked_files {
            reporter.info(&format_autogenerated_marker_message(&path));
        }
    }
}

fn run_native_checks(
    runner: &Arc<dyn CommandRunner>,
    repo_root: &Path,
    native_checks: &[NativeCheck],
    reporter: &dyn ProgressReporter,
) -> Result<Option<VerifyReport>> {
    native_checks
        .iter()
        .find_map(|check| run_single_native_check(runner, repo_root, check, reporter).transpose())
        .transpose()
}

fn run_single_native_check(
    runner: &Arc<dyn CommandRunner>,
    repo_root: &Path,
    check: &NativeCheck,
    reporter: &dyn ProgressReporter,
) -> Result<Option<VerifyReport>> {
    let start = Instant::now();
    reporter.check_started(check.name);
    let result = runner
        .run_native_check(repo_root, check)
        .with_context(|| format!("run native check {}", check.name))?;
    let elapsed = start.elapsed();
    if result.status != CheckStatus::Pass {
        reporter.check_failed(check.name, elapsed, result.status);
        return Ok(Some(VerifyReport {
            exit: VerifyExitCode::Failure,
            failure: Some(CheckFailure {
                name: check.name,
                status: result.status,
                exit_code: -1,
                stdout: result.message,
                stderr: String::new(),
            }),
        }));
    }
    reporter.check_passed(check.name, elapsed);
    Ok(None)
}

fn spawn_native_scan_lane<'scope, 'env>(
    scope: &'scope std::thread::Scope<'scope, 'env>,
    run_native_scan: bool,
    runner: Arc<dyn CommandRunner>,
    repo_root: &'scope Path,
    reporter: &'scope dyn ProgressReporter,
    cancel: &'scope CancellationState,
    result_slot: &'scope Mutex<Option<Result<VerifyReport>>>,
) {
    if !run_native_scan {
        return;
    }
    scope.spawn(move || {
        run_native_scan_lane_body(runner, repo_root, reporter, cancel, result_slot);
    });
}

fn run_native_scan_lane_body(
    runner: Arc<dyn CommandRunner>,
    repo_root: &Path,
    reporter: &dyn ProgressReporter,
    cancel: &CancellationState,
    result_slot: &Mutex<Option<Result<VerifyReport>>>,
) {
    let lane_start = Instant::now();
    if cancel.should_cancel(FailurePriority::Scan) {
        return;
    }
    execute_native_scan(runner, repo_root, reporter, cancel, result_slot, lane_start);
}

fn execute_native_scan(
    runner: Arc<dyn CommandRunner>,
    repo_root: &Path,
    reporter: &dyn ProgressReporter,
    cancel: &CancellationState,
    result_slot: &Mutex<Option<Result<VerifyReport>>>,
    lane_start: Instant,
) {
    let scan_start = Instant::now();
    reporter.check_started("native-scan");
    let run_result = runner
        .run_native_scan(
            repo_root,
            crate::io::scanner::NATIVE_SCAN_CHECKS,
            &|name, info| reporter.check_progress(name, info),
        )
        .with_context(|| "run native-scan".to_string());
    let scan_elapsed = scan_start.elapsed();
    handle_scan_result(
        reporter,
        cancel,
        result_slot,
        run_result,
        scan_elapsed,
        lane_start,
    );
}

fn handle_scan_result(
    reporter: &dyn ProgressReporter,
    cancel: &CancellationState,
    result_slot: &Mutex<Option<Result<VerifyReport>>>,
    run_result: Result<Vec<crate::io::scanner::NativeScanCheckResult>>,
    scan_elapsed: std::time::Duration,
    lane_start: Instant,
) {
    match run_result {
        Ok(scan_results) => handle_scan_results(
            reporter,
            cancel,
            result_slot,
            &scan_results,
            scan_elapsed,
            lane_start,
        ),
        Err(error) => finish_scan_with_error(
            reporter,
            cancel,
            result_slot,
            scan_elapsed,
            lane_start,
            &error,
        ),
    }
}

fn handle_scan_results(
    reporter: &dyn ProgressReporter,
    cancel: &CancellationState,
    result_slot: &Mutex<Option<Result<VerifyReport>>>,
    scan_results: &[crate::io::scanner::NativeScanCheckResult],
    scan_elapsed: std::time::Duration,
    lane_start: Instant,
) {
    if let Some(failed) = scan_results.iter().find(|r| !r.passed) {
        finish_scan_with_failure(
            reporter,
            cancel,
            result_slot,
            failed,
            scan_elapsed,
            lane_start,
        );
        return;
    }
    reporter.check_passed("native-scan", scan_elapsed);
    *result_slot.lock().unwrap() = Some(Ok(VerifyReport {
        exit: VerifyExitCode::Success,
        failure: None,
    }));
    reporter.lane_finished("native-scan", lane_start.elapsed());
}

fn finish_scan_with_error(
    reporter: &dyn ProgressReporter,
    cancel: &CancellationState,
    result_slot: &Mutex<Option<Result<VerifyReport>>>,
    scan_elapsed: std::time::Duration,
    lane_start: Instant,
    error: &anyhow::Error,
) {
    reporter.check_failed("native-scan", scan_elapsed, CheckStatus::Error);
    cancel.record_failure(FailurePriority::Scan);
    *result_slot.lock().unwrap() = Some(Ok(VerifyReport {
        exit: VerifyExitCode::Failure,
        failure: Some(CheckFailure {
            name: "native-scan",
            status: CheckStatus::Error,
            exit_code: 1,
            stdout: String::new(),
            stderr: format!("{error:#}"),
        }),
    }));
    reporter.lane_finished("native-scan", lane_start.elapsed());
}

fn finish_scan_with_failure(
    reporter: &dyn ProgressReporter,
    cancel: &CancellationState,
    result_slot: &Mutex<Option<Result<VerifyReport>>>,
    result: &crate::io::scanner::NativeScanCheckResult,
    scan_elapsed: std::time::Duration,
    lane_start: Instant,
) {
    reporter.check_failed(result.check_name, scan_elapsed, CheckStatus::Error);
    let output = format_scan_failure_output(result);
    cancel.record_failure(FailurePriority::Scan);
    *result_slot.lock().unwrap() = Some(Ok(VerifyReport {
        exit: VerifyExitCode::Failure,
        failure: Some(CheckFailure {
            name: result.check_name,
            status: CheckStatus::Error,
            exit_code: 1,
            stdout: output,
            stderr: String::new(),
        }),
    }));
    reporter.lane_finished("native-scan", lane_start.elapsed());
}

fn format_scan_failure_output(result: &crate::io::scanner::NativeScanCheckResult) -> String {
    if result.check_name == "forbidden-allow-expect-scan" {
        format!(
            "{}\n\n{}",
            FORBIDDEN_ALLOW_EXPECT_POLICY,
            format_scan_violations(&result.violations)
        )
    } else {
        format_scan_violations(&result.violations)
    }
}

struct GroupLaneContext<'scope> {
    reporter: &'scope dyn ProgressReporter,
    cancel: &'scope CancellationState,
    result: &'scope Mutex<Option<Result<VerifyReport>>>,
}

struct LaneSpec<'scope> {
    specs: &'scope [CommandSpec],
    lane_name: &'static str,
    priority: FailurePriority,
}

impl<'scope> GroupLaneContext<'scope> {
    fn new(
        reporter: &'scope dyn ProgressReporter,
        cancel: &'scope CancellationState,
        result: &'scope Mutex<Option<Result<VerifyReport>>>,
    ) -> Self {
        Self {
            reporter,
            cancel,
            result,
        }
    }
}

impl<'scope> LaneSpec<'scope> {
    fn new(
        specs: &'scope [CommandSpec],
        lane_name: &'static str,
        priority: FailurePriority,
    ) -> Self {
        Self {
            specs,
            lane_name,
            priority,
        }
    }
}

struct LaneResults {
    scan: Mutex<Option<Result<VerifyReport>>>,
    fmt: Mutex<Option<Result<VerifyReport>>>,
    xtask: Mutex<Option<Result<VerifyReport>>>,
    release: Mutex<Option<Result<VerifyReport>>>,
}

impl LaneResults {
    fn new() -> Self {
        Self {
            scan: Mutex::new(None),
            fmt: Mutex::new(None),
            xtask: Mutex::new(None),
            release: Mutex::new(None),
        }
    }

    fn scan(&self) -> &Mutex<Option<Result<VerifyReport>>> {
        &self.scan
    }

    fn fmt(&self) -> &Mutex<Option<Result<VerifyReport>>> {
        &self.fmt
    }

    fn xtask(&self) -> &Mutex<Option<Result<VerifyReport>>> {
        &self.xtask
    }

    fn release(&self) -> &Mutex<Option<Result<VerifyReport>>> {
        &self.release
    }
}

fn spawn_group_lane<'scope, 'env>(
    scope: &'scope std::thread::Scope<'scope, 'env>,
    runner: Arc<dyn CommandRunner>,
    context: GroupLaneContext<'scope>,
    lane: LaneSpec<'scope>,
) {
    if lane.specs.is_empty() {
        return;
    }

    scope.spawn(move || {
        let lane_start = Instant::now();
        let report = run_checks_cancellable(
            runner.as_ref(),
            lane.specs,
            context.reporter,
            context.cancel,
            lane.priority,
        );
        *context.result.lock().unwrap() = Some(report);
        context
            .reporter
            .lane_finished(lane.lane_name, lane_start.elapsed());
    });
}

fn run_parallel_lanes(
    runner: Arc<dyn CommandRunner>,
    repo_root: &Path,
    reporter: &dyn ProgressReporter,
    groups: &CheckGroups<'_>,
    cancel: &CancellationState,
    lane_results: &LaneResults,
    run_native_scan: bool,
) -> Result<VerifyReport> {
    let cargo_report = std::thread::scope(|s| {
        spawn_native_scan_lane(
            s,
            run_native_scan,
            Arc::clone(&runner),
            repo_root,
            reporter,
            cancel,
            lane_results.scan(),
        );

        spawn_group_lane(
            s,
            Arc::clone(&runner),
            GroupLaneContext::new(reporter, cancel, lane_results.fmt()),
            LaneSpec::new(groups.fmt, "fmt", FailurePriority::Fmt),
        );

        spawn_group_lane(
            s,
            Arc::clone(&runner),
            GroupLaneContext::new(reporter, cancel, lane_results.xtask()),
            LaneSpec::new(
                groups.xtask_cargo,
                "xtask-cargo",
                FailurePriority::XtaskCargo,
            ),
        );

        spawn_group_lane(
            s,
            Arc::clone(&runner),
            GroupLaneContext::new(reporter, cancel, lane_results.release()),
            LaneSpec::new(groups.release, "release", FailurePriority::Release),
        );

        let lane_start = Instant::now();
        let cargo_report = run_checks_cancellable(
            runner.as_ref(),
            groups.core_cargo,
            reporter,
            cancel,
            FailurePriority::CoreCargo,
        );
        reporter.lane_finished("core-cargo", lane_start.elapsed());
        cargo_report
    });

    cargo_report
}

fn drain_lane_order(
    lanes: &[&Mutex<Option<Result<VerifyReport>>>],
) -> Result<Option<VerifyReport>> {
    for lane in lanes {
        if let Some(report) = drain_lane_failure(lane)? {
            return Ok(Some(report));
        }
    }

    Ok(None)
}

fn drain_lane_failure(
    result: &Mutex<Option<Result<VerifyReport>>>,
) -> Result<Option<VerifyReport>> {
    if let Some(value) = result.lock().unwrap().take() {
        let report = value?;
        if report.exit == VerifyExitCode::Failure {
            return Ok(Some(report));
        }
    }

    Ok(None)
}

pub const FMT_CHECKS: &[CommandSpec] = &[CommandSpec {
    name: "fmt-check",
    program: "cargo",
    args: &["fmt", "--all", "--check"],
    success_exit_codes: &[0],
    extra_env: &[],
}];

pub const CORE_CARGO_CHECKS: &[CommandSpec] = &[
    CommandSpec {
        name: "clippy-core",
        program: "cargo",
        args: &[
            "clippy",
            "-p",
            "ralph-workflow",
            "-p",
            "ralph-workflow-tests",
            "-p",
            "test-helpers",
            "--all-targets",
            "--all-features",
            "--",
            "-D",
            "warnings",
        ],
        success_exit_codes: &[0],
        extra_env: &[],
    },
    CommandSpec {
        name: "test-ralph-workflow-lib",
        program: "cargo",
        args: &[
            "nextest",
            "run",
            "-p",
            "ralph-workflow",
            "--lib",
            "--all-features",
        ],
        success_exit_codes: &[0],
        extra_env: &[],
    },
    CommandSpec {
        name: "test-integration",
        program: "cargo",
        args: &[
            "nextest",
            "run",
            "-p",
            "ralph-workflow-tests",
            "--test",
            "integration_tests_agent_core",
            "--test",
            "integration_tests_reducer",
            "--test",
            "integration_tests_workflow",
        ],
        success_exit_codes: &[0],
        extra_env: &[],
    },
];

pub const XTASK_CARGO_CHECKS: &[CommandSpec] = &[
    CommandSpec {
        name: "clippy-xtask",
        program: "cargo",
        args: &[
            "clippy",
            "-p",
            "xtask",
            "--all-targets",
            "--",
            "-D",
            "warnings",
        ],
        success_exit_codes: &[0],
        extra_env: &[("CARGO_TARGET_DIR", "target/xtask-parallel-verify")],
    },
    CommandSpec {
        name: "test-xtask",
        program: "cargo",
        args: &["nextest", "run", "-p", "xtask"],
        success_exit_codes: &[0],
        extra_env: &[("CARGO_TARGET_DIR", "target/xtask-parallel-verify")],
    },
];

pub const DYLINT_CHECKS: &[CommandSpec] = &[CommandSpec {
    name: "dylint",
    program: "make",
    args: &["dylint"],
    success_exit_codes: &[0],
    extra_env: &[
        ("DYLINT_DRIVER_PATH", "target/dylint-driver"),
        ("CARGO_TARGET_DIR", "target/release-parallel-verify"),
    ],
}];

pub const RELEASE_BUILD_CHECKS: &[CommandSpec] = &[CommandSpec {
    name: "release-build",
    program: "cargo",
    args: &["build", "--profile", "release-verify"],
    success_exit_codes: &[0],
    extra_env: &[("CARGO_TARGET_DIR", "target/release-parallel-verify")],
}];

#[cfg(test)]
pub const RELEASE_CHECKS: &[CommandSpec] = &[
    CommandSpec {
        name: "release-build",
        program: "cargo",
        args: &["build", "--profile", "release-verify"],
        success_exit_codes: &[0],
        extra_env: &[("CARGO_TARGET_DIR", "target/release-parallel-verify")],
    },
    CommandSpec {
        name: "dylint",
        program: "make",
        args: &["dylint"],
        success_exit_codes: &[0],
        extra_env: &[
            ("DYLINT_DRIVER_PATH", "target/dylint-driver"),
            ("CARGO_TARGET_DIR", "target/release-parallel-verify"),
        ],
    },
];
