use std::fs;
use std::path::{Path, PathBuf};

use super::types::NativeCheck;

pub const AUTOGENERATED_REASON_TOKEN: &str = "reason = \"autogenerated\"";
const AUTOGENERATED_REASON_TOKEN_COMPACT: &str = "reason=\"autogenerated\"";
const AUTOGENERATED_SCAN_DIRS: &[&str] = &["ralph-workflow/src", "lints/ralph_lints/src"];

pub(crate) fn detect_autogenerated_reason(source: &str) -> Option<&'static str> {
    source.lines().take(20).find_map(|line| {
        let compact: String = line.chars().filter(|ch| !ch.is_whitespace()).collect();
        compact
            .contains(AUTOGENERATED_REASON_TOKEN_COMPACT)
            .then_some(AUTOGENERATED_REASON_TOKEN)
    })
}

pub(crate) fn format_autogenerated_marker_message(path: &Path) -> String {
    format!("{} has been marked as autogenerated", path.display())
}

pub(crate) fn collect_rs_files(root: &Path, files: &mut Vec<PathBuf>) -> std::io::Result<()> {
    if !root.exists() {
        return Ok(());
    }

    collect_rs_files_in_dir(root, files)
}

fn collect_rs_files_in_dir(dir: &Path, files: &mut Vec<PathBuf>) -> std::io::Result<()> {
    for entry in fs::read_dir(dir)? {
        handle_dir_entry(entry?, files)?;
    }

    Ok(())
}

fn handle_dir_entry(entry: fs::DirEntry, files: &mut Vec<PathBuf>) -> std::io::Result<()> {
    let path = entry.path();
    let file_type = entry.file_type()?;
    match (
        file_type.is_dir(),
        file_type.is_file() && is_rust_source(&path),
    ) {
        (true, _) => collect_rs_files_in_dir(&path, files),
        (_, true) => {
            files.push(path);
            Ok(())
        }
        _ => Ok(()),
    }
}

fn is_rust_source(path: &Path) -> bool {
    path.extension().is_some_and(|ext| ext == "rs")
}

pub(crate) fn collect_autogenerated_marked_files(
    repo_root: &Path,
) -> std::io::Result<Vec<PathBuf>> {
    let candidates = gather_autogenerated_candidates(repo_root)?;

    let mut marked_files = Vec::new();
    for path in candidates {
        if file_is_autogenerated(&path)? {
            marked_files.push(relative_path_or_self(repo_root, &path));
        }
    }

    Ok(marked_files)
}

fn gather_autogenerated_candidates(repo_root: &Path) -> std::io::Result<Vec<PathBuf>> {
    let mut rust_files = Vec::new();
    for dir in AUTOGENERATED_SCAN_DIRS {
        collect_rs_files(&repo_root.join(dir), &mut rust_files)?;
    }

    rust_files.sort();
    Ok(rust_files)
}

fn file_is_autogenerated(path: &Path) -> std::io::Result<bool> {
    let source = fs::read_to_string(path)?;
    Ok(detect_autogenerated_reason(&source).is_some())
}

fn relative_path_or_self(repo_root: &Path, path: &Path) -> PathBuf {
    path.strip_prefix(repo_root)
        .map_or_else(|_| path.to_path_buf(), PathBuf::from)
}

pub const NATIVE_REQUIRED_CHECKS: &[NativeCheck] = &[
    NativeCheck {
        name: "compliance-timeout-wrapper",
        run: crate::boundary::compliance::check_timeout_wrappers,
    },
    NativeCheck {
        name: "audit-no-shell-scripts",
        run: crate::boundary::compliance::check_no_shell_scripts,
    },
    NativeCheck {
        name: "tailwind4-removed-angular-classes",
        run: crate::boundary::compliance::check_tailwind4_removed_angular_classes,
    },
    NativeCheck {
        name: "test-utils-items-used-in-tests",
        run: crate::boundary::test_utils_usage::check_test_utils_items_used_in_tests,
    },
    NativeCheck {
        name: "dependency-isolation-mcp-server",
        run: crate::boundary::checks::check_mcp_server_no_ralph_workflow_dependency,
    },
];
