#![feature(rustc_private)]
// DO NOT CHANGE LINTING POLICY UNLESS THE USER SPECIFICALLY ASKS TO, YOU MUST REFACTOR EVEN IF IT TAKES YOU LONG TIME
#![deny(warnings)]
#![deny(clippy::all)]
#![forbid(unsafe_code)]
#![deny(
    // No explicit iterator loops when a more idiomatic form exists
    clippy::explicit_iter_loop,
    clippy::explicit_into_iter_loop,
    // No implicit crashes / partial operations
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::panic_in_result_fn,
    clippy::indexing_slicing,
    // No casual side effects / debugging leftovers
    clippy::print_stdout,
    clippy::print_stderr,
    clippy::dbg_macro,
    // Treat unchecked arithmetic as suspicious
    clippy::arithmetic_side_effects,
    // Push toward combinators instead of hand-written control flow
    clippy::manual_map,
    clippy::manual_filter,
    clippy::manual_find,
    clippy::manual_filter_map,
    clippy::manual_flatten,
    clippy::needless_collect
)]

extern crate rustc_ast;
extern crate rustc_span;

use rustc_lint::{EarlyContext, EarlyLintPass, LintContext};
use rustc_span::{FileName, SourceFile, Span};
use std::collections::HashSet;
use std::path::{Component, Path};
use std::sync::Arc;

const AUTOGENERATED_REASON_TOKEN: &str = "reason=\"autogenerated\"";

dylint_linting::impl_early_lint! {
    /// ### What it does
    ///
    /// Checks for files that exceed recommended line limits:
    /// - 500+ lines: Consider refactoring
    /// - 1000+ lines: Must refactor
    ///
    /// ### Why is this bad?
    ///
    /// Large files are harder to navigate, understand, and maintain.
    /// They often indicate that a module has too many responsibilities
    /// and should be split into smaller, more focused modules.
    ///
    /// See CODE_STYLE.md for design principles.
    ///
    /// ### Example
    ///
    /// A file with 1500 lines of code should be refactored into
    /// multiple smaller modules.
    pub FILE_TOO_LONG,
    Deny,
    "file exceeds recommended line limits",
    FileTooLong::default()
}

/// Threshold for "consider refactoring" warning
const CONSIDER_REFACTOR_LINES: usize = 500;

/// Threshold for "must refactor" warning
const MUST_REFACTOR_LINES: usize = 1000;

/// Custom lint pass that tracks which files we've already warned about
#[derive(Default)]
pub struct FileTooLong {
    warned_files: HashSet<String>,
}

fn path_contains_component(path: &Path, target: &str) -> bool {
    path.components().any(|component| match component {
        Component::Normal(name) => name == target,
        _ => false,
    })
}

fn current_workspace_root() -> Option<std::path::PathBuf> {
    std::env::current_dir()
        .ok()
        .and_then(|path| path.canonicalize().ok().or(Some(path)))
}

fn canonicalize_for_filter(path: &Path) -> std::path::PathBuf {
    path.canonicalize().unwrap_or_else(|_| path.to_path_buf())
}

/// Check if the file is a local project file (not stdlib, cargo registry, or external)
fn is_local_project_file(name: &FileName) -> bool {
    match name {
        FileName::Real(real_name) => {
            if let Some(path) = real_name.local_path() {
                let canonical_path = canonicalize_for_filter(path);

                if path_contains_component(&canonical_path, ".cargo")
                    || path_contains_component(&canonical_path, ".rustup")
                    || path_contains_component(&canonical_path, "target")
                {
                    return false;
                }

                let Some(workspace_root) = current_workspace_root() else {
                    return false;
                };

                canonical_path.starts_with(workspace_root)
            } else {
                false
            }
        }
        _ => false,
    }
}

/// Get the display path for a file
fn get_file_display_path(name: &FileName) -> Option<String> {
    match name {
        FileName::Real(real_name) => real_name.local_path().map(|p| p.display().to_string()),
        _ => None,
    }
}

fn file_marked_as_autogenerated(source: &str) -> bool {
    source.lines().take(20).any(|line| {
        let compact: String = line.chars().filter(|ch| !ch.is_whitespace()).collect();
        compact.contains(AUTOGENERATED_REASON_TOKEN)
    })
}

impl FileTooLong {
    fn check_source_file(&mut self, cx: &EarlyContext<'_>, source_file: &Arc<SourceFile>) {
        // Skip non-local files (stdlib, external crates, cargo registry)
        if !is_local_project_file(&source_file.name) {
            return;
        }

        // Get file path for display and deduplication
        let Some(file_path) = get_file_display_path(&source_file.name) else {
            return;
        };

        if source_file
            .src
            .as_ref()
            .is_some_and(|source| file_marked_as_autogenerated(source.as_ref()))
        {
            return;
        }

        // Only warn once per file
        if self.warned_files.contains(&file_path) {
            return;
        }

        let total_lines = source_file.count_lines();

        // Check thresholds (check higher threshold first for clearer messaging)
        // Semantics are inclusive: 500+ warns, 1000+ is MUST refactor.
        if total_lines >= MUST_REFACTOR_LINES {
            self.warned_files.insert(file_path.clone());

            let warning_span = Span::with_root_ctxt(source_file.start_pos, source_file.start_pos);

            cx.span_lint(FILE_TOO_LONG, warning_span, |diag| {
                diag.primary_message(format!(
                    "file has {total_lines} lines (>= {MUST_REFACTOR_LINES}) - MUST refactor"
                ));
                diag.help("this file is too large and MUST be split into smaller modules");
                diag.note("see CODE_STYLE.md for design principles on module organization");
            });
        } else if total_lines >= CONSIDER_REFACTOR_LINES {
            self.warned_files.insert(file_path.clone());

            let warning_span = Span::with_root_ctxt(source_file.start_pos, source_file.start_pos);

            cx.span_lint(FILE_TOO_LONG, warning_span, |diag| {
                diag.primary_message(format!(
                    "file has {total_lines} lines (>= {CONSIDER_REFACTOR_LINES}) - consider refactoring"
                ));
                diag.help("consider splitting this file into smaller, more focused modules");
                diag.note("see CODE_STYLE.md for design principles on module organization");
            });
        }
    }
}

impl EarlyLintPass for FileTooLong {
    fn check_crate(&mut self, cx: &EarlyContext<'_>, _krate: &rustc_ast::Crate) {
        let source_map = cx.sess().source_map();

        // Iterate over all source files in the source map
        source_map.files().iter().for_each(|source_file| {
            self.check_source_file(cx, source_file);
        });
    }
}

#[cfg(test)]
mod tests {
    use super::file_marked_as_autogenerated;
    use super::path_contains_component;
    use std::path::Path;

    #[test]
    fn detects_cargo_component_in_registry_paths() {
        assert!(path_contains_component(
            Path::new(
                "/tmp/ralph-cargo-home/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anyhow-1.0.102/src/lib.rs"
            ),
            ".cargo"
        ));
    }

    #[test]
    fn detects_rustup_component_in_toolchain_paths() {
        assert!(path_contains_component(
            Path::new(
                "/tmp/ralph-rustup-home/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/lib.rs"
            ),
            ".rustup"
        ));
    }

    #[test]
    fn detects_reason_field_marking_file_as_autogenerated() {
        let source = "// reason = \"autogenerated\"\nfn generated() {}\n";

        assert!(
            file_marked_as_autogenerated(source),
            "reason=autogenerated marker must exempt generated files from file_too_long"
        );
    }

    #[test]
    fn ui() {
        dylint_testing::ui_test(env!("CARGO_PKG_NAME"), "ui");
    }
}
