[mypy]
strict = true
python_version = 3.14
plugins = pydantic.mypy

[mypy-typer.*]
ignore_missing_imports = true

[mypy-rich.*]
ignore_missing_imports = true

[mypy-rich_click.*]
ignore_missing_imports = true

[mypy-gitpython.*]
ignore_missing_imports = true

[mypy-tqdm.*]
ignore_missing_imports = true

[mypy-watchdog.*]
ignore_missing_imports = true

[mypy-tomli.*]
ignore_missing_imports = true

[mypy-tomli_w.*]
ignore_missing_imports = true
