from __future__ import annotations

import signal

from ralph.interrupt.controller import (
    INTERRUPT_EXIT_CODE,
    InterruptController,
    install_force_kill_handler,
)

_DEAD_PID = 202
_FORCE_KILL_PID = 101
_PID_ALPHA = 101
_PID_BETA = 202
_EXPECTED_FORCE_KILL_EVENT_COUNT = 2


def test_begin_interrupt_records_graceful_shutdown_and_optional_cleanup() -> None:
    events: list[tuple[str, object]] = []

    controller = InterruptController(
        shutdown_all=lambda grace_period_s: events.append(("shutdown", grace_period_s)),
        record_interrupt=lambda: events.append(("record", None)),
        stop_connectivity=lambda: events.append(("stop", None)),
        hard_exit=lambda code: events.append(("exit", code)),
    )

    controller.begin_interrupt(grace_period_s=2.5)

    assert events == [("record", None), ("stop", None), ("shutdown", 2.5)]


def test_force_interrupt_records_shutdown_and_optional_cleanup() -> None:
    """AC-11 contract: kill events are generated by the
    ``shutdown_all(grace=0)`` closure, NOT by a per-pgid loop on
    the controller side. The ``bridge_pgids`` parameter is
    accepted for backward compatibility (per step 10's deprecation
    shim) but is no longer iterated by the controller. The
    closure captures ``bridge_pgids`` explicitly so the executor
    cannot get lost in a generator expression.

    Pin: ``len(kill_events) == 2`` (one per PGID).
    """
    bridge_pgids = [_PID_ALPHA, _PID_BETA]
    events: list[tuple[str, object]] = []

    def _shutdown_all(grace_period_s: float) -> None:
        events.append(("shutdown", grace_period_s))
        if grace_period_s == 0:
            events.extend(
                [("kill", (pgid, 9)) for pgid in bridge_pgids]  # 9 == SIGKILL
            )

    controller = InterruptController(
        shutdown_all=_shutdown_all,
        record_interrupt=lambda: events.append(("record", None)),
        stop_connectivity=lambda: events.append(("stop", None)),
        hard_exit=lambda code: events.append(("exit", code)),
    )

    controller.force_interrupt(bridge_pgids=bridge_pgids)

    assert events[0] == ("record", None)
    assert ("stop", None) in events
    assert ("shutdown", 0) in events
    kill_events = [event for event in events if event[0] == "kill"]
    assert len(kill_events) == _EXPECTED_FORCE_KILL_EVENT_COUNT
    assert ("exit", INTERRUPT_EXIT_CODE) not in events


def test_force_interrupt_suppresses_cleanup_failures() -> None:
    shutdown_calls: list[float] = []

    def bad_stop() -> None:
        raise RuntimeError("stop failed")

    def shutdown_all(grace_period_s: float) -> None:
        shutdown_calls.append(grace_period_s)

    controller = InterruptController(
        shutdown_all=shutdown_all,
        record_interrupt=lambda: None,
        stop_connectivity=bad_stop,
        hard_exit=lambda code: None,
    )

    controller.force_interrupt(bridge_pgids=[_FORCE_KILL_PID, _DEAD_PID])

    assert shutdown_calls == [0]


def test_force_exit_uses_interrupt_exit_code_and_force_kill() -> None:
    """AC-11 contract: ``force_exit`` calls ``shutdown_all(0)`` (which
    SIGKILLs every active record via the closure) and then
    ``hard_exit(INTERRUPT_EXIT_CODE)``. The kill event is generated
    by the closure, not the per-pgid loop."""
    bridge_pgids = [_FORCE_KILL_PID]
    events: list[tuple[str, object]] = []

    def _shutdown_all(grace_period_s: float) -> None:
        events.append(("shutdown", grace_period_s))
        if grace_period_s == 0:
            events.extend([("kill", (pgid, 9)) for pgid in bridge_pgids])

    controller = InterruptController(
        shutdown_all=_shutdown_all,
        record_interrupt=lambda: events.append(("record", None)),
        hard_exit=lambda code: events.append(("exit", code)),
    )

    controller.force_exit(bridge_pgids=bridge_pgids)

    assert ("shutdown", 0) in events
    assert any(event[0] == "kill" and event[1][0] == _FORCE_KILL_PID for event in events)
    assert events[-1] == ("exit", INTERRUPT_EXIT_CODE)


def test_install_force_kill_handler_restores_previous_handler() -> None:
    calls: list[tuple[str, object]] = []
    previous = object()

    def fake_getsignal(signum: int) -> object:
        calls.append(("get", signum))
        return previous

    def fake_signal(signum: int, handler: object) -> object:
        calls.append(("set", (signum, handler)))
        return handler

    restore = install_force_kill_handler(
        lambda: calls.append(("force", None)),
        signal_getter=fake_getsignal,
        signal_setter=fake_signal,
    )
    handler = calls[1][1][1]
    handler(2, None)
    restore()

    assert calls[0] == ("get", 2)
    assert calls[2] == ("force", None)
    assert calls[3] == ("set", (2, previous))


# ---------------------------------------------------------------------------
# wt-024 Step 4: SIGTERM handler mirrors SIGINT
# ---------------------------------------------------------------------------


def test_install_force_kill_handler_supports_sigterm() -> None:
    """wt-024 Step 4: install_force_kill_handler must accept ``signum`` and install SIGTERM too."""
    calls: list[tuple[str, object]] = []
    previous_int = object()
    previous_term = object()

    def fake_getsignal(signum: int) -> object:
        calls.append(("get", signum))
        if signum == signal.SIGINT:
            return previous_int
        return previous_term

    def fake_signal(signum: int, handler: object) -> object:
        calls.append(("set", (signum, handler)))
        return handler

    restore = install_force_kill_handler(
        lambda: calls.append(("force", None)),
        signal_getter=fake_getsignal,
        signal_setter=fake_signal,
        signum=signal.SIGTERM,
    )
    handler = calls[1][1][1]
    handler(signal.SIGTERM, None)
    restore()

    assert calls[0] == ("get", signal.SIGTERM)
    assert calls[2] == ("force", None)
    assert calls[3] == ("set", (signal.SIGTERM, previous_term))


def test_install_force_kill_handler_default_signum_is_sigint() -> None:
    """Backward-compat: omitting ``signum`` preserves the existing SIGINT behavior."""
    calls: list[tuple[str, object]] = []
    previous = object()

    def fake_getsignal(signum: int) -> object:
        calls.append(("get", signum))
        return previous

    def fake_signal(signum: int, handler: object) -> object:
        calls.append(("set", (signum, handler)))
        return handler

    restore = install_force_kill_handler(
        lambda: None,
        signal_getter=fake_getsignal,
        signal_setter=fake_signal,
    )
    restore()

    assert calls[0] == ("get", signal.SIGINT)
    assert calls[1] == ("set", (signal.SIGINT, calls[1][1][1]))
    assert calls[2] == ("set", (signal.SIGINT, previous))
