"""Phase 4: tests for ``format='metadata'`` in
``handle_read_image`` and ``handle_read_media``.

The tests run against an in-memory PNG file so the path stays
black-box; the PNG signature parser is exercised through the public
handler so a regression in either parser or the envelope builder
fails the test.

For ``handle_read_media`` we exercise the workspace file path
because it is the most common call site. The replay-handle metadata
path is covered indirectly by the inline-mode tests already in
``test_tool_workspace_handle_read_media.py``; the inline contract is
unchanged so a regression would be caught there.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import cast

import pytest

from ralph.mcp.multimodal.artifacts import ResourceReferenceContent
from ralph.mcp.multimodal.capabilities import MultimodalModelIdentity
from ralph.mcp.tools.coordination import ImageContent, ToolContent
from ralph.mcp.tools.workspace._media_handlers import (
    handle_read_image,
    handle_read_media,
)
from ralph.workspace.fs import FsWorkspace
from tests.mock_session import MockSession
from tests.mock_session_with_manifest import MockSessionWithManifest

MEDIA_READ_CAPABILITY = "media.read"

pytestmark = [pytest.mark.timeout_seconds(5), pytest.mark.subprocess_e2e]


# Minimal valid PNG: 1x1 transparent pixel. Generated bytes (not a
# file fixture) so the test is hermetic.
_PNG_BYTES = (
    b"\x89PNG\r\n\x1a\n"  # PNG signature
    b"\x00\x00\x00\rIHDR"
    b"\x00\x00\x00\x01\x00\x00\x00\x01"  # width=1, height=1
    b"\x08\x06\x00\x00\x00"  # bit depth, color type, etc.
    b"\x1f\x15\xc4\x89"  # CRC for IHDR (correct CRC not required for parser)
    b"\x00\x00\x00\nIDAT"
    b"\x78\x9c\x62\x00\x01\x00\x00\x05\x00\x01"
    b"\x0d\x0a\x2d\xb4"
    b"\x00\x00\x00\x00IEND\xaeB`\x82"
)


def _write_png(tmp_path: Path, name: str = "tiny.png") -> Path:
    """Write a small PNG file and return its path."""
    file_path = tmp_path / name
    file_path.write_bytes(_PNG_BYTES)
    return file_path


class TestReadImageMetadata:
    def test_read_image_metadata_returns_bounded_envelope(self, tmp_path: Path) -> None:
        _write_png(tmp_path)
        ws = FsWorkspace(tmp_path)

        result = handle_read_image(
            MockSession(MEDIA_READ_CAPABILITY),
            ws,
            {"path": "tiny.png", "format": "metadata"},
        )

        assert result.is_error is False
        envelope = json.loads(cast("ToolContent", result.content[0]).text)
        assert envelope["format"] == "metadata"
        assert envelope["media_kind"] == "image"
        assert envelope["mime_type"] == "image/png"
        assert envelope["size_bytes"] == len(_PNG_BYTES)
        assert envelope["sha256"] == hashlib.sha256(_PNG_BYTES).hexdigest()
        assert envelope["width"] == 1
        assert envelope["height"] == 1
        # ``handle_read_image`` never persists an artifact, so
        # ``resource_handle`` is always ``None``.
        assert envelope["resource_handle"] is None
        assert envelope["inline_only"] is True
        assert envelope["truncated"] is False
        assert envelope["bytes_out"] > 0
        # No inline image content block.
        assert not any(isinstance(c, ImageContent) for c in result.content)

    def test_read_image_inline_default_unchanged(self, tmp_path: Path) -> None:
        """``format='inline'`` (default) preserves the legacy image block."""
        _write_png(tmp_path)
        ws = FsWorkspace(tmp_path)

        result = handle_read_image(
            MockSessionWithManifest(
                MEDIA_READ_CAPABILITY,
                model_identity=MultimodalModelIdentity(provider="claude"),
            ),
            ws,
            {"path": "tiny.png"},
        )

        assert result.is_error is False
        assert any(isinstance(c, ImageContent) for c in result.content)

    def test_read_image_metadata_invalid_format_raises(self, tmp_path: Path) -> None:
        _write_png(tmp_path)
        ws = FsWorkspace(tmp_path)

        from ralph.mcp.tools.coordination import InvalidParamsError

        with pytest.raises(InvalidParamsError, match="Invalid format"):
            handle_read_image(
                MockSession(MEDIA_READ_CAPABILITY),
                ws,
                {"path": "tiny.png", "format": "bogus"},
            )


class TestReadMediaMetadata:
    def test_read_media_metadata_returns_bounded_envelope_for_pdf(
        self, tmp_path: Path
    ) -> None:
        pdf_path = tmp_path / "report.pdf"
        pdf_path.write_bytes(b"%PDF-1.4 fake pdf content")
        ws = FsWorkspace(tmp_path)

        # Use a session with an UNKNOWN provider so the
        # ``RESOURCE_REFERENCE_REPLAY`` delivery is taken. The
        # known-provider ``claude`` model uses ``TYPED_BLOCK`` for
        # PDFs (which does not register a Ralph-owned artifact), so
        # an unknown provider is the simplest way to exercise the
        # resource-reference delivery.
        result = handle_read_media(
            MockSessionWithManifest(
                MEDIA_READ_CAPABILITY,
                model_identity=MultimodalModelIdentity(provider="unknown"),
            ),
            ws,
            {"path": "report.pdf", "format": "metadata"},
        )

        assert result.is_error is False
        envelope = json.loads(cast("ToolContent", result.content[0]).text)
        assert envelope["format"] == "metadata"
        assert envelope["media_kind"] == "pdf"
        assert envelope["mime_type"] == "application/pdf"
        assert envelope["size_bytes"] == len(b"%PDF-1.4 fake pdf content")
        assert envelope["sha256"] == hashlib.sha256(
            b"%PDF-1.4 fake pdf content"
        ).hexdigest()
        # Resource-reference delivery registers a Ralph-owned artifact,
        # so the handle is non-null.
        assert envelope["resource_handle"] is not None
        assert str(envelope["resource_handle"]).startswith("ralph://media/")
        assert envelope["inline_only"] is False
        assert envelope["bytes_out"] > 0
        # No inline media content block.
        assert not any(isinstance(c, ResourceReferenceContent) for c in result.content)

    def test_read_media_metadata_returns_bounded_envelope_for_image(
        self, tmp_path: Path
    ) -> None:
        _write_png(tmp_path, name="shot.png")
        ws = FsWorkspace(tmp_path)

        result = handle_read_media(
            MockSessionWithManifest(
                MEDIA_READ_CAPABILITY,
                model_identity=MultimodalModelIdentity(provider="claude"),
            ),
            ws,
            {"path": "shot.png", "format": "metadata"},
        )

        assert result.is_error is False
        envelope = json.loads(cast("ToolContent", result.content[0]).text)
        assert envelope["format"] == "metadata"
        assert envelope["media_kind"] == "image"
        assert envelope["mime_type"] == "image/png"
        assert envelope["size_bytes"] == len(_PNG_BYTES)
        assert envelope["sha256"] == hashlib.sha256(_PNG_BYTES).hexdigest()
        # Image deliveries do not register a Ralph-owned artifact
        # (the inline path is taken), so ``resource_handle`` is None.
        assert envelope["resource_handle"] is None
        assert envelope["inline_only"] is True
        assert envelope["width"] == 1
        assert envelope["height"] == 1

    def test_read_media_inline_default_unchanged_for_pdf(
        self, tmp_path: Path
    ) -> None:
        """``format='inline'`` (default) preserves the legacy block shape.

        Claude delivers PDFs as a typed ``PdfContent`` block (not
        ``ResourceReferenceContent``); the unknown-provider default
        falls through to ``RESOURCE_REFERENCE_REPLAY``. Either shape
        is acceptable; what matters is that ``format='inline'`` still
        emits the legacy block instead of the new metadata envelope.
        """
        pdf_path = tmp_path / "report.pdf"
        pdf_path.write_bytes(b"%PDF-1.4 fake pdf content")
        ws = FsWorkspace(tmp_path)

        result = handle_read_media(
            MockSessionWithManifest(
                MEDIA_READ_CAPABILITY,
                model_identity=MultimodalModelIdentity(provider="unknown"),
            ),
            ws,
            {"path": "report.pdf"},
        )

        assert result.is_error is False
        # Legacy shape: either a ResourceReferenceContent block
        # (resource_reference_replay delivery) or a typed block
        # (PdfContent). The new metadata envelope is a ToolContent
        # text block whose JSON carries ``format='metadata'``;
        # ``format='inline'`` MUST NOT produce that envelope.
        legacy_blocks = [
            c for c in result.content
            if isinstance(c, ResourceReferenceContent)
            or c.__class__.__name__ in {"PdfContent", "AudioContent",
                                         "VideoContent", "DocumentContent",
                                         "ImageContent"}
        ]
        assert legacy_blocks, (
            f"inline mode must emit a legacy typed/resource-reference "
            f"block; got {result.content!r}"
        )
        for c in result.content:
            text = getattr(c, "text", None)
            if text is not None:
                # The metadata envelope always carries ``format=metadata``
                # in the JSON text content.
                assert '"format": "metadata"' not in text, (
                    f"inline mode must not emit the metadata envelope: {text!r}"
                )

    def test_read_media_metadata_invalid_format_raises(self, tmp_path: Path) -> None:
        pdf_path = tmp_path / "report.pdf"
        pdf_path.write_bytes(b"%PDF-1.4 fake pdf content")
        ws = FsWorkspace(tmp_path)

        from ralph.mcp.tools.coordination import InvalidParamsError

        with pytest.raises(InvalidParamsError, match="Invalid format"):
            handle_read_media(
                MockSessionWithManifest(
                    MEDIA_READ_CAPABILITY,
                    model_identity=MultimodalModelIdentity(provider="claude"),
                ),
                ws,
                {"path": "report.pdf", "format": "bogus"},
            )
