"""Black-box tests for ``ralph.skills._auto_commit.commit_skill_updates``.

The auto-commit helper is wired into ``_sync_shipped_skills_on_pipeline_run``
so that any drift in the project-scope skill tree is committed
deterministically before the development agent runs. This test file pins:

* AC-01 deterministic subject / body format (``chore(skills): sync baseline bundle``,
  ``Auto-generated by Ralph skill sync``, ``Changed skills:`` with one
  bullet per changed skill name).
* no-commit when the skill tree is clean.
* no-commit on a non-git workspace.
* AC-04 selective staging -- only the FIVE skill-root paths are staged,
  any dirty file outside the roots is filtered out defensively.
* AC-01 subject-is-deterministic across two consecutive runs (different
  bodies, identical subjects).
* git-lock recovery via ``_run_git_operation_with_stale_lock_recovery``
  is transparent -- a stale ``.git/index.lock`` does not break the
  auto-commit.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING
from unittest.mock import MagicMock

import pytest
from git import Actor, Repo

from ralph.skills._agent_paths import _SKILL_ROOT_PREFIXES
from ralph.skills._auto_commit import (
    SKILL_AUTO_COMMIT_SUBJECT,
    commit_skill_updates,
)

if TYPE_CHECKING:
    from pathlib import Path


@pytest.fixture
def fake_create_commit() -> MagicMock:
    """A stub create_commit that records its arguments and returns a fake SHA."""
    fake_sha = "f" * 40
    return MagicMock(return_value=fake_sha)


def _track_initial_commit(repo_root: Path) -> None:
    """Make an initial empty commit so HEAD exists for subsequent diffing."""
    repo = Repo(repo_root)
    try:
        repo.config_writer().set_value("user", "name", "Test Author").release()
        repo.config_writer().set_value("user", "email", "test@example.com").release()
        actor = Actor("Test Author", "test@example.com")
        repo.index.commit("initial", author=actor, committer=actor)
    finally:
        repo.close()


@pytest.mark.timeout_seconds(5)
def test_auto_commit_subject_is_deterministic(
    tmp_path: Path, fake_create_commit: MagicMock
) -> None:
    """AC-01: subject is the literal ``chore(skills): sync baseline bundle``."""
    Repo.init(tmp_path)
    _track_initial_commit(tmp_path)

    # Make one skill dirty
    skill_dir = tmp_path / ".opencode" / "skills" / "brainstorming"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_dir.joinpath("SKILL.md").write_text("# brainstorm\n", encoding="utf-8")

    stage_spy = MagicMock()
    commit_skill_updates(tmp_path, fake_create_commit, stage_fn=stage_spy)

    fake_create_commit.assert_called_once()
    message = fake_create_commit.call_args.args[1]
    subject = message.splitlines()[0]
    assert subject == SKILL_AUTO_COMMIT_SUBJECT, (
        f"Subject must be exactly {SKILL_AUTO_COMMIT_SUBJECT!r}; got: {subject!r}"
    )
    assert SKILL_AUTO_COMMIT_SUBJECT == "chore(skills): sync baseline bundle"


@pytest.mark.timeout_seconds(5)
def test_auto_commit_body_lists_changed_skills(
    tmp_path: Path, fake_create_commit: MagicMock
) -> None:
    """AC-01: body lists every changed skill name under the ``Changed skills:`` header."""
    Repo.init(tmp_path)
    _track_initial_commit(tmp_path)

    for name in ("brainstorming", "coding-standards"):
        skill_dir = tmp_path / ".opencode" / "skills" / name
        skill_dir.mkdir(parents=True, exist_ok=True)
        skill_dir.joinpath("SKILL.md").write_text(f"# {name}\n", encoding="utf-8")

    stage_spy = MagicMock()
    commit_skill_updates(tmp_path, fake_create_commit, stage_fn=stage_spy)

    message = fake_create_commit.call_args.args[1]
    assert "Auto-generated by Ralph skill sync" in message, (
        f"Body must contain the auto-gen header; got: {message!r}"
    )
    assert "Changed skills:" in message, (
        f"Body must contain the 'Changed skills:' section; got: {message!r}"
    )
    assert "- brainstorming" in message, (
        f"Body must list 'brainstorming'; got: {message!r}"
    )
    assert "- coding-standards" in message, (
        f"Body must list 'coding-standards'; got: {message!r}"
    )


@pytest.mark.timeout_seconds(5)
def test_auto_commit_no_commit_when_skill_tree_clean(
    tmp_path: Path, fake_create_commit: MagicMock
) -> None:
    """A clean skill tree: helper returns None and create_commit is NOT called."""
    Repo.init(tmp_path)
    _track_initial_commit(tmp_path)

    # No skill-tree mutations
    result = commit_skill_updates(tmp_path, fake_create_commit)

    assert result is None, f"Clean skill tree must return None; got: {result!r}"
    fake_create_commit.assert_not_called()


@pytest.mark.timeout_seconds(5)
def test_auto_commit_no_commit_on_non_git_workspace(
    tmp_path: Path, fake_create_commit: MagicMock
) -> None:
    """A non-git workspace: helper returns None and create_commit is NOT called."""
    # tmp_path is NOT a git repo (no Repo.init)
    assert not (tmp_path / ".git").exists()

    result = commit_skill_updates(tmp_path, fake_create_commit)

    assert result is None, f"Non-git workspace must return None; got: {result!r}"
    fake_create_commit.assert_not_called()


@pytest.mark.timeout_seconds(5)
def test_auto_commit_stages_only_skill_roots(
    tmp_path: Path, fake_create_commit: MagicMock
) -> None:
    """AC-04: stage_fn is called with paths ONLY under the FIVE skill roots.

    Pre-stages one dirty file under ``.opencode/skills/`` (allowed) and
    one dirty file outside (``src/main.go``, NOT allowed). The defensive
    filter must drop the outside path even if ``git status`` reported it.
    """
    Repo.init(tmp_path)
    _track_initial_commit(tmp_path)

    skill_dir = tmp_path / ".opencode" / "skills" / "brainstorming"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_dir.joinpath("SKILL.md").write_text("# brainstorm\n", encoding="utf-8")

    # Dirty file OUTSIDE the skill roots -- the defensive filter must drop it
    src_dir = tmp_path / "src"
    src_dir.mkdir(parents=True, exist_ok=True)
    src_dir.joinpath("main.go").write_text("package main\n", encoding="utf-8")

    stage_spy = MagicMock()
    commit_skill_updates(tmp_path, fake_create_commit, stage_fn=stage_spy)

    stage_spy.assert_called_once()
    staged_paths = stage_spy.call_args.args[1]
    for path in staged_paths:
        assert any(path.startswith(prefix) for prefix in _SKILL_ROOT_PREFIXES), (
            f"Staged path {path!r} must be under one of the FIVE skill roots"
        )
    assert "src/main.go" not in staged_paths, (
        f"Dirty file outside skill roots MUST be filtered out; got: {staged_paths!r}"
    )
    assert ".opencode/skills/brainstorming/SKILL.md" in staged_paths, (
        f"Skill-root path MUST be staged; got: {staged_paths!r}"
    )


@pytest.mark.timeout_seconds(5)
def test_auto_commit_subject_is_deterministic_across_two_runs(
    tmp_path: Path, fake_create_commit: MagicMock
) -> None:
    """AC-01: subject is identical across consecutive runs even when bodies differ."""
    Repo.init(tmp_path)
    _track_initial_commit(tmp_path)

    # First run: stage one skill
    skill_a = tmp_path / ".opencode" / "skills" / "brainstorming"
    skill_a.mkdir(parents=True, exist_ok=True)
    skill_a.joinpath("SKILL.md").write_text("# brainstorm\n", encoding="utf-8")
    stage_spy = MagicMock()
    commit_skill_updates(tmp_path, fake_create_commit, stage_fn=stage_spy)
    first_message = fake_create_commit.call_args.args[1]

    # Second run: stage a different skill (simulate a different set of dirty paths)
    skill_b = tmp_path / ".opencode" / "skills" / "coding-standards"
    skill_b.mkdir(parents=True, exist_ok=True)
    skill_b.joinpath("SKILL.md").write_text("# coding-standards\n", encoding="utf-8")
    commit_skill_updates(tmp_path, fake_create_commit, stage_fn=MagicMock())
    second_message = fake_create_commit.call_args.args[1]

    first_subject = first_message.splitlines()[0]
    second_subject = second_message.splitlines()[0]
    assert first_subject == second_subject, (
        f"Subject must be IDENTICAL across consecutive runs; "
        f"got: {first_subject!r} vs {second_subject!r}"
    )
    assert first_subject == SKILL_AUTO_COMMIT_SUBJECT
    assert first_message != second_message, (
        "Bodies must differ when changed skill names differ"
    )


@pytest.mark.timeout_seconds(5)
def test_auto_commit_fails_closed_on_git_lock(
    tmp_path: Path, fake_create_commit: MagicMock
) -> None:
    """AC-04: a stale .git/index.lock must NOT crash the auto-commit; helper returns None.

    Pins the fail-closed contract: ``_run_git_operation_with_stale_lock_recovery``
    handles the lock transparently, and any persistent GitCommandError is
    caught by the outer guard and returns None so a broken git state
    cannot block the pipeline.
    """
    Repo.init(tmp_path)
    _track_initial_commit(tmp_path)
    skill_dir = tmp_path / ".opencode" / "skills" / "brainstorming"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_dir.joinpath("SKILL.md").write_text("# brainstorm\n", encoding="utf-8")

    # Create a stale index.lock that points at a non-existent PID so the
    # recovery helper unlinks it. This simulates a concurrent crash that
    # left a stale lock behind.
    lock_path = tmp_path / ".git" / "index.lock"
    lock_path.write_text("", encoding="utf-8")

    stage_spy = MagicMock()
    result = commit_skill_updates(tmp_path, fake_create_commit, stage_fn=stage_spy)

    # Either the lock was recovered transparently (commit succeeded with
    # fake_create_commit called) OR the helper returned None fail-closed.
    # The contract is: never raise, never block the pipeline.
    if result is None:
        # Fail-closed branch -- the helper detected unrecoverable git state
        fake_create_commit.assert_not_called()
    else:
        # Lock was recovered -- commit succeeded
        fake_create_commit.assert_called_once()
        assert result == "f" * 40


@pytest.mark.timeout_seconds(5)
def test_auto_commit_subject_constant_is_pinned() -> None:
    """The subject literal is the literal-string contract pinned by the audit."""
    assert SKILL_AUTO_COMMIT_SUBJECT == "chore(skills): sync baseline bundle", (
        f"SKILL_AUTO_COMMIT_SUBJECT must be the literal 'chore(skills): sync baseline bundle'; "
        f"got: {SKILL_AUTO_COMMIT_SUBJECT!r}"
    )


@pytest.mark.timeout_seconds(5)
def test_auto_commit_handles_multiple_skill_roots(
    tmp_path: Path, fake_create_commit: MagicMock
) -> None:
    """All FIVE skill roots are scanned; skills in any root get committed."""
    Repo.init(tmp_path)
    _track_initial_commit(tmp_path)

    # Pre-create skills under THREE different roots
    for prefix in (".opencode/skills/", ".agents/skills/", ".claude/skills/"):
        skill_dir = tmp_path / prefix / "brainstorming"
        skill_dir.mkdir(parents=True, exist_ok=True)
        skill_dir.joinpath("SKILL.md").write_text("# brainstorm\n", encoding="utf-8")

    stage_spy = MagicMock()
    commit_skill_updates(tmp_path, fake_create_commit, stage_fn=stage_spy)

    staged_paths = stage_spy.call_args.args[1]
    assert any(p.startswith(".opencode/skills/") for p in staged_paths)
    assert any(p.startswith(".agents/skills/") for p in staged_paths)
    assert any(p.startswith(".claude/skills/") for p in staged_paths)
    message = fake_create_commit.call_args.args[1]
    assert "- brainstorming" in message


@pytest.mark.timeout_seconds(5)
def test_auto_commit_fails_closed_on_oserror(
    tmp_path: Path,
) -> None:
    """Outer guard catches OSError and returns None -- pipeline is never broken."""
    Repo.init(tmp_path)
    _track_initial_commit(tmp_path)

    def _raising_create_commit(
        _repo_root: Path, _message: str
    ) -> str:
        raise OSError("simulated filesystem failure")

    # No dirty skill-tree mutations; the helper returns None BEFORE
    # calling create_commit, so this test is a no-op smoke check. To
    # actually exercise the OSError branch we need a dirty tree plus a
    # raising create_commit.
    skill_dir = tmp_path / ".opencode" / "skills" / "brainstorming"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_dir.joinpath("SKILL.md").write_text("# brainstorm\n", encoding="utf-8")

    result = commit_skill_updates(tmp_path, _raising_create_commit, stage_fn=MagicMock())

    assert result is None, (
        f"OSError in create_commit must be caught and return None; got: {result!r}"
    )


@pytest.mark.timeout_seconds(10)
def test_auto_commit_body_is_deterministic_across_shuffled_input_orderings(
    tmp_path: Path, fake_create_commit: MagicMock
) -> None:
    """wt-025 / AC-01: the auto-commit message is byte-for-byte deterministic.

    Pins the deterministic-shape contract against NON-DETERMINISTIC input
    orderings. The auto-commit helper receives dirty paths from
    ``git status --porcelain``, which can return paths in filesystem /
    write / traversal order depending on the OS. The body must be stable
    regardless of which order the helper iterates the dirty paths in.

    Drives ``commit_skill_updates`` THREE TIMES against the SAME three
    dirty skill files under THREE different FIVE-root prefixes (one per
    run) by varying the directory-write order. After every run the test
    asserts:

      (a) the subject (line 0) is the literal
          ``chore(skills): sync baseline bundle`` (the audit-pinned subject),

      (b) the body matches the EXACT regex (assembled from the multi-line
          constant in the test body):
          ``^Auto-generated by Ralph skill sync`` then ``\\n\\n`` then
          ``Changed skills:`` then ``\\n`` then the sorted list of
          ``- <skill-name>`` lines ending with
          ``- test-driven-development$`` with ``re.MULTILINE`` --
          the ``Changed skills:`` list is sorted ascending, deduped,
          contains EVERY changed skill name exactly once, and the
          message has no extra trailing free-form text,

      (c) the body lines after ``Changed skills:`` are exactly
          ``['- brainstorming', '- coding-standards', '- test-driven-development']``
          (in that order) regardless of the input ordering,

      (d) the ``stage_fn`` spy received the SECOND positional arg in
          SORTED ASCENDING order in every run -- proves the production
          helper sorts before staging, not after.

    This is a NEW regression test added by the wt-025 plan. It locks the
    ``_SKILL_ROOT_PREFIXES``-sorted iteration in
    ``commit_skill_updates`` and the ``_extract_skill_names`` dedup
    against any future refactor that reintroduces the prior
    iteration-ordering bug (where the body listed changed skills in
    ``git status`` output order, which is platform-dependent).
    """
    # The exact body shape we expect after every run. The audit pins the
    # subject literal; this test pins the body shape.
    expected_body_regex = (
        r"^Auto-generated by Ralph skill sync\n\n"
        r"Changed skills:\n"
        r"- brainstorming\n"
        r"- coding-standards\n"
        r"- test-driven-development$"
    )
    expected_skill_lines = [
        "- brainstorming",
        "- coding-standards",
        "- test-driven-development",
    ]

    # Three skill files, each under a DIFFERENT FIVE-root prefix so the
    # cross-prefix sort inside ``commit_skill_updates`` is exercised.
    cross_root_paths = (
        ("coding-standards", ".opencode/skills/"),
        ("brainstorming", ".claude/skills/"),
        ("test-driven-development", ".agents/skills/"),
    )

    # Three orderings: identity, reversed, and a stride that interchanges
    # the middle element. Each must produce the SAME deterministic message.
    name_orderings = (
        ("coding-standards", "brainstorming", "test-driven-development"),
        ("test-driven-development", "coding-standards", "brainstorming"),
        ("brainstorming", "test-driven-development", "coding-standards"),
    )

    captured_messages: list[str] = []
    captured_staged: list[list[str]] = []

    for ordering in name_orderings:
        # Wipe the fake_create_commit spy between runs so each run's
        # call_args.args[1] reflects the LATEST message only.
        fake_create_commit.reset_mock()

        Repo.init(tmp_path)
        _track_initial_commit(tmp_path)

        # Write the three skill files in the run-specific order.
        name_to_dir = dict(cross_root_paths)
        for skill_name in ordering:
            prefix = name_to_dir[skill_name]
            skill_dir = tmp_path / prefix / skill_name
            skill_dir.mkdir(parents=True, exist_ok=True)
            skill_dir.joinpath("SKILL.md").write_text(
                f"# {skill_name}\n", encoding="utf-8"
            )

        stage_spy = MagicMock()
        commit_skill_updates(tmp_path, fake_create_commit, stage_fn=stage_spy)

        # Record the message arg passed to create_commit for this run.
        assert fake_create_commit.call_count == 1, (
            f"Expected exactly one commit per run; got: {fake_create_commit.call_count}"
        )
        message = fake_create_commit.call_args.args[1]
        captured_messages.append(message)

        # Record the paths passed to stage_fn for this run -- they MUST be
        # sorted ascending regardless of write order.
        assert stage_spy.call_count == 1, (
            f"Expected exactly one stage_fn call per run; got: {stage_spy.call_count}"
        )
        captured_staged.append(list(stage_spy.call_args.args[1]))

    # (a) Subject literal -- identical across all three runs.
    subjects = [msg.splitlines()[0] for msg in captured_messages]
    for idx, subject in enumerate(subjects):
        assert subject == SKILL_AUTO_COMMIT_SUBJECT, (
            f"Run {idx}: subject must be {SKILL_AUTO_COMMIT_SUBJECT!r}; got: {subject!r}"
        )

    # (b) Body regex match -- identical across all three runs.
    body_pattern = re.compile(expected_body_regex, re.MULTILINE)
    for idx, message in enumerate(captured_messages):
        # The full message is ``subject\n\nbody``; line 0 is the subject
        # and line 1 is the blank separator. Drop both before validating
        # the body shape.
        body = "\n".join(message.splitlines()[2:])
        assert body_pattern.match(body), (
            f"Run {idx}: body must match the deterministic-shape regex; got: {body!r}"
        )

    # (c) Body lines after 'Changed skills:' are exactly the sorted, deduped
    # list -- in that order, regardless of the write ordering of the
    # underlying files. This is the canonical AC-01 contract.
    for idx, message in enumerate(captured_messages):
        lines = message.splitlines()
        changed_idx = lines.index("Changed skills:")
        skill_lines = lines[changed_idx + 1 :]
        assert skill_lines == expected_skill_lines, (
            f"Run {idx}: changed-skills lines must be the sorted, deduped "
            f"list {expected_skill_lines!r}; got: {skill_lines!r}"
        )

    # (d) The stage_fn spy received the SECOND positional arg (the file
    # list) in SORTED ASCENDING order in every run -- proves the
    # production helper sorts before staging. If a future refactor
    # forgets the sort, this assertion catches it.
    for idx, staged in enumerate(captured_staged):
        assert staged == sorted(staged), (
            f"Run {idx}: stage_fn MUST receive a sorted path list; "
            f"got: {staged!r}"
        )

    # (e) Across all three runs, the messages are byte-identical -- the
    # strongest possible deterministic-shape pin.
    assert len(set(captured_messages)) == 1, (
        f"All three runs MUST produce byte-identical messages; "
        f"got distinct: {captured_messages!r}"
    )
