from __future__ import annotations

import configparser
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
WORKSPACE_ROOT = REPO_ROOT.parent
MYPY_INI_PATH = REPO_ROOT / "mypy.ini"
PYPROJECT_PATH = REPO_ROOT / "pyproject.toml"
EXTERNAL_LIBRARY_POLICY_REF = "docs/agents/type-ignore-policy.md#external-library"
AUTOGENERATED_POLICY_REF = "docs/agents/type-ignore-policy.md#autogenerated-code"


def _load_mypy_config() -> configparser.ConfigParser:
    parser = configparser.ConfigParser()
    parser.read(MYPY_INI_PATH, encoding="utf-8")
    return parser


def _load_pyproject() -> dict[str, object]:
    return tomllib.loads(PYPROJECT_PATH.read_text(encoding="utf-8"))


def test_mypy_requires_error_codes_on_type_ignores() -> None:
    parser = _load_mypy_config()
    enabled_codes = {
        code.strip()
        for code in parser["mypy"].get("enable_error_code", "").split(",")
        if code.strip()
    }

    assert "ignore-without-code" in enabled_codes



def test_ruff_enforces_blanket_type_ignore_rule() -> None:
    pyproject = _load_pyproject()
    tool = pyproject["tool"]
    assert isinstance(tool, dict)
    ruff = tool["ruff"]
    assert isinstance(ruff, dict)
    lint = ruff["lint"]
    assert isinstance(lint, dict)
    select = lint["select"]
    assert isinstance(select, list)

    assert "PGH" in select



def test_repo_contains_no_blanket_type_ignore_comments() -> None:
    offenders: list[str] = []
    marker = "# type:" + " ignore"
    coded_marker = marker + "["

    for path in REPO_ROOT.rglob("*.py"):
        if ".venv" in path.parts:
            continue
        for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            if marker not in line:
                continue
            if coded_marker in line:
                continue
            offenders.append(f"{path.relative_to(REPO_ROOT)}:{line_number}")

    assert offenders == []



def test_external_library_policy_document_exists() -> None:
    policy_path = WORKSPACE_ROOT / EXTERNAL_LIBRARY_POLICY_REF.split("#", maxsplit=1)[0]
    assert policy_path.is_file(), f"Missing policy document: {EXTERNAL_LIBRARY_POLICY_REF}"



def test_repo_requires_allowed_reason_on_coded_type_ignores() -> None:
    offenders: list[str] = []
    marker = "# type:" + " ignore["
    external_library_suffix = (
        "# reason: external library has no type support, see "
        f"{EXTERNAL_LIBRARY_POLICY_REF}"
    )
    autogenerated_suffix = (
        "# reason: autogenerated code has no type support, see "
        f"{AUTOGENERATED_POLICY_REF}"
    )

    for path in REPO_ROOT.rglob("*.py"):
        if ".venv" in path.parts:
            continue
        for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            if marker not in line:
                continue
            stripped = line.rstrip()
            if stripped.endswith(external_library_suffix) or stripped.endswith(
                autogenerated_suffix
            ):
                continue
            offenders.append(f"{path.relative_to(REPO_ROOT)}:{line_number}")

    policy_message = (
        "Every '# type:' + ' ignore[...]' must end with either '# reason: external library has no "
        "type support, see docs/agents/type-ignore-policy.md#external-library' or '# reason: "
        "autogenerated code has no type support, see "
        "docs/agents/type-ignore-policy.md#autogenerated-code'."
    )

    assert offenders == [], policy_message
