from __future__ import annotations

import configparser
import tomllib
from functools import cache
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
WORKSPACE_ROOT = REPO_ROOT.parent
MYPY_INI_PATH = REPO_ROOT / "mypy.ini"
PYPROJECT_PATH = REPO_ROOT / "pyproject.toml"
EXTERNAL_LIBRARY_POLICY_REF = "docs/agents/type-ignore-policy.md#external-library"
AUTOGENERATED_POLICY_REF = "docs/agents/type-ignore-policy.md#autogenerated-code"


def _load_mypy_config() -> configparser.ConfigParser:
    parser = configparser.ConfigParser()
    parser.read(MYPY_INI_PATH, encoding="utf-8")
    return parser


def _load_pyproject() -> dict[str, object]:
    return tomllib.loads(PYPROJECT_PATH.read_text(encoding="utf-8"))


@cache
def _repo_python_files() -> tuple[Path, ...]:
    return tuple(path for path in REPO_ROOT.rglob("*.py") if ".venv" not in path.parts)


@cache
def _repo_type_ignore_lines() -> tuple[tuple[str, int, str], ...]:
    matches: list[tuple[str, int, str]] = []
    marker = "# type:"
    for path in _repo_python_files():
        text = path.read_text(encoding="utf-8")
        if marker not in text:
            continue
        rel_path = str(path.relative_to(REPO_ROOT))
        for line_number, line in enumerate(text.splitlines(), start=1):
            if marker in line:
                matches.append((rel_path, line_number, line.rstrip()))
    return tuple(matches)


def test_mypy_requires_error_codes_on_type_ignores() -> None:
    parser = _load_mypy_config()
    enabled_codes = {
        code.strip()
        for code in parser["mypy"].get("enable_error_code", "").split(",")
        if code.strip()
    }

    assert "ignore-without-code" in enabled_codes



def test_ruff_enforces_blanket_type_ignore_rule() -> None:
    pyproject = _load_pyproject()
    tool = pyproject["tool"]
    assert isinstance(tool, dict)
    ruff = tool["ruff"]
    assert isinstance(ruff, dict)
    lint = ruff["lint"]
    assert isinstance(lint, dict)
    select = lint["select"]
    assert isinstance(select, list)

    assert "PGH" in select



@pytest.mark.timeout_seconds(5)
def test_repo_type_ignore_comments_follow_policy() -> None:
    blanket_offenders: list[str] = []
    reason_offenders: list[str] = []
    blanket_marker = "# type:" + " ignore"
    coded_marker = blanket_marker + "["
    coded_marker_prefix = "# type:" + " ignore["
    external_library_suffix = (
        "# reason: external library has no type support, see "
        f"{EXTERNAL_LIBRARY_POLICY_REF}"
    )
    autogenerated_suffix = (
        "# reason: autogenerated code has no type support, see "
        f"{AUTOGENERATED_POLICY_REF}"
    )

    for rel_path, line_number, line in _repo_type_ignore_lines():
        if blanket_marker in line and coded_marker not in line:
            blanket_offenders.append(f"{rel_path}:{line_number}")
        if coded_marker_prefix not in line:
            continue
        if line.endswith(external_library_suffix) or line.endswith(autogenerated_suffix):
            continue
        reason_offenders.append(f"{rel_path}:{line_number}")

    assert blanket_offenders == []

    policy_message = (
        "Every '# type:' + ' ignore[...]' must end with either '# reason: external library has no "
        "type support, see docs/agents/type-ignore-policy.md#external-library' or '# reason: "
        "autogenerated code has no type support, see "
        "docs/agents/type-ignore-policy.md#autogenerated-code'."
    )
    assert reason_offenders == [], policy_message



def test_external_library_policy_document_exists() -> None:
    policy_path = WORKSPACE_ROOT / EXTERNAL_LIBRARY_POLICY_REF.split("#", maxsplit=1)[0]
    assert policy_path.is_file(), f"Missing policy document: {EXTERNAL_LIBRARY_POLICY_REF}"



