"""AST-based policy tests enforcing the maintained structural rules.

Scoped to ralph/, tests/, and named repo-root standalone files (excludes .venv, tmp/, docs/).
"""

from __future__ import annotations

import functools
import io
import tokenize
import tomllib
from pathlib import Path

import pytest

pytestmark = pytest.mark.timeout_seconds(5)

REPO_ROOT = Path(__file__).resolve().parents[1]
RALPH_DIR = REPO_ROOT / "ralph"
TESTS_DIR = REPO_ROOT / "tests"
MYPY_INI_PATH = REPO_ROOT / "mypy.ini"
PYPROJECT_PATH = REPO_ROOT / "pyproject.toml"
_REPO_ROOT_STANDALONE_FILES: tuple[Path, ...] = (REPO_ROOT / "conftest.py",)

_SKIP_DIRS = frozenset({"__pycache__", ".venv", "tmp"})
_MAX_FILE_LINES = 1_000


@functools.cache
def _all_py_files(base: Path) -> tuple[Path, ...]:
    result = []
    for path in base.rglob("*.py"):
        if any(part in _SKIP_DIRS for part in path.parts):
            continue
        result.append(path)
    return tuple(sorted(result))


@functools.cache
def _read_path(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _scan_class_structure(src: str) -> list[str]:
    """Return names of top-level classes at module level.

    TYPE_CHECKING-guarded classes are indented, so a token-level scan is enough
    for this policy check and is much cheaper than parsing every file into an AST.
    """
    classes: list[str] = []
    indent_level = 0
    pending_class_name = False

    try:
        tokens = tokenize.generate_tokens(io.StringIO(src).readline)
        for tok_type, tok_string, *_rest in tokens:
            if tok_type == tokenize.INDENT:
                indent_level += 1
                continue
            if tok_type == tokenize.DEDENT:
                indent_level = max(0, indent_level - 1)
                continue
            if indent_level == 0 and tok_type == tokenize.NAME and tok_string == "class":
                pending_class_name = True
                continue
            if pending_class_name and tok_type == tokenize.NAME:
                classes.append(tok_string)
                pending_class_name = False
                continue
            if pending_class_name and tok_type not in {
                tokenize.NL,
                tokenize.NEWLINE,
                tokenize.COMMENT,
            }:
                pending_class_name = False
    except tokenize.TokenError:
        return []

    return classes


@functools.cache
def _scan_bypass_comments(src: str, lines: tuple[str, ...]) -> tuple[tuple[int, str], ...]:
    bypass_comments: list[tuple[int, str]] = []
    try:
        tokens = tokenize.generate_tokens(io.StringIO(src).readline)
        for tok_type, tok_string, (start_row, _), *_rest in tokens:
            if tok_type != tokenize.COMMENT:
                continue
            if _TYPE_IGNORE_MARKER not in tok_string and _NOQA_MARKER not in tok_string:
                continue
            line = lines[start_row - 1].rstrip() if start_row - 1 < len(lines) else ""
            if line.endswith(_EXTERNAL_LIBRARY_SUFFIX) or line.endswith(_AUTOGENERATED_SUFFIX):
                continue
            bypass_comments.append((start_row, line))
    except tokenize.TokenError:
        return ()
    return tuple(bypass_comments)


@functools.cache
def _scan_private_imports(lines: tuple[str, ...]) -> tuple[tuple[str, list[str]], ...]:
    results: list[tuple[str, list[str]]] = []
    for raw_line in lines:
        stripped = raw_line.strip()
        if not stripped.startswith("from ralph") or " import " not in stripped:
            continue
        module_part, imported_part = stripped.split(" import ", 1)
        module = module_part[len("from ") :].strip()
        if not module.startswith("ralph"):
            continue
        private_names: list[str] = []
        for item in imported_part.split(","):
            name = item.split("#", 1)[0].strip()
            if not name:
                continue
            if " as " in name:
                name = name.split(" as ", 1)[0].strip()
            if name.startswith("_"):
                private_names.append(name)
        if private_names:
            results.append((module, private_names))
    return tuple(results)


@functools.cache
def _policy_scan(path: Path) -> dict[str, object]:
    """Return a cached structural report for a single Python file."""
    src = _read_path(path)
    lines = tuple(src.splitlines())
    bypass_comments = _scan_bypass_comments(src, lines)
    private_ralph_imports = _scan_private_imports(lines)
    return {
        "private_ralph_imports": private_ralph_imports,
        "bypass_comments": bypass_comments,
    }


def _count_lines(path: Path) -> int:
    return len(_read_path(path).splitlines())


def _top_level_classes(path: Path) -> list[str]:
    """Return names of top-level classes at module level."""
    return _scan_class_structure(_read_path(path))


def _private_ralph_imports(path: Path) -> list[tuple[str, list[str]]]:
    """Return (module, [private_names]) for imports of private names from ralph.*."""
    return list(_policy_scan(path)["private_ralph_imports"])


_TYPE_IGNORE_MARKER = "# type:" + " ignore"
_NOQA_MARKER = "# no" + "qa"
_EXTERNAL_LIBRARY_SUFFIX = (
    "# reason: external library has no type support, see "
    "docs/agents/type-ignore-policy.md#external-library"
)
_AUTOGENERATED_SUFFIX = (
    "# reason: autogenerated code has no type support, see "
    "docs/agents/type-ignore-policy.md#autogenerated-code"
)


def _has_bypass_comment(path: Path) -> list[tuple[int, str]]:
    """Return (lineno, line) for lines with actual type-check or lint-bypass comments.

    Uses tokenize to distinguish comment tokens from string literals.
    Policy-compliant type-suppression comments (ending with a valid reason suffix) are excluded.
    """
    src = _read_path(path)
    results = []
    try:
        tokens = tokenize.generate_tokens(io.StringIO(src).readline)
        for tok_type, tok_string, (start_row, _), _, _ in tokens:
            if tok_type == tokenize.COMMENT and (
                _TYPE_IGNORE_MARKER in tok_string or _NOQA_MARKER in tok_string
            ):
                lines = src.splitlines()
                line = lines[start_row - 1] if start_row <= len(lines) else ""
                stripped = line.rstrip()
                # Policy-compliant type ignores with reason suffixes are allowed
                if stripped.endswith(_EXTERNAL_LIBRARY_SUFFIX) or stripped.endswith(
                    _AUTOGENERATED_SUFFIX
                ):
                    continue
                results.append((start_row, stripped))
    except tokenize.TokenError:
        pass
    return results


def test_no_file_over_1000_lines() -> None:
    """No .py file in ralph/ or tests/ may exceed 1000 lines."""
    violations = []
    for base in (RALPH_DIR, TESTS_DIR):
        for path in _all_py_files(base):
            n = _count_lines(path)
            if n > _MAX_FILE_LINES:
                rel = str(path.relative_to(REPO_ROOT))
                violations.append(f"{n} lines: {rel}")

    assert not violations, (
        f"Files exceeding 1000 lines ({len(violations)} violations):\n"
        + "\n".join(sorted(violations))
    )


def test_one_class_per_file() -> None:
    """Each maintained source file in ralph/ and tests/ must have at most one top-level class."""
    violations = []
    for base in (RALPH_DIR, TESTS_DIR):
        for path in _all_py_files(base):
            classes = _top_level_classes(path)
            if len(classes) > 1:
                rel = str(path.relative_to(REPO_ROOT))
                violations.append(f"{len(classes)} classes in {rel}: {classes[:5]}")

    assert not violations, (
        f"Files with multiple top-level classes ({len(violations)} violations):\n"
        + "\n".join(sorted(violations))
    )


def test_no_private_imports_from_ralph_in_tests() -> None:
    """Test files must not import private symbols (starting with _) from ralph.* modules."""
    violations = []
    for path in _all_py_files(TESTS_DIR):
        for mod, names in _private_ralph_imports(path):
            rel = str(path.relative_to(REPO_ROOT))
            violations.append(f"{rel}: from {mod} import {names}")

    assert not violations, (
        f"Private ralph.* imports in tests ({len(violations)} violations):\n"
        + "\n".join(sorted(violations))
    )


def test_no_type_ignore_or_noqa_in_maintained_source() -> None:
    """No type-check or lint-bypass comments in ralph/ or tests/."""
    violations = []
    for base in (RALPH_DIR, TESTS_DIR):
        for path in _all_py_files(base):
            hits = _has_bypass_comment(path)
            if hits:
                rel = str(path.relative_to(REPO_ROOT))
                for lineno, line in hits:
                    violations.append(f"{rel}:{lineno}: {line}")

    assert not violations, f"Bypass comments found ({len(violations)} violations):\n" + "\n".join(
        sorted(violations)
    )


def _nested_classes_in_class_body(path: Path) -> list[tuple[int, str, str]]:
    src = _read_path(path)
    results: list[tuple[int, str, str]] = []
    indent_level = 0
    class_stack: list[tuple[str, int]] = []
    pending_class_name: str | None = None
    pending_class_outer: str | None = None

    try:
        tokens = tokenize.generate_tokens(io.StringIO(src).readline)
        for tok_type, tok_string, (start_row, _), *_rest in tokens:
            if tok_type == tokenize.INDENT:
                indent_level += 1
                if pending_class_name is not None:
                    class_stack.append((pending_class_name, indent_level))
                    pending_class_name = None
                    pending_class_outer = None
                continue
            if tok_type == tokenize.DEDENT:
                indent_level = max(0, indent_level - 1)
                while class_stack and class_stack[-1][1] > indent_level:
                    class_stack.pop()
                continue
            if tok_type == tokenize.NAME and tok_string == "class":
                pending_class_name = None
                pending_class_outer = class_stack[-1][0] if class_stack else None
                continue
            if pending_class_outer is not None and tok_type == tokenize.NAME:
                if indent_level > 0:
                    results.append((start_row, pending_class_outer, tok_string))
                pending_class_name = tok_string
                pending_class_outer = None
                continue
            if pending_class_outer is not None and tok_type not in {
                tokenize.NL,
                tokenize.NEWLINE,
                tokenize.COMMENT,
            }:
                pending_class_outer = None
    except tokenize.TokenError:
        return []
    return results


def test_no_nested_classes_in_class_body() -> None:
    """No class definitions nested inside another class body in ralph/ or tests/."""
    violations = []
    for base in (RALPH_DIR, TESTS_DIR):
        for path in _all_py_files(base):
            rel = str(path.relative_to(REPO_ROOT))
            for lineno, outer, inner in _nested_classes_in_class_body(path):
                violations.append(f"{rel}:{lineno}: {outer}.{inner}")
    assert not violations, (
        f"Nested class definitions found ({len(violations)} violations):\n"
        + "\n".join(sorted(violations))
    )


def test_mypy_ini_has_no_ignore_missing_imports() -> None:
    """mypy.ini must not contain ignore_missing_imports = true."""
    text = MYPY_INI_PATH.read_text(encoding="utf-8")

    violations = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        if "ignore_missing_imports" in line and "= true" in line.lower():
            violations.append(f"line {lineno}: {line.strip()}")

    assert not violations, (
        "mypy.ini contains ignore_missing_imports = true suppressions. "
        "All third-party imports must be properly typed or stubbed. "
        "Violations:\n" + "\n".join(violations)
    )


def test_mypy_ini_has_no_follow_imports_silent() -> None:
    """mypy.ini must not contain follow_imports = silent."""
    text = MYPY_INI_PATH.read_text(encoding="utf-8")

    violations = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        if "follow_imports" in line and "= silent" in line.lower():
            violations.append(f"line {lineno}: {line.strip()}")

    assert not violations, (
        "mypy.ini contains follow_imports = silent suppressions. "
        "All third-party imports must be properly typed or stubbed. "
        "Silently skipping type checking bypasses the type system. "
        "Violations:\n" + "\n".join(violations)
    )


def test_pyproject_has_no_per_file_ignores() -> None:
    """pyproject.toml must not contain [tool.ruff.lint.per-file-ignores]."""
    pyproject = tomllib.loads(PYPROJECT_PATH.read_text(encoding="utf-8"))

    violations = []
    tool = pyproject.get("tool", {})
    ruff = tool.get("ruff", {})
    lint = ruff.get("lint", {})
    per_file_ignores = lint.get("per-file-ignores", {})

    if per_file_ignores:
        for file_pattern, codes in per_file_ignores.items():
            violations.append(f"[tool.ruff.lint.per-file-ignores]['{file_pattern}'] = {codes}")

    assert not violations, (
        "pyproject.toml contains [tool.ruff.lint.per-file-ignores] suppressions. "
        "All lint violations must be fixed, not suppressed per-file. "
        "Violations:\n" + "\n".join(violations)
    )


def test_repo_root_standalone_py_files_structural_rules() -> None:
    """conftest.py at repo root must satisfy structural rules identical to ralph/ and tests/.

    docs/sphinx/conf.py is intentionally excluded: it is Sphinx documentation
    tooling, not maintained application code, and the docs/ directory is
    explicitly excluded per this module's scope.
    """
    violations: list[str] = []
    for path in _REPO_ROOT_STANDALONE_FILES:
        if not path.exists():
            violations.append(f"Expected file not found: {path.relative_to(REPO_ROOT)}")
            continue
        n = _count_lines(path)
        if n > _MAX_FILE_LINES:
            violations.append(f"{n} lines (>{_MAX_FILE_LINES}): {path.relative_to(REPO_ROOT)}")
        classes = _top_level_classes(path)
        if len(classes) > 1:
            violations.append(f"{len(classes)} classes: {path.relative_to(REPO_ROOT)}: {classes}")
        for lineno, outer, inner in _nested_classes_in_class_body(path):
            violations.append(f"{path.relative_to(REPO_ROOT)}:{lineno}: {outer}.{inner}")
        for lineno, line in _has_bypass_comment(path):
            violations.append(f"{path.relative_to(REPO_ROOT)}:{lineno}: {line}")
    prefix = "Repo root standalone files structural violations:\n"
    assert not violations, prefix + "\n".join(violations)
