from __future__ import annotations

import configparser
import io
import tokenize
import tomllib
from functools import cache
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
WORKSPACE_ROOT = REPO_ROOT.parent
MYPY_INI_PATH = REPO_ROOT / "mypy.ini"
PYPROJECT_PATH = REPO_ROOT / "pyproject.toml"
EXTERNAL_LIBRARY_POLICY_REF = "docs/agents/type-ignore-policy.md#external-library"
AUTOGENERATED_POLICY_REF = "docs/agents/type-ignore-policy.md#autogenerated-code"


def _load_mypy_config() -> configparser.ConfigParser:
    parser = configparser.ConfigParser()
    parser.read(MYPY_INI_PATH, encoding="utf-8")
    return parser


def _load_pyproject() -> dict[str, object]:
    return tomllib.loads(PYPROJECT_PATH.read_text(encoding="utf-8"))


@cache
def _repo_python_files() -> tuple[Path, ...]:
    return tuple(path for path in REPO_ROOT.rglob("*.py") if ".venv" not in path.parts)


@cache
def _repo_type_ignore_lines() -> tuple[tuple[str, int, str], ...]:
    """Find actual inline type ignores and pyright directives, not string literals."""
    matches: list[tuple[str, int, str]] = []
    for path in _repo_python_files():
        text = path.read_text(encoding="utf-8")
        type_ignore_marker = "# type:" + " ignore"
        pyright_marker = "# py" + "right:"
        if type_ignore_marker not in text and pyright_marker not in text:
            continue
        rel_path = str(path.relative_to(REPO_ROOT))
        try:
            tokens = list(tokenize.tokenize(io.BytesIO(text.encode()).readline))
            type_ignore_marker = "# type:" + " ignore"
            pyright_marker = "# py" + "right:"
            matches.extend(
                (rel_path, token.start[0], token.line.rstrip())
                for token in tokens
                if token.type == tokenize.COMMENT and (
                    type_ignore_marker in token.string or pyright_marker in token.string
                )
            )
        except (tokenize.TokenError, UnicodeDecodeError):
            # Fallback: parse manually for files with encoding issues
            for line_number, line in enumerate(text.splitlines(), start=1):
                if _is_actual_type_ignore_comment(line) or _is_actual_pyright_comment(line):
                    matches.append((rel_path, line_number, line.rstrip()))
    return tuple(matches)


def _is_actual_type_ignore_comment(line: str) -> bool:
    """Check if type-ignore appears in an actual comment, not a string."""
    marker = "# type:" + " ignore"
    try:
        comment_idx = line.index(marker)
    except ValueError:
        return False
    before_comment = line[:comment_idx]
    in_single = False
    in_double = False
    i = 0
    while i < len(before_comment):
        if before_comment[i] == "\\":
            i += 2
            continue
        if before_comment[i] == "'" and not in_double:
            in_single = not in_single
        elif before_comment[i] == '"' and not in_single:
            in_double = not in_double
        i += 1
    return not (in_single or in_double)


def _is_actual_pyright_comment(line: str) -> bool:
    """Check if pyright directive appears in an actual comment, not a string."""
    marker = "# py" + "right:"
    try:
        comment_idx = line.index(marker)
    except ValueError:
        return False
    before_comment = line[:comment_idx]
    in_single = False
    in_double = False
    i = 0
    while i < len(before_comment):
        if before_comment[i] == "\\":
            i += 2
            continue
        if before_comment[i] == "'" and not in_double:
            in_single = not in_single
        elif before_comment[i] == '"' and not in_single:
            in_double = not in_double
        i += 1
    return not (in_single or in_double)


def test_mypy_requires_error_codes_on_type_ignores() -> None:
    parser = _load_mypy_config()
    enabled_codes = {
        code.strip()
        for code in parser["mypy"].get("enable_error_code", "").split(",")
        if code.strip()
    }

    assert "ignore-without-code" in enabled_codes



def test_ruff_enforces_blanket_type_ignore_rule() -> None:
    pyproject = _load_pyproject()
    tool = pyproject["tool"]
    assert isinstance(tool, dict)
    ruff = tool["ruff"]
    assert isinstance(ruff, dict)
    lint = ruff["lint"]
    assert isinstance(lint, dict)
    select = lint["select"]
    assert isinstance(select, list)

    assert "PGH" in select



@pytest.mark.timeout_seconds(5)
def test_repo_type_ignore_comments_follow_policy() -> None:
    blanket_offenders: list[str] = []
    reason_offenders: list[str] = []
    blanket_marker = "# type:" + " ignore"
    coded_marker_prefix = "# type:" + " ignore["
    external_library_suffix = (
        "# reason: external library has no type support, see "
        f"{EXTERNAL_LIBRARY_POLICY_REF}"
    )
    autogenerated_suffix = (
        "# reason: autogenerated code has no type support, see "
        f"{AUTOGENERATED_POLICY_REF}"
    )

    for rel_path, line_number, line in _repo_type_ignore_lines():
        if blanket_marker in line and coded_marker_prefix not in line:
            blanket_offenders.append(f"{rel_path}:{line_number}")
        if coded_marker_prefix not in line:
            continue
        if line.endswith(external_library_suffix) or line.endswith(autogenerated_suffix):
            continue
        reason_offenders.append(f"{rel_path}:{line_number}")

    assert blanket_offenders == []

    policy_prefix = "# type:" + " ignore"
    policy_message = (
        f"Every '{policy_prefix}[...]' must end with either '# reason: external library has no "
        "type support, see docs/agents/type-ignore-policy.md#external-library' or '# reason: "
        "autogenerated code has no type support, see "
        "docs/agents/type-ignore-policy.md#autogenerated-code'."
    )
    assert reason_offenders == [], policy_message



def test_zero_test_file_suppressions() -> None:
    """Test files must have zero suppressions."""
    test_suppressions: list[str] = []
    for rel_path, line_number, _ in _repo_type_ignore_lines():
        if "tests/" not in rel_path and "tests\\" not in rel_path:
            continue
        test_suppressions.append(f"{rel_path}:{line_number}")
    assert test_suppressions == [], (
        "Test files must not contain suppressions. "
        f"Found {len(test_suppressions)} in test files: {test_suppressions}"
    )


def test_external_library_policy_document_exists() -> None:
    policy_path = WORKSPACE_ROOT / EXTERNAL_LIBRARY_POLICY_REF.split("#", maxsplit=1)[0]
    assert policy_path.is_file(), f"Missing policy document: {EXTERNAL_LIBRARY_POLICY_REF}"


@pytest.mark.timeout_seconds(5)
def test_zero_runtime_pyright_directives() -> None:
    """Runtime code must have zero runtime directives from pyright."""
    runtime_pyright_directives: list[str] = []
    for rel_path, line_number, line in _repo_type_ignore_lines():
        if "tests/" in rel_path or "tests\\" in rel_path:
            continue
        if "# py" + "right:" in line:
            runtime_pyright_directives.append(f"{rel_path}:{line_number}")
    assert runtime_pyright_directives == [], (
        "Runtime code must not contain directives from py" + "right. "
        "Use # type:" + " ignore[...] with reason comments instead. "
        f"Found {len(runtime_pyright_directives)}: {runtime_pyright_directives}"
    )


