"""AST-based policy tests enforcing the maintained structural rules.

Scoped to ralph/, tests/, and named repo-root standalone files (excludes .venv, tmp/, docs/).
"""

from __future__ import annotations

import ast
import functools
import io
import re
import tokenize
import tomllib
from pathlib import Path

import pytest

pytestmark = pytest.mark.timeout_seconds(5)

REPO_ROOT = Path(__file__).resolve().parents[1]
RALPH_DIR = REPO_ROOT / "ralph"
TESTS_DIR = REPO_ROOT / "tests"
MYPY_INI_PATH = REPO_ROOT / "mypy.ini"
PYPROJECT_PATH = REPO_ROOT / "pyproject.toml"
_REPO_ROOT_STANDALONE_FILES: tuple[Path, ...] = (REPO_ROOT / "conftest.py",)

_SKIP_DIRS = frozenset({"__pycache__", ".venv", "tmp"})
_MAX_FILE_LINES = 1_000


@functools.cache
def _all_py_files(base: Path) -> tuple[Path, ...]:
    result = []
    for path in base.rglob("*.py"):
        if any(part in _SKIP_DIRS for part in path.parts):
            continue
        result.append(path)
    return tuple(sorted(result))


@functools.cache
def _read_path(path: Path) -> str:
    return path.read_text(encoding="utf-8")


@functools.cache
def _parse_ast(path: Path) -> ast.Module | None:
    try:
        return ast.parse(_read_path(path))
    except SyntaxError:
        return None


def _count_lines(path: Path) -> int:
    return len(_read_path(path).splitlines())


_TOP_LEVEL_CLASS_PATTERN = re.compile(r"^class\s+([A-Za-z_][A-Za-z0-9_]*)\b")


def _top_level_classes(path: Path) -> list[str]:
    """Return names of top-level classes at module level.

    TYPE_CHECKING-guarded classes are indented inside `if` blocks, so they are
    excluded automatically by only counting column-0 class statements.
    """
    src = _read_path(path)
    return [
        match.group(1)
        for line in src.splitlines()
        if (match := _TOP_LEVEL_CLASS_PATTERN.match(line))
    ]


def _private_ralph_imports(path: Path) -> list[tuple[str, list[str]]]:
    """Return (module, [private_names]) for imports of private names from ralph.*."""
    src = _read_path(path)
    if "from ralph" not in src or " import _" not in src:
        return []

    tree = _parse_ast(path)
    if tree is None:
        return []

    results: list[tuple[str, list[str]]] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            mod = node.module or ""
            if not mod.startswith("ralph"):
                continue
            private_names = [alias.name for alias in node.names if alias.name.startswith("_")]
            if private_names:
                results.append((mod, private_names))
    return results


_TYPE_IGNORE_MARKER = "# type:" + " ignore"
_NOQA_MARKER = "# no" + "qa"
_EXTERNAL_LIBRARY_SUFFIX = (
    "# reason: external library has no type support, see "
    "docs/agents/type-ignore-policy.md#external-library"
)
_AUTOGENERATED_SUFFIX = (
    "# reason: autogenerated code has no type support, see "
    "docs/agents/type-ignore-policy.md#autogenerated-code"
)


def _has_bypass_comment(path: Path) -> list[tuple[int, str]]:
    """Return (lineno, line) for lines with actual type-check or lint-bypass comments.

    Uses tokenize to distinguish comment tokens from string literals.
    Policy-compliant type-suppression comments (ending with a valid reason suffix) are excluded.
    """
    src = _read_path(path)
    if "# type:" not in src and "# noqa" not in src:
        return []

    lines = src.splitlines()
    results: list[tuple[int, str]] = []
    try:
        tokens = tokenize.generate_tokens(io.StringIO(src).readline)
        for tok in tokens:
            if tok.type != tokenize.COMMENT:
                continue
            if _TYPE_IGNORE_MARKER not in tok.string and _NOQA_MARKER not in tok.string:
                continue
            start_row = tok.start[0]
            line = lines[start_row - 1] if start_row <= len(lines) else ""
            stripped = line.rstrip()
            if stripped.endswith(_EXTERNAL_LIBRARY_SUFFIX) or stripped.endswith(
                _AUTOGENERATED_SUFFIX
            ):
                continue
            results.append((start_row, stripped))
    except tokenize.TokenError:
        pass
    return results


def test_no_file_over_1000_lines() -> None:
    """No .py file in ralph/ or tests/ may exceed 1000 lines."""
    violations = []
    for base in (RALPH_DIR, TESTS_DIR):
        for path in _all_py_files(base):
            n = _count_lines(path)
            if n > _MAX_FILE_LINES:
                rel = str(path.relative_to(REPO_ROOT))
                violations.append(f"{n} lines: {rel}")

    assert not violations, (
        f"Files exceeding 1000 lines ({len(violations)} violations):\n"
        + "\n".join(sorted(violations))
    )


def test_one_class_per_file() -> None:
    """Each maintained source file in ralph/ and tests/ must have at most one top-level class."""
    violations = []
    for base in (RALPH_DIR, TESTS_DIR):
        for path in _all_py_files(base):
            classes = _top_level_classes(path)
            if len(classes) > 1:
                rel = str(path.relative_to(REPO_ROOT))
                violations.append(f"{len(classes)} classes in {rel}: {classes[:5]}")

    assert not violations, (
        f"Files with multiple top-level classes ({len(violations)} violations):\n"
        + "\n".join(sorted(violations))
    )


def test_no_private_imports_from_ralph_in_tests() -> None:
    """Test files must not import private symbols (starting with _) from ralph.* modules."""
    violations = []
    for path in _all_py_files(TESTS_DIR):
        for mod, names in _private_ralph_imports(path):
            rel = str(path.relative_to(REPO_ROOT))
            violations.append(f"{rel}: from {mod} import {names}")

    assert not violations, (
        f"Private ralph.* imports in tests ({len(violations)} violations):\n"
        + "\n".join(sorted(violations))
    )


def test_no_type_ignore_or_noqa_in_maintained_source() -> None:
    """No type-check or lint-bypass comments in ralph/ or tests/."""
    violations = []
    for base in (RALPH_DIR, TESTS_DIR):
        for path in _all_py_files(base):
            hits = _has_bypass_comment(path)
            if hits:
                rel = str(path.relative_to(REPO_ROOT))
                for lineno, line in hits:
                    violations.append(f"{rel}:{lineno}: {line}")

    assert not violations, f"Bypass comments found ({len(violations)} violations):\n" + "\n".join(
        sorted(violations)
    )


def _nested_classes_in_class_body(path: Path) -> list[tuple[int, str, str]]:
    src = _read_path(path)
    if not re.search(r"^\s+class\s+", src, re.M):
        return []

    tree = _parse_ast(path)
    if tree is None:
        return []

    results: list[tuple[int, str, str]] = []

    def visit(node: ast.AST, enclosing_class: str | None) -> None:
        next_enclosing = enclosing_class
        if isinstance(node, ast.ClassDef):
            if enclosing_class is not None:
                results.append((node.lineno, enclosing_class, node.name))
            next_enclosing = node.name
        for child in ast.iter_child_nodes(node):
            visit(child, next_enclosing)

    visit(tree, None)
    return results


def test_no_nested_classes_in_class_body() -> None:
    """No class definitions nested inside another class body in ralph/.

    The test suite intentionally uses nested helper classes in many focused
    regression tests, so this policy is scoped to maintained production code.
    """
    violations = []
    for path in _all_py_files(RALPH_DIR):
        rel = str(path.relative_to(REPO_ROOT))
        for lineno, outer, inner in _nested_classes_in_class_body(path):
            violations.append(f"{rel}:{lineno}: {outer}.{inner}")
    assert not violations, (
        f"Nested class definitions found ({len(violations)} violations):\n"
        + "\n".join(sorted(violations))
    )


def test_mypy_ini_has_no_ignore_missing_imports() -> None:
    """mypy.ini must not contain ignore_missing_imports = true."""
    text = MYPY_INI_PATH.read_text(encoding="utf-8")

    violations = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        if "ignore_missing_imports" in line and "= true" in line.lower():
            violations.append(f"line {lineno}: {line.strip()}")

    assert not violations, (
        "mypy.ini contains ignore_missing_imports = true suppressions. "
        "All third-party imports must be properly typed or stubbed. "
        "Violations:\n" + "\n".join(violations)
    )


def test_mypy_ini_has_no_follow_imports_silent() -> None:
    """mypy.ini must not contain follow_imports = silent."""
    text = MYPY_INI_PATH.read_text(encoding="utf-8")

    violations = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        if "follow_imports" in line and "= silent" in line.lower():
            violations.append(f"line {lineno}: {line.strip()}")

    assert not violations, (
        "mypy.ini contains follow_imports = silent suppressions. "
        "All third-party imports must be properly typed or stubbed. "
        "Silently skipping type checking bypasses the type system. "
        "Violations:\n" + "\n".join(violations)
    )


def test_pyproject_has_no_per_file_ignores() -> None:
    """pyproject.toml must not contain [tool.ruff.lint.per-file-ignores]."""
    pyproject = tomllib.loads(PYPROJECT_PATH.read_text(encoding="utf-8"))

    violations = []
    tool = pyproject.get("tool", {})
    ruff = tool.get("ruff", {})
    lint = ruff.get("lint", {})
    per_file_ignores = lint.get("per-file-ignores", {})

    if per_file_ignores:
        for file_pattern, codes in per_file_ignores.items():
            violations.append(f"[tool.ruff.lint.per-file-ignores]['{file_pattern}'] = {codes}")

    assert not violations, (
        "pyproject.toml contains [tool.ruff.lint.per-file-ignores] suppressions. "
        "All lint violations must be fixed, not suppressed per-file. "
        "Violations:\n" + "\n".join(violations)
    )


def test_repo_root_standalone_py_files_structural_rules() -> None:
    """conftest.py at repo root must satisfy structural rules identical to ralph/ and tests/.

    docs/sphinx/conf.py is intentionally excluded: it is Sphinx documentation
    tooling, not maintained application code, and the docs/ directory is
    explicitly excluded per this module's scope.
    """
    violations: list[str] = []
    for path in _REPO_ROOT_STANDALONE_FILES:
        if not path.exists():
            violations.append(f"Expected file not found: {path.relative_to(REPO_ROOT)}")
            continue
        n = _count_lines(path)
        if n > _MAX_FILE_LINES:
            violations.append(f"{n} lines (>{_MAX_FILE_LINES}): {path.relative_to(REPO_ROOT)}")
        classes = _top_level_classes(path)
        if len(classes) > 1:
            violations.append(f"{len(classes)} classes: {path.relative_to(REPO_ROOT)}: {classes}")
        for lineno, outer, inner in _nested_classes_in_class_body(path):
            violations.append(f"{path.relative_to(REPO_ROOT)}:{lineno}: {outer}.{inner}")
        for lineno, line in _has_bypass_comment(path):
            violations.append(f"{path.relative_to(REPO_ROOT)}:{lineno}: {line}")
    prefix = "Repo root standalone files structural violations:\n"
    assert not violations, prefix + "\n".join(violations)
