import js from "@eslint/js";
import tseslint from "typescript-eslint";
import angular from "angular-eslint";

// ============================================================================
// LINT POLICY FILE -- DO NOT WEAKEN, DISABLE, OR RELAX RULES WITHOUT EXPLICIT
// USER/MAINTAINER DIRECTION. REFRACTOR THE CODE INSTEAD. "BEING LAZY TO
// REFACTOR" IS NOT A VALID REASON TO CHANGE LINTING BEHAVIOR. THE ONLY
// EXCEPTION IS DOCUMENTED AUTOGENERATED CODE HANDLED BY THE REPOSITORY'S
// APPROVED MECHANISM.
// ============================================================================

export default tseslint.config(
  { ignores: ["dist", "coverage", "node_modules", "**/*.spec.ts", "**/*.test.ts"] },
  {
    files: ["**/*.ts"],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
    ],
    languageOptions: {
      parserOptions: {
        project: "./tsconfig.json",
      },
    },
    rules: {
      // Core type safety rules
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/consistent-type-imports": ["warn", { "prefer": "type-imports" }],
      "@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern": "^_" }],
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      // Relax strict rules for this project
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-unnecessary-condition": "off",
      "@typescript-eslint/prefer-readonly-parameter-types": "off",
    },
  },
  {
    files: ["**/*.component.ts"],
    extends: [...angular.configs.tsRecommended],
    rules: {
      "@angular-eslint/component-class-suffix": "error",
      "@angular-eslint/component-selector": ["error", { "type": "element", "prefix": "app", "style": "kebab-case" }],
      "@angular-eslint/directive-class-suffix": "error",
      "@angular-eslint/directive-selector": ["error", { "type": "attribute", "prefix": "app", "style": "camelCase" }],
      "@angular-eslint/prefer-on-push-component-change-detection": "error",
      "@angular-eslint/prefer-standalone": "error",
      // Do not relax lint rules to avoid refactors. Keep inline templates small.
      "@angular-eslint/component-max-inline-declarations": ["error", { "template": 3 }],
      "@angular-eslint/sort-keys-in-type-decorator": "off",
      "@angular-eslint/consistent-component-styles": "off",
      // Allow legacy @Input/@Output for now
      "@angular-eslint/prefer-signals": "off",
      "@angular-eslint/prefer-output-emitter-ref": "off",
      "@angular-eslint/prefer-output-readonly": "off",
      // Allow forwardRef
      "@angular-eslint/no-forward-ref": "off",
    },
  },
  {
    files: ["**/*.html"],
    extends: [...angular.configs.templateRecommended],
    rules: {
      "@angular-eslint/template/no-call-expression": "warn",
      "@angular-eslint/template/eqeqeq": "error",
      // i18n is not needed for this internal tool
      "@angular-eslint/template/i18n": "off",
    },
  }
);
